testing

diff --git a/deployTKGmc b/deployTKGmc
--- a/deployTKGmc
+++ b/deployTKGmc
@@ -264,10 +264,9 @@ configureLetsEnscript() {
     route53createHostedZone $domain
 
     echo "-------------------------------------- GENERATE LET'S-ENCRYPT CERTIFICATES -------------------------------------"
-    typ=$(echo $domain | egrep -c "aztkg|awstkg|gcptkg")
+    typ=$(echo $domain | egrep -c "aztkg|awstkg|gcptkg|vstkg")
     if [ $typ -ne 0 ]; then
       messageTitle "Generate Certificate for PKS Domains ($domain)"
-      #$SSH_COMMAND -n "echo \"/usr/bin/certbot certonly --dns-route53 -d '*.$domain' -d '*.api.$domain' -d '*.contour-tdh.$domain'\" -d '*.nginx-tdh.$domain'\""
       $SSH_COMMAND -n "sudo /usr/local/bin/certbot certonly --dns-route53 -d '*.$domain' -d '*.apps-tdh-1.$domain' -d '*.nginx-tdh-1.$domain' \
                 -d '*.nginx-tdh-1.$domain' -d '*.apps-tdh-2.$domain' -d '*.apps-tdh-3.$domain' -m sadubois@pivotal.io --agree-tos -n --expand"
       if [ $? -ne 0 ]; then
@@ -554,13 +553,21 @@ checkKeyPairs
 # --- CREATE TKG CLUSTER AND JUMP SERVER
 createJumpHost
 sshEnvironment
+echo "1-SSH_COMMAND:$SSH_COMMAND"
 configureJumpHost
+echo "2-SSH_COMMAND:$SSH_COMMAND"
 
 configureLetsEnscript
+echo "3-SSH_COMMAND:$SSH_COMMAND"
 
 # --- UPLOAD OVA IMAGES TO VCENTER ---
 if [ "${TDH_DEPLOYMENT_ENV_NAME}" == "vSphere" ]; then
   $SSH_COMMAND -n "[ -f $SSH_HOME/tanzu-demo-hub/scripts/uploadOVAimages.sh ] && tanzu-demo-hub/scripts/uploadOVAimages.sh $DEPLOY_TKG_TEMPLATE"
+
+  docker ps > /dev/null 2>&1
+  if [ $? -ne 0 ]; then 
+    echo "ERROR: Docker Daemon not running"; exit
+  fi
 
   #$TDHPATH/scripts/InstallTKGmc.sh $DEPLOY_TKG_TEMPLATE
   scripts/InstallTKGmc.sh $DEPLOY_TKG_TEMPLATE
