improved stability in vsphere clusters and management clusters

diff --git a/deployTKG b/deployTKG
--- a/deployTKG
+++ b/deployTKG
@@ -13,10 +13,8 @@ export NATIVE=0
 export DEPLOY_TKG_CLEAN=0
 export TDH_TKGWC_K8S_VERSION=""
 export TDH_TANZU_MISSION_CONTROL_REGISTRATION=true
-export TDH_TOOLS=tdh-tools
 
 # --- SETTING FOR TDH-TOOLS ---
-export NATIVE=0                ## NATIVE=1 r(un on local host), NATIVE=0 (run within docker)
 export START_COMMAND="$*"
 export CMD_EXEC=$(basename $0)
 export CMD_ARGS=$*
@@ -25,33 +23,9 @@ export CMD_ARGS=$*
 [ -f $TANZU_DEMO_HUB/functions ] && . $TANZU_DEMO_HUB/functions
 [ -f $HOME/.tanzu-demo-hub.cfg ] && . $HOME/.tanzu-demo-hub.cfg
 
-while [ "$1" != "" ]; do
-  case $1 in
-    -d)   TKG_DEPLOYMENT=$2;;
-    -m)   TDH_TKGMC_NAME=$2;;
-    -n)   TDH_TKGWC_NAME=$2;;
-    -k)   TDH_TKGWC_K8S_VERSION=$2;;
-    -tag) TDH_TKGWC_NAME_TAG=$2;;
-    --debug)       DEBUG=1;;
-    --delete)      DEPLOY_TKG_CLEAN=1;;
-    --native)      NATIVE=1;;
-  esac
-  shift
-done
-
-############################################################################################################################
-################################### EXECUTING CODE WITHIN  TDH-TOOLS DOCKER CONTAINER  ######################################
-#############################################################################################################################
-runTDHtools tkg "Deploy TKG Workload Cluster" "$TDHPATH/$CMD_EXEC" "$CMD_ARGS"
-
-# --- FIX MANAGEMENT SERVER NAME INSTEAD OF ITS DEPLOYMENT FILE NAME ---
-if [ -f $HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME} -o $HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.cfg ]; then
-  [ -f $HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME} ] && TDH_TKGMC_NAME=$(echo "$TDH_TKGMC_NAME" | awk -F'.' '{ print $1 }')
-fi
-
 usage() {
   echo ""
-  echo "USAGE: $0 [options] -m <mgmt-cluster> -d <deployment> -n <cluster-name> [-k <kubernetes-version>] [--debug]"
+  echo "USAGE: $0 [options] -d <tkg-deployment.cfg> -c <tkg-configuration.cfg> -n <cluster-name> [-k <kubernetes-version>] [--debug]"
   echo "            Options:  -n  <cluster-name>        # Should reflect the environment and its purpose. Make sure"
   echo "                                                # to add your user name, to prevent conflicts in TMC"
   echo "                                                # ie. tdh-azure-sdubois or tdh-aws-sdubois-aws"
@@ -66,22 +40,66 @@ usage() {
   echo ""
 }
 
-listClusterConfig() {
-  echo
-  printf "%-31s %-5s %-15s %-20s %-5s %s\n" "DEPLOYMENT" "PLAN" "DESCRIPTION" 
-  echo "-----------------------------------------------------------------------------------------------------------"
+while [ "$1" != "" ]; do
+  case $1 in
+    -d)   TKG_DEPLOYMENT=$2;;
+    -c)   TKG_CONFIGURATION=$2;;
+    -n)   TDH_TKGWC_NAME=$2;;
+    -k)   TDH_TKGWC_K8S_VERSION=$2;;
+    -tag) TDH_TKGWC_NAME_TAG=$2;;
+    --debug)       DEBUG=1;;
+    --delete)      DEPLOY_TKG_CLEAN=1;;
+    --native)      NATIVE=1;;
+  esac
+  shift
+done
 
-  for deployment in $(ls -1 ${TDHPATH}/deployments/tkg-*.cfg | grep -v "tkgmc-"); do
-    TDH_DEPLOYMENT_DESCRIPTION=$(egrep "^TDH_DEPLOYMENT_DESCRIPTION=" $deployment | awk -F'=' '{ print $2 }' | sed 's/"//g')
-    TDH_DEPLOYMENT_CLUSTER_PLAN=$(egrep "^TDH_DEPLOYMENT_CLUSTER_PLAN=" $deployment | awk -F'=' '{ print $2 }')
+if [ "${TKG_DEPLOYMENT}" == "" -o "${TKG_CONFIGURATION}" == "" ]; then
+  [ "${TKG_DEPLOYMENT}" == "" ] && listTKGmc
+  [ "${TKG_CONFIGURATION}" == "" ] && listClusterConfig
 
-    dep=$(basename $deployment)
+  usage; exit 0
+fi
 
-    printf "%-31s %-5s %-15s %-20s %-5s %s\n" $dep "$TDH_DEPLOYMENT_CLUSTER_PLAN" "$TDH_DEPLOYMENT_DESCRIPTION"
-  done
+# --- VERIFY DEPLOYMENT ---
+if [ -f $HOME/.tanzu-demo-hub/config/${TKG_DEPLOYMENT} ]; then
+  TMC_DEPLOYMENT_CONFIG=${HOME}/.tanzu-demo-hub/config/${TKG_DEPLOYMENT}
+  TDH_TKGMC_NAME=$(egrep "^TDH_TKGMC_NAME=" $TMC_DEPLOYMENT_CONFIG | awk -F'=' '{ print $2 }' | sed 's/"//g')
+  TDH_TKGMC_TOOLS_CONTAINER=$(egrep "^TDH_TKGMC_TOOLS_CONTAINER=" $TMC_DEPLOYMENT_CONFIG | awk -F'=' '{ print $2 }' | sed 's/"//g' | awk -F'-' '{ print $NF }')
+  K8S_TKGMC=$(echo $TDH_TKGMC_TOOLS_CONTAINER | awk -F'.' '{ printf("%s.%s\n",$1,$2) }')
 
-  echo "-----------------------------------------------------------------------------------------------------------"
-}
+  . $HOME/.tanzu-demo-hub/config/${TKG_DEPLOYMENT}
+else
+  echo "ERROR: Deployment file $TKG_DEPLOYMENT can not be found in the directory:"
+  echo "       $HOME/.tanzu-demo-hub/config"
+  exit 1
+fi
+
+
+if [ -f $TDHPATH/deployments/$TKG_CONFIGURATION ]; then
+  TKG_TANZU_KUBERNETES_GRID=$(egrep "^TKG_TANZU_KUBERNETES_GRID=" $TDHPATH/deployments/$TKG_CONFIGURATION | awk -F'=' '{ print $2 }') 
+  K8S_TKGWC=$(echo $TKG_TANZU_KUBERNETES_GRID | awk -F'.' '{ printf("%s.%s\n",$1,$2) }')
+
+  if [ "$K8S_TKGMC" != "$K8S_TKGWC" ]; then 
+    K8S_SHORT=$(echo $TDH_TKGMC_TOOLS_CONTAINER | awk -F'.' '{ printf("%s.%s.x\n",$1,$2) }') 
+    echo "ERROR: Management Cluster ($TDH_TKGMC_NAME) deployed with $TKG_DEPLOYMENT has been configured"
+    echo "       with TKG ${K8S_TKGMC}.x, but the TKG Workload Cluster defined in $TKG_CONFIGURATION"
+    echo "       requires TKG ${K8S_TKGWC}.x. Please use a TDK Configuration supporteing TKG $K8S_SHORT instead"
+    echo ""
+    exit
+  fi
+
+  . ${TDHPATH}/deployments/$TKG_CONFIGURATION
+else
+  echo "ERROR: Deployment file $TKG_DEPLOYMENT can not be found in the directory:"
+  echo "       $TDHPATH/deployments or $HOME/.tanzu-demo-hub/config"
+  exit 1
+fi
+
+############################################################################################################################
+################################### EXECUTING CODE WITHIN  TDH-TOOLS DOCKER CONTAINER  ######################################
+#############################################################################################################################
+runTDHtools "$TDH_TOOLS_CONTAINER_TYPE" "$TDH_TOOLS_CONTAINER_VERS" "Deploy TKG Workload Cluster" "$TDHPATH/$CMD_EXEC" "$CMD_ARGS"
 
 listDeployments() {
   echo
@@ -134,37 +152,6 @@ listDeployments() {
   echo "-----------------------------------------------------------------------------------------------------------"
 }
 
-if [ "${TKG_DEPLOYMENT}" == "" -o "${TDH_TKGMC_NAME}" == "" ]; then
-  if [ "${TKG_DEPLOYMENT}" == "" ]; then 
-    listDeployments
-  fi
-
-  if [ "${TKG_WC_CLUSTER}" == "" ]; then 
-    listClusterConfig
-  fi
-
-  usage; exit 0
-fi
-
-# --- VERIFY DEPLOYMENT ---
-TKG_DEPLOYMENT_CONFIG=$(echo $TKG_DEPLOYMENT | sed 's/cfg/yaml/g')
-if [ ! -f ${TDHPATH}/deployments/${TKG_DEPLOYMENT} ]; then
-  echo "ERROR: Deployment file $TKG_DEPLOYMENT can not be found in ${TDHPATH}/deployments"
-  exit 1
-else
-  . ${TDHPATH}/deployments/${TKG_DEPLOYMENT}
-fi
-
-# --- CHECK ENVIRONMENT VARIABLES ---
-if [ -f ~/.tanzu-demo-hub.cfg ]; then
-  . ~/.tanzu-demo-hub.cfg
-fi
-
-# --- SOURCE MANAGEMENT CLUSTER VARIABLES ---
-if [ -f $HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.cfg ]; then
-  . $HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.cfg
-fi
-
 if [ "$TDH_DEPLOYMENT_CLUSTER_PLAN" == "dev" ]; then
   TDH_TKGMC_CONFIG=$TDH_TKGMC_WC_CONFIG_DEV
 else
@@ -172,7 +159,7 @@ else
 fi
 
 # --- SET THE CLUSTER NAME IF NON HAS SET WITH COMMAND LINE ARGS ---
-[ "$TDH_TKGWC_NAME" == "" ] && TDH_TKGWC_NAME="tdh-$(echo $TDH_TKGMC_INFRASTRUCTURE | tr "[A-Z]" "[a.z]")-$TDH_USER"
+[ "$TDH_TKGWC_NAME" == "" ] && TDH_TKGWC_NAME="tdh-$(echo $TDH_TKGMC_INFRASTRUCTURE | tr "[A-Z]" "[a-z]")-$TDH_USER"
 
 # --- DIRTY FIX ---
 export TDH_INFRASTRUCTURE=$TDH_TKGMC_INFRASTRUCTURE
@@ -263,149 +250,7 @@ if [ "$TDH_TKGWC_K8S_VERSION" != "" ]; then
   fi
 fi
 
-# --- GET TDH_TKGWC_CPIP_ADDRESS FROM NAME TAG ---
-if [ "${TDH_TKGMC_INFRASTRUCTURE}" == "vSphere" ]; then
-  if [ "$TDH_TKGWC_NAME_TAG" == "TKG_CLUSTER_01" -o "$TDH_TKGWC_NAME_TAG" == "TKG_CLUSTER_02" -o \
-       "$TDH_TKGWC_NAME_TAG" == "TKG_CLUSTER_03" ]; then
-
-    if [ "$TDH_TKGWC_NAME_TAG" == "TKG_CLUSTER_01" ]; then 
-      TDH_TKGWC_CPIP_ADDRESS=$VSPHERE_TKGM_WKLD_CLUSTER01_CONTROL_PLANE
-      TDH_TKGWC_LB_ADDRESS=$VSPHERE_TKGM_WKLD_CLUSTER01_LOADBALANCER_POOL
-    fi
-
-    if [ "$TDH_TKGWC_NAME_TAG" == "TKG_CLUSTER_02" ]; then 
-      TDH_TKGWC_CPIP_ADDRESS=$VSPHERE_TKGM_WKLD_CLUSTER02_CONTROL_PLANE
-      TDH_TKGWC_LB_ADDRESS=$VSPHERE_TKGM_WKLD_CLUSTER03_LOADBALANCER_POOL
-    fi
-
-    if [ "$TDH_TKGWC_NAME_TAG" == "TKG_CLUSTER_04" ]; then 
-      TDH_TKGWC_CPIP_ADDRESS=$VSPHERE_TKGM_WKLD_CLUSTER04_CONTROL_PLANE
-      TDH_TKGWC_LB_ADDRESS=$VSPHERE_TKGM_WKLD_CLUSTER04_LOADBALANCER_POOL
-    fi
-  else
-    echo "ERROR: Option -tag should be either: TKG_CLUSTER_01, TKG_CLUSTER_02 or TKG_CLUSTER_03"
-    usage; exit 0
-  fi
-
-  #TDH_TKGWC_CPIP_ADDRESS
-  #TDH_TKGWC_NAME_TAG
-fi
-
-messageTitle "Tanzu Kubernetes Grid Deployment"
-messagePrint " ▪ Management Cluster Name"               "$TDH_TKGMC_NAME"
-messagePrint " ▪ Management Cluster Configuration"      "deployments/${TDH_TKGMC_NAME}.cfg"
-messagePrint " ▪ Deployment Configuration"              "deployments/$TKG_DEPLOYMENT"
-messagePrint " ▪ Workload Cluster Name"                 "$TDH_TKGWC_NAME"
-messagePrint " ▪ Workload Cluster Cloud Config"         "$HOME/.tanzu/tkg/clusterconfigs/$TDH_TKGMC_CONFIG"
-messagePrint " ▪ Workload Cluster Configuration"        "deployments/$TKG_DEPLOYMENT"
-messagePrint " ▪ Workload Cluster consolidated Config"  "$HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml"
-
-[ "$TDH_DEPLOYMENT_CLUSTER_PLAN" == "dev" ] && DEP_SOURCE=$HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.yaml
-[ "$TDH_DEPLOYMENT_CLUSTER_PLAN" == "prod" ] && DEP_SOURCE=$HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.yaml
-
-# --- GENERATE WORKLOAD CLUSTER CONFIG FILE ---
-CLUSTER_CONFIG_FILE=$HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml
-
-# --- GET KUBERNETES VERSION ---
-if [ "$TDH_TKGWC_K8S_VERSION" == "" ]; then 
-  TDH_TKGWC_K8S_VERSION=$(tanzu kubernetes-release get | egrep "$TDH_TKGWC_KUBERNETES" | tail -1 | awk '{ print $1 }')
-fi
-
-# --- TKG ON VSPHERE RELEATED CONFIG ---
-if [ "${TDH_TKGMC_INFRASTRUCTURE}" == "vSphere" ]; then
-  # --- SET DEFAULT VALUES ---
-  [ "$TDH_TKGWC_CONTROL_PLANE_MEM_MIB" == "" ] && TDH_TKGWC_CONTROL_PLANE_MEM_MIB=8192
-  [ "$TDH_TKGWC_CONTROL_PLANE_NUM_CPUS" == "" ] && TDH_TKGWC_CONTROL_PLANE_NUM_CPUS=4
-  [ "$TDH_TKGWC_CONTROL_PLANE_DISK_GIB" == "" ] && TDH_TKGWC_CONTROL_PLANE_DISK_GIB=40
-  [ "$TDH_TKGWC_WORKER_DISK_GIB" == "" ] && TDH_TKGWC_WORKER_DISK_GIB=40
-  [ "$TDH_TKGWC_WORKER_MEM_MIB" == "" ] && TDH_TKGWC_WORKER_MEM_MIB=8192
-  [ "$TDH_TKGWC_WORKER_NUM_CPUS" == "" ] && TDH_TKGWC_WORKER_NUM_CPUS=2
-
-  messagePrint " ▪ Control Plane Machine CPU"     "$TDH_TKGWC_CONTROL_PLANE_NUM_CPUS"
-  messagePrint " ▪ Control Plane Machine Memory"  "$TDH_TKGWC_CONTROL_PLANE_MEM_MIB"
-  messagePrint " ▪ Control Plane Machine Disk"    "$TDH_TKGWC_CONTROL_PLANE_DISK_GIB"
-  messagePrint " ▪ Worker Node Machine CPU"       "$TDH_TKGWC_WORKER_NUM_CPUS"
-  messagePrint " ▪ Worker Node Machine Memory"    "$TDH_TKGWC_WORKER_MEM_MIB"
-  messagePrint " ▪ Worker Node Machine Disk"      "$TDH_TKGWC_WORKER_DISK_GIB"
-
-  # --- RESOURCE DEFINITIONS ---
-  str="^#|ENDPOINT|AZURE_RESOURCE_GROUP|AZURE_VNET_RESOURCE_GROUP|AZURE_NODE_MACHINE_TYPE|AZURE_CONTROL_PLANE_MACHINE_TYPE|CLUSTER_NAME|AZURE_VNET_NAME"
-  egrep -v "$str" $DEP_SOURCE | sed -e '/^$/d'                                    >  $CLUSTER_CONFIG_FILE
-  echo "CLUSTER_NAME: $TDH_TKGWC_NAME"                                            >> $CLUSTER_CONFIG_FILE
-  echo "WORKER_MACHINE_COUNT: $TDH_TKGWC_WORKERNODES"                             >> $CLUSTER_CONFIG_FILE
-  echo "CNI: antrea"                                                              >> $CLUSTER_CONFIG_FILE
-
-  echo "VSPHERE_CONTROL_PLANE_DISK_GIB: \"$TDH_TKGWC_CONTROL_PLANE_DISK_GIB\""    >> $CLUSTER_CONFIG_FILE
-  echo "VSPHERE_CONTROL_PLANE_MEM_MIB: \"$TDH_TKGWC_CONTROL_PLANE_MEM_MIB\""      >> $CLUSTER_CONFIG_FILE
-  echo "VSPHERE_CONTROL_PLANE_NUM_CPUS: \"$TDH_TKGWC_CONTROL_PLANE_NUM_CPUS\""    >> $CLUSTER_CONFIG_FILE
-  echo "VSPHERE_WORKER_DISK_GIB: \"$TDH_TKGWC_WORKER_DISK_GIB\""                  >> $CLUSTER_CONFIG_FILE
-  echo "VSPHERE_WORKER_MEM_MIB: \"$TDH_TKGWC_WORKER_MEM_MIB\""                    >> $CLUSTER_CONFIG_FILE
-  echo "VSPHERE_WORKER_NUM_CPUS: \"$TDH_TKGWC_WORKER_NUM_CPUS\""                  >> $CLUSTER_CONFIG_FILE
-
-  echo "VSPHERE_CONTROL_PLANE_ENDPOINT: $TDH_TKGWC_CPIP_ADDRESS"                  >> $CLUSTER_CONFIG_FILE
-fi
-
-if [ "${TDH_TKGMC_INFRASTRUCTURE}" == "Azure" ]; then
-  TDH_TKGWC_WORKERNODES_MACHINE=$(nodeType $TDH_TKGWC_WORKERNODES_TYPE)
-  TDH_TKGWC_CONTROPLANE_MACHINE=$(nodeType $TDH_TKGWC_CONTROPLANE_NODETYPE)
-
-  # --- SET DEFAULT VALUES ---
-  [ "$TDH_TKGWC_CONTROPLANE_MACHINE" == "" ] && TDH_TKGWC_CONTROPLANE_MACHINE=Standard_D4s_v3
-  [ "$TDH_TKGWC_WORKERNODES_MACHINE" == "" ] && TDH_TKGWC_WORKERNODES_MACHINE=Standard_D4s_v3
-
-  messagePrint " ▪ Kubernetes Version"               "$TDH_TKGWC_KUBERNETES"
-  messagePrint " ▪ Kubernetes Image"                 "$TDH_TKGWC_K8S_VERSION"
-  messagePrint " ▪ TKG Cluster Worker Nodes"         "$TDH_TKGWC_WORKERNODES"
-  messagePrint " ▪ TKG Cluster Worker Node Type"     "$TDH_TKGWC_WORKERNODES_TYPE ($TDH_TKGWC_WORKERNODES_MACHINE)"
-  messagePrint " ▪ TKG Control Plane Nodes"          "$TDH_TKGWC_CONTROPLANE"
-  messagePrint " ▪ TKG Control Plane Nodes Type"     "$TDH_TKGWC_CONTROPLANE_NODETYPE ($TDH_TKGWC_CONTROPLANE_MACHINE)"
-
-  str="AZURE_SUBSCRIPTION_ID|AZURE_TENANT_ID|AZURE_CLIENT_ID|AZURE_CLIENT_SECRET|AZURE_LOCATION|AZURE_SSH_PUBLIC_KEY_B64|CLUSTER_PLAN"
-  egrep "$str" $DEP_SOURCE                                                        >  $CLUSTER_CONFIG_FILE
-
-  echo "CLUSTER_NAME: $TDH_TKGWC_NAME"                                            >> $CLUSTER_CONFIG_FILE
-  echo "WORKER_MACHINE_COUNT: $TDH_TKGWC_WORKERNODES"                             >> $CLUSTER_CONFIG_FILE
-  echo "CNI: antrea"                                                              >> $CLUSTER_CONFIG_FILE
-  echo "AZURE_CONTROL_PLANE_MACHINE_TYPE: $TDH_TKGWC_CONTROPLANE_MACHINE"         >> $CLUSTER_CONFIG_FILE
-  echo "AZURE_NODE_MACHINE_TYPE: $TDH_TKGWC_WORKERNODES_MACHINE"                  >> $CLUSTER_CONFIG_FILE
-  echo "AZURE_RESOURCE_GROUP: $TDH_TKGWC_NAME"                                    >> $CLUSTER_CONFIG_FILE
-  echo "AZURE_VNET_RESOURCE_GROUP: $TDH_TKGWC_NAME"                               >> $CLUSTER_CONFIG_FILE
-  echo "AZURE_VNET_NAME: ${TDH_TKGWC_NAME}-vnet"                                  >> $CLUSTER_CONFIG_FILE
-  echo "ENABLE_MHC: true"                                                         >> $CLUSTER_CONFIG_FILE
-  echo "MHC_UNKNOWN_STATUS_TIMEOUT: 10m"                                          >> $CLUSTER_CONFIG_FILE
-  echo "MHC_FALSE_STATUS_TIMEOUT: 20m"                                            >> $CLUSTER_CONFIG_FILE
-fi
-
-[ "${TDH_TKGWC_CNI}" == "" ] && TDH_TKGWC_CNI=calico
-if [ "${TDH_TKGWC_CNI}" == "antrea" ]; then
-  echo "CNI: $TDH_TKGWC_CNI"                                                      >> $CLUSTER_CONFIG_FILE
-  echo "ANTREA_NO_SNAT: false"                                                    >> $CLUSTER_CONFIG_FILE
-  echo "ANTREA_TRAFFIC_ENCAP_MODE: \"encap\""                                     >> $CLUSTER_CONFIG_FILE
-  echo "ANTREA_PROXY: false"                                                      >> $CLUSTER_CONFIG_FILE
-  echo "ANTREA_POLICY: true"                                                      >> $CLUSTER_CONFIG_FILE
-  echo "ANTREA_TRACEFLOW: false"                                                  >> $CLUSTER_CONFIG_FILE
-else
-  echo "CNI: $TDH_TKGWC_CNI"                                                      >> $CLUSTER_CONFIG_FILE
-fi
-
-if [ $DEBUG -gt 0 ]; then 
-  echo "-----------------------------------------------------------------------------------------------------------"
-  cat $HOME/.tanzu/tkg/clusterconfigs/$TDH_TKGMC_CONFIG deployments/$TKG_DEPLOYMENT | egrep -v "^#" | sed -e '/^$/d'
-fi
-
-tanzu cluster get $TDH_TKGWC_NAME >/dev/null 2>&1; ret=$?
-if [ $ret -ne 0 ]; then  
-  echo "-----------------------------------------------------------------------------------------------------------"
-  echo "=> tanzu cluster create $TDH_TKGWC_NAME -f $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml --tkr $TDH_TKGWC_K8S_VERSION" 
-  tanzu cluster create $TDH_TKGWC_NAME -f $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml --tkr $TDH_TKGWC_K8S_VERSION 
-  echo "-----------------------------------------------------------------------------------------------------------"
-
-  #dockerPullImages="projects.registry.vmware.com/tkg/antrea/antrea-debian:v0.13.3_vmware.1 \
-  #                  projects.registry.vmware.com/tkg/tanzu_core/capabilities/capabilities-controller-manager:v1.4.1"
-fi
-
-# --- GET CREDENTIALS AND SET ENVIRONMENT ---
-tanzu cluster kubeconfig get $TDH_TKGWC_NAME --admin > /dev/null 2>&1
+tkgCreateCluster
 
 # --- CLEANUP KUNECONFIG ---
 cleanKubeconfig
@@ -421,9 +266,9 @@ runningPods kube-system
 runningPods tkg-system
 
 messageTitle "Waiting for Kapp Services to have completed starting"
-waitForKappServices   default     ${TDH_TKGWC_NAME}-kapp-controller-ctrl 
-waitForKappServices   tkg-system  ${TDH_TKGWC_CNI}-ctrl 
-waitForKappServices   tkg-system  tanzu-core-ctrl 
+#waitForKappServices   default     ${TDH_TKGWC_NAME}-kapp-controller-ctrl 
+#waitForKappServices   tkg-system  ${TDH_TKGWC_CNI}-ctrl 
+#waitForKappServices   tkg-system  tanzu-core-ctrl 
 
 uodateConfigMap tanzu-demo-hub TDH_DOMAIN                         $AWS_HOSTED_DNS_DOMAIN
 uodateConfigMap tanzu-demo-hub TDH_ENVNAME                        $TDH_TKGMC_ENVNAME
@@ -436,7 +281,7 @@ uodateConfigMap tanzu-demo-hub TDH_MANAGEMENT_CLUSTER             "$TDH_TKGMC_NA
 uodateConfigMap tanzu-demo-hub TDH_PROVISIONER_NAME               "$TMC_PROVISIONER_NAME"
 uodateConfigMap tanzu-demo-hub TDH_MISSION_CONTROL_ACCOUNT_NAME   "ukn"
 
-if [ "${TDH_TKGMC_INFRASTRUCTURE}" == "vSphere" ]; then
+if [ "${TDH_TKGMC_INFRASTRUCTURE}" == "vSphere" -a "$TDH_TKGMC_ENVNAME" != "tkgs" ]; then
   InstallMetallLB
 fi
 
@@ -445,8 +290,17 @@ fi
 #InstallContour
 #InstallHarborRegistry
 
+#  TKGS
+#  NAME                   REPOSITORY                                               TAG     STATUS               DETAILS  NAMESPACE                  
+#  tanzu-system-packages  projects.registry.vmware.com/tkg/packages/standard/repo  v1.5.0  Reconcile succeeded           default                    
+#  tkg-repo               projects.registry.vmware.com/tkg/packages/standard/repo  v1.5.0  Reconcile succeeded           tanzu-package-repo-global  
+#  TanzuPackage_AddRepo      tanzu-package-repo-global tkg-repo projects.registry.vmware.com/tkg/packages/standard/repo:v1.5.0
+#  TanzuPackage_RepoSync     tanzu-package-repo-global
+
+
+exit
 messageTitle "Tanzu Package Management"
-TanzuPackage_RepoSync     tanzu-package-repo-global
+TanzuPackage_RepoSync     default
 
 TanzuPackage_CertManager  cert-manager-pkg     cert-manager.tanzu.vmware.com 
 TanzuPackage_Contour      contour-pkg          contour.tanzu.vmware.com
@@ -455,6 +309,8 @@ getRootCA                 tanzu-demo-hub-tls
 TanzuPackage_Harbor       harbor-pkg           harbor.tanzu.vmware.com
 
 installBuildService          ## Tanzu Build Service (TBS)
+
+exit
 installTanzuDataPostgres     ## Tanzu Data SQL
 installSpringCloudGateway
 installMinio
