testing

diff --git a/deployTKGmc b/deployTKGmc
--- a/deployTKGmc
+++ b/deployTKGmc
@@ -788,19 +788,63 @@ echo "$SSH_COMMAND -n id > /dev/null"
             --priority 1000 \
             --destination-port-range 22 \
             --access allow > /dev/null 2>&1
+        if [ $? -ne 0 ]; then
+          echo "ERROR: Creating Security Group Rule AdminSG-RuleSSH"
+          exit 1
+        fi
 
         az network nsg rule create \
             --resource-group Admin \
             --nsg-name AdminSG \
-            --name AdminSG-RuleSSH \
+            --name AdminSG-RuleLDAP \
             --protocol tcp \
             --priority 1001 \
             --destination-port-range 636 \
             --access allow > /dev/null 2>&1
         if [ $? -ne 0 ]; then
-          echo "ERROR: Creating Security Group Rule AdminSG-RuleSSH"
+          echo "ERROR: Creating Security Group Rule AdminSG-RuleLDAP (tcp/636)"
           exit 1
         fi
+
+        az network nsg rule create \
+            --resource-group Admin \
+            --nsg-name AdminSG \
+            --name AdminSG-RuleLDAP \
+            --protocol udp \
+            --priority 1001 \
+            --destination-port-range 636 \
+            --access allow > /dev/null 2>&1
+        if [ $? -ne 0 ]; then
+          echo "ERROR: Creating Security Group Rule AdminSG-RuleLDAP (udp/636)"
+          exit 1
+        fi
+
+        az network nsg rule create \
+            --resource-group Admin \
+            --nsg-name AdminSG \
+            --name AdminSG-RuleLDAP \
+            --protocol tcp \
+            --priority 1001 \
+            --destination-port-range 389 \
+            --access allow > /dev/null 2>&1
+        if [ $? -ne 0 ]; then
+          echo "ERROR: Creating Security Group Rule AdminSG-RuleLDAP (tcp/389)"
+          exit 1
+        fi
+
+        az network nsg rule create \
+            --resource-group Admin \
+            --nsg-name AdminSG \
+            --name AdminSG-RuleLDAP \
+            --protocol udp \
+            --priority 1001 \
+            --destination-port-range 389 \
+            --access allow > /dev/null 2>&1
+        if [ $? -ne 0 ]; then
+          echo "ERROR: Creating Security Group Rule AdminSG-RuleLDAP (udp/389)"
+          exit 1
+        fi
+
       else
         messagePrint " - Verify Security Group Rule" "AdminSG-RuleSSH"
       fi
