fixed TMC reattach

diff --git a/deployMiniKube b/deployMiniKube
--- a/deployMiniKube
+++ b/deployMiniKube
@@ -224,25 +224,40 @@ installMinio
 
 if [ "$TDH_TANZU_MISSION_CONTROL_REGISTRATION" == "true" ]; then 
   cnt=$(tmc cluster list --name $TDH_MINIKUBE_PROFILE 2>/dev/null | grep -c $TDH_MINIKUBE_PROFILE)
+  if [ $cnt -gt 0 ]; then
+    stt=$(tmc cluster list --name $TDH_MINIKUBE_PROFILE -o json | jq -r '.clusters[].status.conditions."Agent-READY".status')
+    if [ "$stt" != "TRUE" ]; then
+      tmc cluster reattach --name $TDH_MINIKUBE_PROFILE -p attached -m attached > /dev/null 2>&1; ret=$?
+      if [ $ret -ne 0 ]; then
+        MGMT=$(tmc cluster list --name $TDH_MINIKUBE_PROFILE | grep $TDH_MINIKUBE_PROFILE | awk '{ print $2 }')
+        PROV=$(tmc cluster list --name $TDH_MINIKUBE_PROFILE | grep $TDH_MINIKUBE_PROFILE | awk '{ print $3 }')
+
+        tmc cluster delete $TDH_MINIKUBE_PROFILE -p $PROV -m $MGMT -f > /dev/null 2>&1; ret=$?
+        if [ $ret -ne 0 ]; then
+          echo "ERROR: TMC failed to attach cluster"
+          echo "       => tmc cluster delete $TDH_MINIKUBE_PROFILE -p tanzu-demo-hub -m $TDH_TKGMC_NAME"
+          exit 1
+        fi
+
+        # --- WAIT FOR THE CLUSTER TO BE DELETED ---
+        cnt=1
+        while [ $cnt -ne 0 ]; do
+          cnt=$(tmc cluster list --name $TDH_MINIKUBE_PROFILE 2>/dev/null | grep -c $TDH_MINIKUBE_PROFILE)
+          sleep 20
+        done
+
+        cnt=0
+      fi  
+    fi
+  fi
+
   if [ $cnt -eq 0 ]; then
     tmc cluster attach --name $TDH_MINIKUBE_PROFILE --kubeconfig /Users/sdu/.kube/config -p attached -m attached > /dev/null 2>&1; ret=$?
-    if [ $ret -ne 0 ]; then 
-      tmc cluster delete $TDH_MINIKUBE_PROFILE -p attached -m attached > /dev/null 2>&1
-  
-      # --- WAIT FOR THE CLUSTER TO BE DELETED ---
-      cnt=1
-      while [ $cnt -ne 0 ]; do
-        cnt=$(tmc cluster list --name $TDH_MINIKUBE_PROFILE 2>/dev/null | grep -c $TDH_MINIKUBE_PROFILE) 
-        sleep 20
-      done
-  
-      tmc cluster attach --name $TDH_MINIKUBE_PROFILE --kubeconfig /Users/sdu/.kube/config -p attached -m attached > /dev/null 2>&1; ret=$?
-      if [ $ret -ne 0 ]; then 
-        echo "ERROR: TMC failed to attach cluster"
-        echo "       => tmc cluster reattach --name $TDH_MINIKUBE_PROFILE --kubeconfig /Users/sdu/.kube/config -p attached -m attached "
-        exit
-      fi
-    fi 
+    if [ $ret -ne 0 ]; then
+      echo "ERROR: TMC failed to attach cluster"
+      echo "       => tmc cluster reattach --name $TDH_MINIKUBE_PROFILE --kubeconfig /Users/sdu/.kube/config -p attached -m attached "
+      exit
+    fi
   fi
 fi
 
