tesing

diff --git a/deployTKG b/deployTKG
--- a/deployTKG
+++ b/deployTKG
@@ -243,7 +243,14 @@ if [ "${TDH_TKGWC_INGRESS_CONTOUR}" == "true" ]; then
   fi
 
   # --- SET CLUSTER DNS ---
-  setTKGclusterDNS $TDH_TKGWC_NAME
+  ipa=$(kubectl get svc envoy -n tanzu-system-ingress -o json | jq -r '.status.loadBalancer.ingress[].ip')
+  if [ "{$ipa}" != "" ]; then 
+    setTKGclusterDNS "$TDH_TKGWC_NAME" "${ip}"
+  else
+    echo "ERROR: Unable to get LoadBalancer IP-Adress of the Ingress"
+    echo "       => kubectl get svc envoy -n tanzu-system-ingress"
+    exit 1
+  fi
 
 fi
 
diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -881,9 +881,11 @@ createCluster() {
 
 setTKGclusterDNS() {
   TKG_CLUSTER="$1"
+  TKG_IPADRESS="$2"
   DNS_PREFIX="$TDH_TKGMC_ENVNAME"
   DNS_SUFFIX="$AWS_HOSTED_DNS_DOMAIN"
 
+echo "TKG_IPADRESS:$TKG_IPADRESS"
 echo "TDH_TKGWC_NAME:$TDH_TKGWC_NAME"
 echo "TDH_TKGMC_ENVNAME:$TDH_TKGMC_ENVNAME"
 echo "AWS_HOSTED_DNS_DOMAIN:$AWS_HOSTED_DNS_DOMAIN"
@@ -927,7 +929,9 @@ echo "TDH_TKGMC_INFRASTRUCTURE:$TDH_TKGMC_INFRASTRUCTURE"
   if [ "${TDH_TKGMC_INFRASTRUCTURE}" == "Azure" ]; then
     DNS_NAME="*.apps-${TKG_CLUSTER}"
     messagePrint "- Create DNS Entry for:" "*.apps-${TKG_CLUSTER}.${DNS_PREFIX}.${DNS_SUFFIX}"
-echo "DNS_NAME:$DNS_NAME"
+
+
+
   
 echo "az network dns record-set a show -g $DNS_PREFIX -z ${DNS_PREFIX}.${DNS_SUFFIX} -n $DNS_NAME"
     az network dns record-set a show -g $DNS_PREFIX -z ${DNS_PREFIX}.${DNS_SUFFIX} -n $DNS_NAME > /dev/null 2>&1
@@ -959,18 +963,55 @@ echo "IPA:$ipa"
     fi
   fi
 
-
+  if [ "${AWS_HOSTED_ZONE_ID}" != "" -a "${TDH_TKGMC_INFRASTRUCTURE}" == "AWS" ]; then
+    ZONE_ID_STR=$(echo "${ZONE_ID}" | awk -F'/' '{ print $NF }')
+    DNSLB=$(aws elb --region $AWS_REGION describe-load-balancers --load-balancer-names "$AWS_ID" | \
+        jq -r '.LoadBalancerDescriptions[0].DNSName')
+    DNSLB_ZONEID=$(aws elb --region $AWS_REGION describe-load-balancers --load-balancer-names "$AWS_ID" | \
+        jq -r '.LoadBalancerDescriptions[0].CanonicalHostedZoneNameID')
+    ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name ${DNS_PREFIX}.${DNS_SUFFIX} | jq -r '.HostedZones[0].Id')
+  
+    ALIAS=$(aws route53 list-resource-record-sets --hosted-zone-id $ZONE_ID \
+            --query "ResourceRecordSets[?contains(Name, 'apps-${cluster}.${DNS_PREFIX}.${DNS_SUFFIX}')].AliasTarget.DNSName" | \
+            jq -r '.[]' | sed -e 's/dualstack\.//g' -e 's/\.$//g' )
+  
+    if [ "${ALIAS}" != "$DNSLB" ]; then
+      if [ "${ZONE_ID}" != "" ]; then
+        echo "Create DNS Entry for *.apps-${cluster}.${DNS_PREFIX}.${DNS_SUFFIX}:"
+        ZONE="*.${cluster}.${DNS_PREFIX}.${DNS_SUFFIX}"
+        ZONE="*.apps-${cluster}.${DNS_PREFIX}.${DNS_SUFFIX}"
+  
+        TMPROUTE53=/tmp/$$_tmp_route53.json
+        echo "{"                                                   >  $TMPROUTE53
+        echo "  \"Comment\": \"CREATE/DELETE/UPSERT a record \","  >> $TMPROUTE53
+        echo "  \"Changes\": [{"                                   >> $TMPROUTE53
+        echo "  \"Action\": \"UPSERT\","                           >> $TMPROUTE53
+        echo "  \"ResourceRecordSet\": {"                          >> $TMPROUTE53
+        echo "    \"Name\": \"${ZONE}\","                          >> $TMPROUTE53
+        echo "    \"Type\": \"A\","                                >> $TMPROUTE53
+        echo "    \"AliasTarget\": {"                              >> $TMPROUTE53
+        echo "      \"HostedZoneId\": \"${DNSLB_ZONEID}\","        >> $TMPROUTE53
+        echo "      \"DNSName\": \"dualstack.${DNSLB}.\","         >> $TMPROUTE53
+        echo "      \"EvaluateTargetHealth\": true"                >> $TMPROUTE53
+        echo "    }"                                               >> $TMPROUTE53
+        echo "}}]"                                                 >> $TMPROUTE53
+        echo "}"                                                   >> $TMPROUTE53
+  
+        aws route53 change-resource-record-sets --hosted-zone-id $ZONE_ID \
+            --change-batch file://${TMPROUTE53} > /dev/null 2>&1
+        if [ $? -ne 0 ]; then
+          echo "ERROR: failed to set DNS for $hnm"
+          echo "       => aws route53 change-resource-record-sets --hosted-zone-id \"${ZONE_ID}\" \\"
+          echo "              --change-batch file://${TMPROUTE53}"
+          cat $TMPROUTE53
+          exit 1
+        fi
+  
+        rm -f $TMPROUTE53
+      fi
+    fi
+  fi
 }
-
-
-
-
-
-
-
-
-
-
 
 
 
