testing

diff --git a/deployTKG b/deployTKG
--- a/deployTKG
+++ b/deployTKG
@@ -776,12 +776,6 @@ if [ "${TDH_TKGWC_TBS}" == "true" ]; then
   tar xf $TBS_FILE -C /tmp/build-service
 
   kubectl config use-context $TDH_TKGWC_NAME-admin@$TDH_TKGWC_NAME > /dev/null 2>&1
-  # --- TESTING REGISTRY ---
-  docker login $DNS_HARBOR -u admin -p $HARBOR_PASS > /dev/null 2>&1
-  if [ $? -ne 0 ]; then
-    echo "ERROR: Docker login does not work"
-    echo "       => docker login $DNS_HARBOR -u admin -p $HARBOR_PASS"; exit
-  fi
 
   if [ "$PCF_REGISTRY_NAME" == "" -o "$PCF_REGISTRA_USER" == "" -o "$PCF_REGISTRA_PASS" == "" ]; then
     if [ "$PCF_REGISTRY_NAME" == "" ]; then 
@@ -794,6 +788,13 @@ if [ "${TDH_TKGWC_TBS}" == "true" ]; then
 
     if [ "$PCF_REGISTRA_PASS" == "" ]; then 
       echo "ERROR: Variable PCF_REGISTRA_PASS has not been set in ~/.tanzu-demo-hub.cfg"; exit
+    fi
+  else
+    # --- TESTING REGISTRY ---
+    docker login $PCF_REGISTRY_NAME -u $PCF_REGISTRA_USER -p $PCF_REGISTRA_PASS > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+      echo "ERROR: Docker login does not work"
+      echo "       => docker login $PCF_REGISTRY_NAME -u $PCF_REGISTRA_USER -p $PCF_REGISTRA_PASS"; exit
     fi
   fi
 
