improve Azure Management cluster installation

diff --git a/deployTCEmc b/deployTCEmc
--- a/deployTCEmc
+++ b/deployTCEmc
@@ -1249,37 +1249,34 @@ fi
 
     ret=1; cnt=0
     while [ $ret -ne 0 -a $cnt -lt 5 ]; do
-      tmc managementcluster register $TDH_TKGMC_NAME -c tanzu-demo-hub -p TKG -o /tmp/k8s-register-manifest.yaml >/dev/null 2>&1; ret=$?
-      [ $ret -eq 0 ] && break
+      tmc managementcluster register $TDH_TKGMC_NAME -c tanzu-demo-hub -p TKG --kubeconfig=$HOME/.kube/config > /tmp/error.log 2>&1; ret=$?
+      if [ $ret -eq 0 ]; then
+        tmc managementcluster get $TDH_TKGMC_NAME > /dev/null 2>&1; ret=$?
+        if [ $ret -eq 0 ]; then break; else ret=1; fi
+      fi
       sleep 30
       let cnt=cnt+1
     done
 
-    if [ $? -ne 0 ]; then
-      echo "ERROR: failed to register TCE Management Cluster: $TDH_TKGMC_NAME to TMC"
-      echo "       => tmc managementcluster register $TDH_TKGMC_NAME -c tanzu-demo-hub -p TKG"
-      exit
-    fi
-
-    messagePrint " ▪ Install TMC Agent in Namespace"             "vmware-system-tmc"
-    if [ $DEBUG -gt 0 ]; then
-      echo "--------------------------------------------------------------------------------------------------------------"
-      kubectl apply -f /tmp/k8s-register-manifest.yaml; ret=$?
-      echo "--------------------------------------------------------------------------------------------------------------"
-    else
-      kubectl apply -f /tmp/k8s-register-manifest.yaml > /dev/null 2>&1; ret=$?
-    fi
-
     if [ $ret -ne 0 ]; then
-      echo "ERROR: failed to install TMC Agent"
-      echo "       => kubectl apply -f /tmp/k8s-register-manifest.yaml"
+      logMessages /tmp/error.log
+      echo "ERROR: failed to register TKG Management Cluster: $TDH_TKGMC_NAME to TMC"
+      if [ "$NATIVE" == "0" ]; then
+        echo "       => tools/${TDH_TOOLS}.sh"
+        echo "          tdh-tools:/$ tmc managementcluster register $TDH_TKGMC_NAME -c tanzu-demo-hub -p TKG -k $HOME/.kube/config"
+        echo "          tdh-tools:/$ exit"
+      else
+        echo "       => tmc managementcluster register $TDH_TKGMC_NAME -c tanzu-demo-hub -p TKG -k $HOME/.kube/config"
+      fi
+
+      exit 1
     fi
 
     cnt=0; stt="PENDING"
     while [ "$stt" != "READY" -a $cnt -lt 10 ]; do
-      stt=$(tmc managementcluster get $TDH_TKGMC_NAME -o json | jq -r '.status.phase') 
+      stt=$(tmc managementcluster get $TDH_TKGMC_NAME -o json | jq -r '.status.phase')
       sleep 60
- 
+
       let cnt=cnt+1
     done
   fi
