changed ssh-key name from vmware-cloud-tmd to tanzu-demo-hub

diff --git a/deployTMC b/deployTMC
--- a/deployTMC
+++ b/deployTMC
@@ -57,10 +57,10 @@ listDeployments() {
 }
 
 createCluster_deleteme() {
-  SSH_KEY_NAME=vmware-cloud-tmc
+  SSH_KEY_NAME=tanzu-demo-hub
   SSH_KEY_FILE=~/.tanzu-demo-hub/KeyPair-${SSH_KEY_NAME}-${AWS_REGION}.pem
 
-  #tmc cluster create -c sadubois-aws -g sadubois --name sadubois-demo -r eu-central-1 -s vmware-cloud-tmc 
+  #tmc cluster create -c sadubois-aws -g sadubois --name sadubois-demo -r eu-central-1 -s tanzu-demo-hub
   #tmc cluster create -t aws-ha -c my-credential -s my-ssh-key" #template
 
   #stt=$(tmc cluster list --group $TMC_CLUSTER_GROUP --name $TMC_CLUSTER_NAME --output json | \
@@ -98,7 +98,7 @@ createCluster_deleteme() {
 
   messagePrint " - Cluster Status"           "$stt"
 
-  #tmc cluster create -c sadubois-aws -g sadubois --name sadubois-demo -s vmware-cloud-tmc -t default
+  #tmc cluster create -c sadubois-aws -g sadubois --name sadubois-demo -s tanzu-demo-hub -t default
   #tmc cluster list --group sadubois --name sadubois-demo --output json
   #tmc cluster list --name sadubois-demo --output json | jq -r '.clusters[].status.status'
 }
@@ -165,23 +165,26 @@ if [ "${DEPLOY_TKG_TEMPLATE}" == "" ]; then
 fi
 
 # --- VERIFY DEPLOYMENT ---
-if [ ! -f ${TDHPATH}/deployments/${DEPLOY_TKG_TEMPLATE} ]; then
-  echo "ERROR: Deployment file $pcf_deployment can not be found in ${TDHPATH}/deployments"
-  exit 1
+if [ -f ${TDHPATH}/deployments/${DEPLOY_TKG_TEMPLATE} -o ${HOME}/.tanzu-demo-hub/config/${DEPLOY_TKG_TEMPLATE} ]; then
+  if [ -f ${TDHPATH}/deployments/${DEPLOY_TKG_TEMPLATE} ]; then 
+    TDH_DEPLOYMENT_CONFIG=${TDHPATH}/deployments/${DEPLOY_TKG_TEMPLATE}
+  else
+    TDH_DEPLOYMENT_CONFIG=${HOME}/.tanzu-demo-hub/config/${DEPLOY_TKG_TEMPLATE}
+  fi
 else
-  . ${TDHPATH}/deployments/${DEPLOY_TKG_TEMPLATE}
-
-  export TMC_CLUSTER_GROUP=$TDH_DEPLOYMENT_CLUSTERGROUP
+  echo "ERROR: Deployment file $pcf_deployment can not be found in the directory:"
+  echo "       ${TDHPATH}/deployments or ${HOME}/.tanzu-demo-hub/config"
+  exit 1
 fi
 
-
-cnt=$(egrep -c "^TDH_DEPLOYMENT_CLOUD=" ${TDHPATH}/deployments/$DEPLOY_TKG_TEMPLATE)
+cnt=$(egrep -c "^TDH_DEPLOYMENT_CLOUD=" ${TDH_DEPLOYMENT_CONFIG})
 if [ $cnt -eq 0 ]; then
-  echo "ERROR: ${TDHPATH}/deployments/$DEPLOY_TKG_TEMPLATE is not a correct TANZU-DEMO-HUB deployment configuration file"
+  echo "ERROR: ${TDH_DEPLOYMENT_CONFIG} is not a correct TANZU-DEMO-HUB deployment configuration file"
   exit 1
 else
   missing_variables=0
-  .  ${TDHPATH}/deployments/${DEPLOY_TKG_TEMPLATE}
+
+  .  ${TDH_DEPLOYMENT_CONFIG}
   export TMC_CLUSTER_GROUP=$TDH_DEPLOYMENT_CLUSTERGROUP
 
   # --- CHECK ENVIRONMENT VARIABLES ---
