testing

diff --git a/deployTKG b/deployTKG
--- a/deployTKG
+++ b/deployTKG
@@ -149,17 +149,27 @@ tkg get clusters
 echo "-----------------------------------------------------------------------------------------------------------"
 
 if [ "${TDH_TKGWC_INGRESS_CONTOUR}" == "true" ]; then 
-  messagePrint " - Install Ingress Contour"  "$TDH_TKGWC_INGRESS_CONTOUR" 
 
-  cd extensions/$TDH_TKGWC_EXTENSIONS/extensions
-  # --- INSTALL TMC EXTENSION MANAGER ---
-  kubectl apply -f tmc-extension-manager.yaml >/dev/null 2>&1
-  if [ $? -ne 0 ]; then 
-    echo "ERROR: Installation of TMC Extension manager failed"
-    echo "       => cd $TDHPATH/extensions/$TDH_TKGWC_EXTENSIONS"
-    echo "       => kubectl apply -f tmc-extension-manager.yaml"
-    exit
+  stt=$(kubectl get ns -o json | jq -r '.items[] | select(.metadata.name == "vmware-system-tmc").status.phase')
+  if [ "${stt}" == "" ]; then
+    messageTitle "Install Ingress Contour"  
+    echo "-----------------------------------------------------------------------------------------------------------"
+    cd extensions/$TDH_TKGWC_EXTENSIONS/extensions
+    # --- INSTALL TMC EXTENSION MANAGER ---
+    kubectl apply -f tmc-extension-manager.yaml >/dev/null 2>&1
+    if [ $? -ne 0 ]; then 
+      echo "ERROR: Installation of TMC Extension manager failed"
+      echo "       => cd $TDHPATH/extensions/$TDH_TKGWC_EXTENSIONS"
+      echo "       => kubectl apply -f tmc-extension-manager.yaml"
+      exit
+    fi
+    echo "-----------------------------------------------------------------------------------------------------------"
   fi
+
+  messageTitle "Verify Ingress Contour"  
+  echo "-----------------------------------------------------------------------------------------------------------"
+  kubectl get all -n vmware-system-tmc
+  echo "-----------------------------------------------------------------------------------------------------------"
   
 #  kubectl get ns -o json | jq -r '.items[].metadata | select(.name == "tkg-system").uid'
 
