testing

diff --git a/deployTKG b/deployTKG
--- a/deployTKG
+++ b/deployTKG
@@ -428,13 +428,11 @@ if [ "${TDH_TKGWC_INGRESS_HARBOR}" == "true" ]; then
   messagePrint "- Create Harbor service configuration" ""
   sudo snap install yq > /dev/null 2>&1
 
-echo pppp1
   DNS_HARBOR="harbor.apps-${TDH_TKGWC_NAME}.${TDH_TKGMC_ENVNAME}.${AWS_HOSTED_DNS_DOMAIN}"
   DNS_NOTARY="notary.apps-${TDH_TKGWC_NAME}.${TDH_TKGMC_ENVNAME}.${AWS_HOSTED_DNS_DOMAIN}"
   HARBOR_VALUES=/tmp/harbor-data-values.yaml
   HARBOR_PASS=Password12345
 
-echo pppp2
   kubectl -n $HARBOR_NAMESPACE get secret harbor-certs > /dev/null 2>&1
   if [ $? -ne 0 ]; then
     kubectl -n $HARBOR_NAMESPACE create secret tls harbor-certs --cert=$TLS_CERTIFICATE  --key=$TLS_PRIVATE_KEY
@@ -467,13 +465,11 @@ echo pppp2
   echo "  tls:"                                                                      >> $HARBOR_VALUES
   echo "    existingSecret: harbor-certs"                                            >> $HARBOR_VALUES
 
-echo pppp3
 if [ 1 -eq 1 ]; then 
   cnt=$(helm ls -n tanzu-system-registry | egrep -c "^harbor")
   if [ $cnt -eq 0 ]; then
     helm install harbor bitnami/harbor -f $HARBOR_VALUES -n $HARBOR_NAMESPACE --version 9.2.2
   fi
-echo pppp4
 
   # --- TESTING REGISTRY ---
   docker login $DNS_HARBOR -u admin -p $HARBOR_PASS > /dev/null 2>&1
@@ -481,7 +477,6 @@ echo pppp4
     echo "ERROR: Docker login does not work"
     echo "       => docker login $DNS_HARBOR -u admin -p $HARBOR_PASS"; exit
   fi
-echo pppp5
 
 else
   cnt=$(kubectl get secrets harbor-data-values -n $HARBOR_NAMESPACE 2>/dev/null | grep -c "harbor-data-values")
@@ -539,7 +534,6 @@ else
 fi
 #hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
 fi
-echo ppppp10
 
 if [ "${TDH_TKGWC_INGRESS_HARBOR}" == "true1" ]; then
   # https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.2/vmware-tanzu-kubernetes-grid-12/GUID-extensions-harbor-registry.html"
@@ -769,8 +763,6 @@ echo gaga10
     setDNSrecord "$pip" "${TDH_TKGMC_ENVNAME}" "${AWS_HOSTED_DNS_DOMAIN}" "harbor"
     setDNSrecord "$pip" "${TDH_TKGMC_ENVNAME}" "${AWS_HOSTED_DNS_DOMAIN}" "notary.harbor"
 fi
-echo ppppp20
-echo "TDH_TKGWC_TBS:$TDH_TKGWC_TBS"
 
 if [ "${TDH_TKGWC_TBS}" == "true" ]; then
   if [ ! -x /usr/local/bin/kp ]; then
@@ -781,8 +773,32 @@ if [ "${TDH_TKGWC_TBS}" == "true" ]; then
   TBS_FILE=$(ls -1tr $TDHPATH/software/build-service-*.tar | tail -1)
   [ -d /tmp/build-service ] && rm -rf /tmp/build-service 
   mkdir /tmp/build-service
-echo "tar xf $TBS_FILE -C /tmp/build-service"
   tar xf $TBS_FILE -C /tmp/build-service
+
+  kubectl config use-context $TDH_TKGWC_NAME-admin@$TDH_TKGWC_NAME > /dev/null 2>&1
+  # --- TESTING REGISTRY ---
+  docker login $DNS_HARBOR -u admin -p $HARBOR_PASS > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    echo "ERROR: Docker login does not work"
+    echo "       => docker login $DNS_HARBOR -u admin -p $HARBOR_PASS"; exit
+  fi
+
+  if [ "$PCF_REGISTRY_NAME" == "" -o "$PCF_REGISTRA_USER" == "" -o "$PCF_REGISTRA_PASS" == "" ]; then
+    if [ "$PCF_REGISTRY_NAME" == "" ]; then 
+      echo "ERROR: Variable PCF_REGISTRY_NAME has not been set in ~/.tanzu-demo-hub.cfg"; exit
+    fi
+
+    if [ "$PCF_REGISTRA_USER" == "" ]; then 
+      echo "ERROR: Variable PCF_REGISTRY_USER has not been set in ~/.tanzu-demo-hub.cfg"; exit
+    fi
+
+    if [ "$PCF_REGISTRA_PASS" == "" ]; then 
+      echo "ERROR: Variable PCF_REGISTRA_PASS has not been set in ~/.tanzu-demo-hub.cfg"; exit
+    fi
+  fi
+
+
+
 fi
 
 exit
