fix for issue #a:5 Kubeconfig file for TCE Management Cluster not created

diff --git a/deployTCEmc b/deployTCEmc
--- a/deployTCEmc
+++ b/deployTCEmc
@@ -238,85 +238,6 @@ checkKeyPairs() {
   fi
 }
 
-configureLetsEnscript() {
-  ##############################################################################################
-  ################################ GENERATING TLS CERTIFICATES #################################
-  ##############################################################################################
-
-  CERTS_GENERATE_NEW=false
-  domain="${TDH_TKGMC_ENVNAME}.${AWS_HOSTED_DNS_DOMAIN}"
-
-  if [ -d $HOME/.tanzu-demo-hub/certificates/$domain -a -f $HOME/.tanzu-demo-hub/certificates/$domain/privkey.pem ]; then
-    messageTitle "Install Certificate for domain ($domain)"
-    $SSH_COMMAND -n "mkdir -p $SSH_HOME/tanzu-demo-hub/certificates"
-    $SCP_COMMAND $HOME/.tanzu-demo-hub/certificates/$domain/* ${SSH_USER}@${SSH_HOST}:~/tanzu-demo-hub/certificates > /dev/null 2>&1
-  fi
-
-  CERTS_INSTALLED=$($SSH_COMMAND -n "[ -f ~/tanzu-demo-hub/certificates/privkey.pem ] && echo true || echo false")
-
-  if [ "${CERTS_INSTALLED}" == "true" ]; then
-    messageTitle "Validate Certificates for domain ($domain)"
-    $SCP_COMMAND $HOME/.tanzu-demo-hub/certificates/$domain/* ${SSH_USER}@${SSH_HOST}:~/tanzu-demo-hub/certificates > /dev/null 2>&1
-
-    CERTS_ENDDATE=$($SSH_COMMAND -n "openssl x509 -noout -in ~/tanzu-demo-hub/certificates/cert.pem -enddate | awk -F'=' '{ print \$2 }'")
-    CERTS_EXPIRED=$($SSH_COMMAND -n "openssl x509 -noout -in ~/tanzu-demo-hub/certificates/cert.pem -checkend 3600 > /dev/null 2>&1; echo \$?")
-
-    if [ $CERTS_EXPIRED -eq 0 ]; then
-      messagePrint " ▪ Certificate Expiratation Data:" "$CERTS_ENDDATE"
-    else
-      messagePrint " ▪ Certificate Expiratation Data:" "$CERTS_ENDDATE [>>> *EXPIRED* <<<]"
-      CERTS_GENERATE_NEW=true
-    fi
-  else
-    CERTS_GENERATE_NEW=true
-  fi
-
-  if [ "${CERTS_GENERATE_NEW}" == "true" ]; then
-    messageTitle "Generate Certificates for domain ($domain)"
-    route53createHostedZone $domain
-
-    echo "-------------------------------------- GENERATE LET'S-ENCRYPT CERTIFICATES -------------------------------------"
-    typ=$(echo $domain | egrep -c "aztkg|awstkg|gcptkg|vstkg")
-    if [ $typ -ne 0 ]; then
-      messageTitle "Generate Certificate for TCE Domains ($domain)"
-      $SSH_COMMAND -n "sudo certbot certonly --dns-route53 -d '*.$domain' -m sadubois@pivotal.io --agree-tos -n --expand"
-      if [ $? -ne 0 ]; then
-        echo "ERROR: failed to generate certificate. There are probably to many cert requests happends and a limit reached"
-        echo "       Try it again after some hours or search *.$domain in https://crt.sh/"
-        exit 1
-      fi
-    fi
-
-    # --- GET A COPY OF THE CERTIFICATES BACK ---
-    [ ! -d $HOME/.tanzu-demo-hub/certificates/$domain ] && mkdir -p $HOME/.tanzu-demo-hub/certificates/$domain
-
-    $SSH_COMMAND -n "[ -d /etc/letsencrypt/live ] && sudo chmod -R a+r /etc/letsencrypt/live /etc/letsencrypt/archive"
-    $SSH_COMMAND -n "[ -d /etc/letsencrypt/live ] && sudo chmod 777 /etc/letsencrypt/live /etc/letsencrypt/live/$domain"
-    $SSH_COMMAND -n "[ -d /etc/letsencrypt/archive ] && sudo chmod 777 /etc/letsencrypt/archive /etc/letsencrypt/archive/$domain"
-    $SSH_COMMAND -n "[ ! -d $SSH_HOME/tanzu-demo-hub/certificates/$domain ] && mkdir -p $SSH_HOME/tanzu-demo-hub/certificates"
-    $SSH_COMMAND -n "[ -d /etc/letsencrypt/live/$domain ] && cp /etc/letsencrypt/live/$domain/* ~/tanzu-demo-hub/certificates"
-
-    messageTitle " Copy new certificates from jump to local ./certificates/$domain"
-    cnt=0; ret=1
-    while [ ! -f ./certificates/$domain/fullchain.pem ]; do
-      $SCP_COMMAND ${SSH_USER}@${SSH_HOST}:$SSH_HOME/tanzu-demo-hub/certificates/* $HOME/.tanzu-demo-hub/certificates/$domain/ > /dev/null 2>&1; ret=$?
-      [ $cnt -gt 5 ] && break
-
-      sleep 10
-      let cnt=cnt+1
-    done
-
-    if [ $ret -ne 0 ]; then 
-      $SCP_COMMAND ${SSH_USER}@${SSH_HOST}:$SSH_HOME/tanzu-demo-hub/certificates/* $HOME/.tanzu-demo-hub/certificates/$domain/ 
-      echo "ERROR: failed to copy SSL/TLS cert from jumphost"
-      echo "       => SCP_COMMAND ${SSH_USER}@${SSH_HOST}:$SSH_HOME/tanzu-demo-hub/certificates/* $HOME/.tanzu-demo-hub/certificates/$domain/ "
-      exit
-    fi
-
-    echo "----------------------------------------------------------------------------------------------------------------"
-  fi
-}
-
 # --- VERYFY ACCESS TO CLOUD ---
 checkTDHenvironment
 
@@ -355,7 +276,6 @@ TDH_TKGMC_NAME=${TDH_TKGMC_NAME}-${TDH_USER}
 
 if [ "${TDH_DEPLOYMENT_ENV_NAME}" == "docker" ]; then
   TKG_KUBECONFIG=${HOME}/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.kubeconfig; rm -f $TKG_KUBECONFIG
-echo "TKG_KUBECONFIG:$TKG_KUBECONFIG"
 
   #########################################################################################################################
   ############################## TANZU COMMNUNITY EDITION MANAGEMENT CLUSTER ON DOCKER ####################################
@@ -363,7 +283,6 @@ echo "TKG_KUBECONFIG:$TKG_KUBECONFIG"
 
   cnt=$(tanzu management-cluster get 2>/dev/null | grep -c " $TDH_TKGMC_NAME ")
   if [ $cnt -eq 0 ]; then
-
     # --- CLEANUP KUNECONFIG ---
     cleanupEnvironment
     cleanManagementCluster
@@ -378,6 +297,23 @@ echo "TKG_KUBECONFIG:$TKG_KUBECONFIG"
     tanzu management-cluster kubeconfig get --admin > /dev/null 2>&1
     kubectl config set-cluster $TDH_TKGMC_NAME > /dev/null 2>&1
     kubectl config use-context ${TDH_TKGMC_NAME}-admin@$TDH_TKGMC_NAME > /dev/null 2>&1
+  fi
+
+echo gaga1
+  if [ ! -f TKG_KUBECONFIG ]; then 
+echo gaga2
+    tanzu management-cluster kubeconfig get --admin --export-file=${TKG_KUBECONFIG} > /dev/null 2>&1; ret=$?
+    if [ ${ret} -ne 0 ]; then
+      echo "ERROR: failed to export kubeconfig"
+      if [ "$NATIVE" == "0" ]; then
+        echo "       => tools/${TDH_TOOLS}.sh"
+        echo "          tdh-tools:/$ tanzu management-cluster kubeconfig get --admin --export-file=${TKG_KUBECONFIG}"
+        echo "          tdh-tools:/$ exit"
+      else
+        echo "       => tanzu management-cluster kubeconfig get --admin --export-file=${TKG_KUBECONFIG}"
+      fi
+      exit 1
+    fi
   fi
 
 # TMC Registation does not yet work with TCE
