changed Azure ApplicationId generation

diff --git a/deployTKGmc b/deployTKGmc
--- a/deployTKGmc
+++ b/deployTKGmc
@@ -796,43 +796,81 @@ createJumpHost() {
     fi
 
     # --- VERIFY / CREATE APPLICATION ID AND SERVICE PRINCIPLE ---
-    appid=$(az ad app list --display-name "TanzuDemoHub" | jq -r '.[].appId')
+    appid=$(az ad app list --display-name "TanzuDemoHub-$TDH_USER" | jq -r '.[].appId')
     if [ "$appid" == "" ]; then 
-      messageTitle "Register Azure Application (TanzuDemoHub)"
-      messagePrint " ▪ Register Azure ApplicationID" "TanzuDemoHub"
-      az ad app create --display-name TanzuDemoHub --key-type Password --password tanzu-demo-hub > /dev/null 2>&1
-      if [ $? -ne 0 ]; then 
-        echo "ERROR: failed to register app (TanzuDemoHub)"
-        echo "       => az ad app create --display-name TanzuDemoHub --key-type Password --password tanzu-demo-hub"
-        exit
-      fi
-     
-      messagePrint " ▪ Create ServicePrincipal for Application" "TanzuDemoHub"
-      appid=$(az ad app list --display-name "TanzuDemoHub" | jq -r '.[].appId')
-      az ad sp create --id $appid > /dev/null 2>&1
-      if [ $? -ne 0 ]; then 
-        echo "ERROR: failed to create ServicePrinicipal for app (TanzuDemoHub)"
-        echo "       => az ad sp create --id $appid"
-        exit
-      fi
+      messageTitle "Register Azure Application (TanzuDemoHub-$TDH_USER)"
+# => not needed anymore: az ad sp create-for-rbac --name "TanzuDemoHub-$TDH_USER)" does it all
+#      messagePrint " ▪ Register Azure ApplicationID" "TanzuDemoHub-$TDH_USER"
+#      #az ad app create --display-name TanzuDemoHub-$TDH_USER --key-type Password --password tanzu-demo-hub > /dev/null 2>&1
+#      az ad app create --display-name TanzuDemoHub-$TDH_USER --key-type Password --password tanzu-demo-hub 
+#      if [ $? -ne 0 ]; then 
+#        echo "ERROR: failed to register app (TanzuDemoHub-$TDH_USER)"
+#        echo "       => az ad app create --display-name TanzuDemoHub-$TDH_USER --key-type Password --password tanzu-demo-hub"
+#        exit
+#      fi
+#     
+#      messagePrint " ▪ Create ServicePrincipal for Application" "TanzuDemoHub-$TDH_USER"
+#      appid=$(az ad app list --display-name "TanzuDemoHub-$TDH_USER" | jq -r '.[].appId')
+#      az ad sp create --id $appid > /dev/null 2>&1
+#      if [ $? -ne 0 ]; then 
+#        echo "ERROR: failed to create ServicePrinicipal for app (TanzuDemoHub-$TDH_USER)"
+#        echo "       => az ad sp create --id $appid"
+#        exit
+#      fi
+#
+#      messagePrint " ▪ Create RoleBinding for Application (TanzuDemoHub-$TDH_USER)" "Owner"
+#      objid=$(az ad sp list --all --display-name TanzuDemoHub-$TDH_USER | jq -r '.[].objectId')
+#      #az role assignment create --subscription $AZURE_SUBSCRIPTION_ID --role owner \
+#      #    --assignee-principal-type ServicePrincipal --assignee-object-id $objid > /dev/null 2>&1
+#      az role assignment create --subscription $AZURE_SUBSCRIPTION_ID --role owner \
+#          --assignee-principal-type ServicePrincipal --assignee-object-id $objid 
+#      if [ $? -ne 0 ]; then
+#        echo "ERROR: failed to create RoleBinding for app (TanzuDemoHub-$TDH_USER)"
+#        echo "       => az role assignment create --subscription $AZURE_SUBSCRIPTION_ID --role owner \\"
+#        echo "          --assignee-principal-type ServicePrincipal --assignee-object-id $objid"
+#        exit
+#      fi
+#
+#docker run --rm --name azure-cli bitnami/azure-cli:latest login --service-principal --username $appid --password tanzu-demo-hub --tenant $AZURE_TENANT_ID > /dev/null 2>&1
 
-      messagePrint " ▪ Create RoleBinding for Application (TanzuDemoHub)" "Owner"
-      objid=$(az ad sp list --all --display-name TanzuDemoHub | jq -r '.[].objectId')
-      az role assignment create --subscription $AZURE_SUBSCRIPTION_ID --role owner \
-          --assignee-principal-type ServicePrincipal --assignee-object-id $objid > /dev/null 2>&1
-      if [ $? -ne 0 ]; then
-        echo "ERROR: failed to create RoleBinding for app (TanzuDemoHub)"
-        echo "       => az role assignment create --subscription $AZURE_SUBSCRIPTION_ID --role owner \\"
-        echo "          --assignee-principal-type ServicePrincipal --assignee-object-id $objid"
-        exit
+      AZURE_CLIENT_ID=$appid
+      AZURE_CLIENT_SECRET=$(az ad sp create-for-rbac --name "TanzuDemoHub-$TDH_USER)" 2>/dev/null | jq -r '.password')
+
+      echo "INFO: Please set the new generated Azure Client Secret for the Azure ClientID (TanzuDemoHub-$TDH_USER)"
+      echo "      into your ~/.tanzu-demo-hub.cfg and restart $0"
+      echo "      => export AZURE_CLIENT_SECRET=\"$AZURE_CLIENT_SECRET\""
+      echo " "
+      exit 0
+    else
+      if [ "$AZURE_CLIENT_SECRET" == "" ]; then 
+        AZURE_CLIENT_ID=$appid
+        AZURE_CLIENT_SECRET=$(az ad sp create-for-rbac --name "TanzuDemoHub-$TDH_USER)" 2>/dev/null | jq -r '.password') 
+        echo "INFO: Please set the new generated Azure Client Secret for the Azure ClientID (TanzuDemoHub-$TDH_USER)"
+        echo "      into your ~/.tanzu-demo-hub.cfg and restart $0"
+        echo "      => export AZURE_CLIENT_SECRET=\"$AZURE_CLIENT_SECRET\""
+        echo " "
+        exit 0
+      else
+        docker run --rm --name azure-cli bitnami/azure-cli:latest login --service-principal --username $appid --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID > /dev/null 2>&1
+        if [ $? -ne 0 ]; then 
+          AZURE_CLIENT_ID=$appid
+          AZURE_CLIENT_SECRET=$(az ad sp create-for-rbac --name "TanzuDemoHub-$TDH_USER)" 2>/dev/null | jq -r '.password')
+          echo "INFO: The configured Azure Client Secret seams to be wrong or outdated, please set"
+          echo "      the new generated Azure Client Secret for the Azure ClientID (TanzuDemoHub-$TDH_USER)"
+          echo "      into your ~/.tanzu-demo-hub.cfg and restart $0"
+          echo "      => export AZURE_CLIENT_SECRET=\"$AZURE_CLIENT_SECRET\""
+          echo " "
+          exit 0
+        fi
       fi
     fi
 
-    appid=$(az ad app list --display-name "TanzuDemoHub" | jq -r '.[].appId')
-    objid=$(az ad sp list --all --display-name TanzuDemoHub | jq -r '.[].objectId')
-    messageTitle "Verify Azure Application (TanzuDemoHub)"
-    messagePrint " ▪ Application ID" "$appid"
-    messagePrint " ▪ Application Display Name" "TanzuDemoHub"
+    appid=$(az ad app list --display-name "TanzuDemoHub-$TDH_USER" | jq -r '.[].appId')
+    objid=$(az ad sp list --all --display-name TanzuDemoHub-$TDH_USER | jq -r '.[].objectId')
+    messageTitle "Verify Azure Application (TanzuDemoHub-$TDH_USER)"
+    messagePrint " ▪ Azure Client ID" "$appid"
+    messagePrint " ▪ Azure Client Secret" "verified"
+    messagePrint " ▪ Application Display Name" "TanzuDemoHub-$TDH_USER"
     messagePrint " ▪ ServicePrincipal" "$objid"
     messagePrint " ▪ Role Binding" "Owner"
 
diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -99,6 +99,74 @@ loopCmd() {
   echo ""
 }
 
+oktaVerifyAccount() {
+  # [ "${TDH_TKGMC_IDENTITY_MANAGEMENT_TYPE}" == "none" ] && return
+  
+  if [ "${TDH_OKTA_DOMAIN}" == "" -o "${TDH_OKTA_API_TOKEN}" == "" ]; then
+    missing_variables=1
+    echo ""
+    echo "  MISSING ENVIRONMENT-VARIABES    DESCRIPTION        "
+    echo "  -------------------------------------------------------------------------------------------------------------------------------------------------------"
+
+    if [ "${TDH_OKTA_DOMAIN}" == "" ]; then
+      echo "  TDH_OKTA_DOMAIN                  (required) OKTA Domain URL"
+    fi
+
+    if [ "${TDH_OKTA_API_TOKEN}" == "" ]; then
+      echo "  TDH_OKTA_API_TOKEN               (required) OKTA API Token"
+    fi
+  else
+    if [ "$TDH_INFO" == "true" ]; then
+      echo "LDAP Identitiy Management (IdM)"
+      messagePrint " ▪ OKTA Domain "                       "$TDH_OKTA_DOMAIN"
+      messagePrint " ▪ OKTA URL"                           "https://${TDH_OKTA_DOMAIN}"
+      messagePrint " ▪ OKTA Admin URL"                     "https://${TDH_OKTA_DOMAIN}-admin"
+      messagePrint " ▪ OKTA API Token"                     "$TDH_OKTA_API_TOKEN"
+    fi
+  fi
+
+  # --- VERIFY OKTA DOMAIN ---
+  issuer=$(curl ${TDH_OKTA_ADMIN_URL}/.well-known/openid-configuration 2>/dev/null | jq -r '.issuer' 2>/dev/null)
+  if [ "$issuer" != "https://${TDH_OKTA_DOMAIN}.okta.com" ]; then 
+    echo "ERROR: $TDH_OKTA_ADMIN_URL is not a valiad OKta Domain. Please verify or create a new one"
+    exit 1
+  fi
+
+  oktaAPI verify
+}
+
+oktaVerifyApp() {
+  # [ "${TDH_TKGMC_IDENTITY_MANAGEMENT_TYPE}" == "none" ] && return
+
+  if [ "${TDH_OKTA_SECRET_ID}" == "" -o "${TDH_OKTA_USERNAME_CLAIM}" == "" -o "${TDH_OKTA_CLIENT_SECRET}" == "" -o \
+       "${TDH_OKTA_URL}" == "" -o "${TDH_OKTA_SCOPES}" == "" -o "${TDH_OKTA_GROUP_CLAIM}" == "" ]; then
+
+    missing_variables=1
+    echo ""
+    echo "  MISSING ENVIRONMENT-VARIABES    DESCRIPTION        "
+    echo "  -------------------------------------------------------------------------------------------------------------------------------------------------------"
+
+    if [ "${TDH_OKTA_SECRET_ID}" == "" ]; then
+      echo "  TDH_OKTA_SECRET_ID               (required) OKTA SecretId"
+    fi
+
+    if [ "${TDH_OKTA_CLIENT_SECRET}" == "" ]; then
+      echo "  TDH_OKTA_CLIENT_SECRET           (required) OKTA Client Secret"
+    fi
+  else
+    echo "LDAP Identitiy Management (IdM)"
+    messagePrint " ▪ LDAP Domain"                        "$LDAP_DOMAIN"
+    messagePrint " ▪ LDAP User Serach Name"              "userPrincipalName"
+    messagePrint " ▪ LDAP Host"                          "jump.${TDH_TKGMC_ENVNAME}.${AWS_HOSTED_DNS_DOMAIN}"
+    messagePrint " ▪ LDAP Group Search Name Attribute"   "cn"
+    messagePrint " ▪ LDAP Group Search User Attribute"   "DN"
+    messagePrint " ▪ LDAP Search Username"               "userPrincipalName"
+  fi
+
+  curl https://dev-15903420.okta.com/.well-known/openid-configuration | jq
+}
+
+
 
 checkIdentityProvider() {
   [ "${TDH_TKGMC_IDENTITY_MANAGEMENT_TYPE}" == "none" ] && return
@@ -7432,4 +7500,80 @@ leftText() {
   printf "$str\n" $TEXT
 }
 
+oktaAPIdata() {
+  curl --location --request $1 "$2" \
+    --header 'Accept: application/json' \
+    --header 'Content-Type: application/json' \
+    --header "Authorization: SSWS $TDH_OKTA_API_TOKEN" \
+    --data "@$3" 2>/dev/null 
+}
+
+
+oktaAPI() {
+  MODE=$1
+
+echo "TDH_OKTA_API_TOKEN:$TDH_OKTA_API_TOKEN"
+
+  if [ "$MODE" == "app_delete" ]; then 
+    #curl --location -g --request DELETE 'https://dev-15903420.okta.com/api/v1/apps/{{appId}}?appId=0oa3xr89toegQVBJ7696' \
+    curl --location -g --request DELETE "https://dev-15903420.okta.com/api/v1/apps/$2" \
+    --header 'Accept: application/json' \
+    --header "Authorization: SSWS $TDH_OKTA_API_TOKEN" 
+  fi
+
+  # --- TEST LOGIN ---
+  if [ "$MODE" == "login" -o "$MODE" == "verify" ]; then 
+    err=$(curl --location --request GET "https://${TDH_OKTA_DOMAIN}.okta.com/api/v1/users?limit=25" \
+      --header 'Accept: application/json' \
+      --header 'Content-Type: application/json' \
+      --header "Authorization: SSWS $TDH_OKTA_API_TOKEN" 2>/dev/null | jq -r '.errorCode' 2>/dev/null)
+
+    if [ "$err" != "" ]; then 
+      echo "ERROR: Failed to login to Omta, please verify the credentials"
+      exit 1
+    fi
+  fi
+
+  # --- TEST LOGIN ---
+  if [ "$MODE" == "apps" -o "$MODE" == "apps" ]; then 
+    curl --location --request GET "https://${TDH_OKTA_DOMAIN}.okta.com/api/v1/apps?limit=25" \
+    --header 'Accept: application/json' \
+    --header 'Content-Type: application/json' \
+    --header "Authorization: SSWS $TDH_OKTA_API_TOKEN" 2>/dev/null 
+  fi
+
+  if [ "$MODE" == "create_app" ]; then 
+    curl --location --request POST "https://${TDH_OKTA_DOMAIN}.okta.com/api/v1/apps" \
+    --header 'Accept: application/json' \
+    --header 'Content-Type: application/json' \
+    --header "Authorization: SSWS $TDH_OKTA_API_TOKEN" \
+    --data-raw '{
+        "name": "oidc_client",
+        "label": "Sample Client2",
+        "signOnMode": "OPENID_CONNECT",
+        "credentials": {
+          "oauthClient": {
+            "token_endpoint_auth_method": "client_secret_post"
+          }
+        },
+        "settings": {
+          "oauthClient": {
+            "client_uri": "http://localhost:8080",
+            "logo_uri": "http://developer.okta.com/assets/images/logo-new.png",
+            "redirect_uris": [
+              "https://example.com/oauth2/callback",
+              "myapp://callback"
+            ],
+            "response_types": [
+              "code"
+            ],
+            "grant_types": [
+              "authorization_code"
+            ],
+            "application_type": "web"
+          }
+        }
+      }'
+  fi
+}
 
