fix for NATIVE minikube context

diff --git a/deployMiniKube b/deployMiniKube
--- a/deployMiniKube
+++ b/deployMiniKube
@@ -463,7 +463,6 @@ if [ ! -f /tdh_tools_docker_container  ]; then
   echo "by Sacha Dubois, VMware Inc,"
   echo "-----------------------------------------------------------------------------------------------------------"
 
-
   # --- MINIKUBE SETUP ----
   VerifyK8SDemoPlatform
   InstallMetallb
@@ -483,10 +482,14 @@ if [ ! -f /tdh_tools_docker_container  ]; then
 
     mkdir -p $HOME/.mc $HOME/.cache $HOME/.config $HOME/.local
     mkdir -p /tmp/docker && chmod a+w /tmp/docker
+    docker run -it --rm --name tdh-tools -v /var/run/docker.sock:/var/run/docker.sock tdh-tools:latest  chmod 666 /var/run/docker.sock > /dev/null 2>&1
     docker run -u $(id -u):$(id -g) --group-add 0 -it --rm --name tdh-tools \
        -v $HOME:$HOME:ro -v $HOME/.local:$HOME/.local:rw -v $HOME/.tanzu-demo-hub:$HOME/.tanzu-demo-hub:rw \
-       -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.cache:$HOME/.cache:rw -v $HOME/.config:$HOME/.config:rw \
-       -v /tmp:/tmp:rw -v /tmp/docker:$HOME/.docker:rw -v $HOME/.mc:$HOME/.mc:rw \
+       -v /var/run/docker.sock:/var/run/docker.sock:rw -v $HOME/.cache:$HOME/.cache:rw -v $HOME/.config:$HOME/.config:rw \
+       -v $HOME/.aws:$HOME/.aws:rw -v $HOME/.vmware-cna-saas:$HOME/.vmware-cna-saas:rw -v $HOME/.azure:$HOME/.azure:rw \
+       -v /tmp:/tmp:rw -v /tmp/docker:$HOME/.docker:rw -v $HOME/.mc:$HOME/.mc:rw -v $HOME/.tanzu:$HOME/.tanzu:rw \
+       -v $HOME/.kube-tkg:$HOME/.kube-tkg:rw -v $HOME/.kube:$HOME/.kube:rw -v $HOME/.govmomi:$HOME/.govmomi:rw \
+       -v $HOME/.ssh:$HOME/.ssh:rw \
        -e "KUBECONFIG=$HOME/.kube/config" --hostname tdh-tools tdh-tools:latest $TDHPATH/$CMD_EXEC $CMD_ARGS
 
     # --- FINISH CURRENT SESSION AS WE RUN AS CONTAINER ---
@@ -496,6 +499,14 @@ if [ ! -f /tdh_tools_docker_container  ]; then
     checkCLIcommands TOOLS
     checkCLIcommands TKG
   fi
+fi
+
+# --- SWITCH TO MINIKUBE CONTEXT ---
+kubectl config use-context $TDH_MINIKUBE_PROFILE > /dev/null 2>&1
+if [ $? -ne 0 ]; then 
+  echo "ERROR: Unable to switch to context $TDH_MINIKUBE_PROFILE"
+  echo "       => kubectl config use-context $TDH_MINIKUBE_PROFILE"
+  exit 1
 fi
 
 uodateConfigMap tanzu-demo-hub TDH_DOMAIN               $AWS_HOSTED_DNS_DOMAIN 
