testing

diff --git a/deployTKG b/deployTKG
--- a/deployTKG
+++ b/deployTKG
@@ -765,6 +765,7 @@ echo gaga10
 fi
 
 if [ "${TDH_TKGWC_TBS}" == "true" ]; then
+  messageTitle "Installing Tanzu Build Service"
   if [ ! -x /usr/local/bin/kp ]; then
     sudo cp $TDHPATH/software/kp-linux-0.1.3 /usr/local/bin/kp
     sudo chmod 777 /usr/local/bin/kp
@@ -805,9 +806,23 @@ if [ "${TDH_TKGWC_TBS}" == "true" ]; then
     fi
   fi
 
-echo "kbld relocate -f /tmp/images.lock --lock-output /tmp/images-relocated.lock --repository $DNS_HARBOR:sadubois"
-  kbld relocate -f /tmp/images.lock --lock-output /tmp/images-relocated.lock --repository $DNS_HARBOR:sadubois
+  messagePrint "- Relocate the images" "$PCF_REGISTRY_NAME/library/build-service"
+echo "kbld relocate -f /tmp/images.lock --lock-output /tmp/images-relocated.lock --repository $PCF_REGISTRY_NAME/library/build-service"
+  kbld relocate -f /tmp/images.lock --lock-output /tmp/images-relocated.lock --repository $PCF_REGISTRY_NAME/library/build-service
+  if [ $? -ne 0 ]; then  
+    echo "ERROR: Docker login does not work"
+    echo "       => docker login $DNS_HARBOR -u admin -p $HARBOR_PASS"; exit
+  fi
 
+echo "ytt -f /tmp/build-service/values.yaml -f /tmp/build-service/manifests/ -v docker_repository="$PCF_REGISTRY_NAME/library/build-service" -v docker_username="admin" -v docker_password="$HARBOR_PASS" | kbld -f /tmp/images-relocated.lock -f- | kapp deploy -a tanzu-build-service -f- -y"
+
+  ytt -f /tmp/build-service/values.yaml \
+    -f /tmp/build-service/manifests/ \
+    -v docker_repository="$PCF_REGISTRY_NAME/library/build-service" \
+    -v docker_username="admin" \
+    -v docker_password="$HARBOR_PASS" \
+    | kbld -f /tmp/images-relocated.lock -f- \
+    | kapp deploy -a tanzu-build-service -f- -y
 
 
 fi
