testing

diff --git a/deployTKG b/deployTKG
--- a/deployTKG
+++ b/deployTKG
@@ -67,7 +67,6 @@ echo "Tanzu Demo Hub - Deploy TKG Workload Cluster"
 echo "by Sacha Dubois, VMware Inc,"
 echo "-----------------------------------------------------------------------------------------------------------"
 
-echo gaga1
 while [ "$1" != "" ]; do
   case $1 in
     -d)  TKG_DEPLOYMENT=$2;;
@@ -77,7 +76,6 @@ while [ "$1" != "" ]; do
   shift
 done
 
-echo gaga2
 if [ "${TKG_DEPLOYMENT}" == "" -o "${TKG_WC_CLUSTER}" == "" -o "${TDH_TKGWC_NAME}" == "" ]; then
   if [ "${TKG_DEPLOYMENT}" == "" ]; then 
     listDeployments
@@ -123,9 +121,25 @@ if [ "${TDH_TKGWC_CONTROPLANE}" != "" ]; then TDH_OPTIONS="$TDH_OPTIONS --contro
 if [ "${TDH_TKGWC_WORKERNODES}" != "" ]; then TDH_OPTIONS="$TDH_OPTIONS --worker-machine-count=$TDH_TKGWC_WORKERNODES"; fi
 
 echo "TDH_TKGWC_NAME:$TDH_TKGWC_NAME"
+echo "TDH_TKGMC_NAME:$TDH_TKGMC_NAME"
+
+# --- VERIFY TKG MANAGEMENT CLUSTER ---
+stt=$(tkg get mc --name $TDH_TKGMC_NAME -o json | jq -r '.[].status')
+con=$(tkg get mc --name $TDH_TKGMC_NAME -o json | jq -r '.[].context')
+isc=$(tkg get mc --name $TDH_TKGMC_NAME -o json | jq -r '.[].true')
+if [ "${stt}" != "Success" ]; then 
+  echo "ERROR: $0 TKG Management Cluster deployment was not Successfil"; exit 1
+fi
+
+if [ "${isc}" != "true" ]; then 
+  tkg set mc -c "$con" $TDH_TKGMC_NAME > /dev/null 2>&1
+fi
+
+exit
+
 
 echo "tkg create cluster $TDH_TKGWC_NAME $TDH_OPTIONS"
-tkg create cluster $TDH_TKGWC_NAME $TDH_OPTIONS
+#tkg create cluster $TDH_TKGWC_NAME $TDH_OPTIONS
 
 exit
 
