testing

diff --git a/deployTKG b/deployTKG
--- a/deployTKG
+++ b/deployTKG
@@ -839,12 +839,12 @@ if [ "${TDH_TKGWC_TBS}" == "true" ]; then
 
   messagePrint "- Import Tanzu Build Service Dependencies" ""
   fil=$(ls -1 tanzu-demo-hub/software/tbs/descriptor-* | tail -1)
-echo "kp import -f $fil"
-  kp import -f $fil
-  if [ $? -ne 0 ]; then
-    echo "ERROR: Install dependancies"
-    echo "       => kp import -f $fil"; exit
-  fi
+#echo "kp import -f $fil"
+#  kp import -f $fil
+#  if [ $? -ne 0 ]; then
+#    echo "ERROR: Install dependancies"
+#    echo "       => kp import -f $fil"; exit
+#  fi
 
 exit
 echo gugu
