rapair deleting TKGmc

diff --git a/deployTKG b/deployTKG
--- a/deployTKG
+++ b/deployTKG
@@ -332,124 +332,129 @@ installKubeapps
 installGitea
 installJenkins
 installArgoCD
-installGitLab
+#installGitLab
 
 if [ "${TDH_TKGMC_INFRASTRUCTURE}" == "vSphere" -a "$TDH_TKGMC_ENVNAME" == "tkgs" ]; then
   TMC_PROVISIONER_NAME=attached
   TMC_MANAGEMENT_CLUSTER=attached
+
+  echo "INFO: Attaching the cluster $TDH_TKGWC_NAME to TMC needs to be done manually, because of stability problems with TMC"
+  echo "      s attaching clould get stalled. It can be done in the TMC GUI or by CLI."
+  if [ "$NATIVE" == "0" ]; then
+    echo "       => tools/${TDH_TOOLS}.sh"
+    echo "          tdh-tools:/$ tmc cluster attach --name $TDH_TKGWC_NAME --kubeconfig=$KUBECONFIG -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -g tanzu-demo-hub"
+    echo "          tdh-tools:/$ exit"
+  else
+    echo "       => tmc cluster attach --name $TDH_TKGWC_NAME --kubeconfig=$KUBECONFIG -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -g tanzu-demo-hub"
+  fi
 else
   TDH_MANAGEMENT_CLUSTER=$TDH_TKGMC_NAME
-fi
+  TMC_MANAGEMENT_CLUSTER=$TDH_MANAGEMENT_CLUSTER
+  TMC_MANAGEMENT_CLUSTER=attached
+  KUBECONFIG=$HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.kubeconfig
 
-if [ "$TDH_TANZU_MISSION_CONTROL_REGISTRATION" == "true" ]; then
-echo "tmc cluster list -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER"
-tmc cluster list -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER | grep tdh
-echo gaga1
-  cmdLoop tmc cluster list -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -o json > /tmp/output.json
-  nam=$(jq -r --arg key "$TDH_TKGWC_NAME" '.clusters[] | select(.fullName.name == $key).fullName.name' /tmp/output.json)
-echo "NAM-1:$nam"
-  if [ "$nam" == "$TDH_TKGWC_NAME" ]; then
-echo "tmc cluster validate -k $KUBECONFIG"
-    tmc cluster validate -k $KUBECONFIG
+  echo "INFO: Attaching the cluster $TDH_TKGWC_NAME to TMC needs to be done manually, because of stability problems with TMC"
+  echo "      as attaching clould get stalled. It can be done in the TMC GUI or by CLI."
+  if [ "$NATIVE" == "0" ]; then
+    echo "       => tools/${TDH_TOOLS}.sh"
+    echo "          tdh-tools:/$ tmc cluster attach --name $TDH_TKGWC_NAME --kubeconfig=$KUBECONFIG -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -g tanzu-demo-hub"
+    echo "          tdh-tools:/$ exit"
+  else
+    echo "       => tmc cluster attach --name $TDH_TKGWC_NAME --kubeconfig=$KUBECONFIG -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -g tanzu-demo-hub"
+  fi
 
-    stt=$(jq -r --arg key "$TDH_TKGWC_NAME" '.clusters[] | select(.fullName.name == $key).status.phase' /tmp/output.json) 
-    hlt=$(jq -r --arg key "$TDH_TKGWC_NAME" '.clusters[] | select(.fullName.name == $key).status.health' /tmp/output.json) 
-echo "gaga stt:$stt hlt:$hlt"
-    if [ "$stt" != "READY" -a "$hlt" != "HEALTHY" ]; then 
-echo idiot
-echo "tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f "
-      tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f > /dev/null 2>&1; ret=$?
-echo "RET:$ret"
-      if [ $ret -ne 0 ]; then
-echo "tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f"
-        tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f > /tmp/error.log 2>&1; ret=$?
+  if [ "$TDH_TANZU_MISSION_CONTROL_REGISTRATION" == "true1" ]; then
+    cmdLoop tmc cluster list -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -o json > /tmp/output.json
+    nam=$(jq -r --arg key "$TDH_TKGWC_NAME" '.clusters[] | select(.fullName.name == $key).fullName.name' /tmp/output.json)
+    if [ "$nam" == "$TDH_TKGWC_NAME" ]; then
+      tmc cluster validate -k $KUBECONFIG -m attached -p attached > /dev/null 2>&1; ret=$?
+
+      stt=$(jq -r --arg key "$TDH_TKGWC_NAME" '.clusters[] | select(.fullName.name == $key).status.phase' /tmp/output.json) 
+      hlt=$(jq -r --arg key "$TDH_TKGWC_NAME" '.clusters[] | select(.fullName.name == $key).status.health' /tmp/output.json) 
+      if [ "$stt" != "READY" -a "$hlt" != "HEALTHY" ]; then 
+        tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f > /dev/null 2>&1; ret=$?
         if [ $ret -ne 0 ]; then
-          logMessages /tmp/error.log
-          echo "ERROR: TMC failed to delete cluster"
-          if [ "$NATIVE" == "0" ]; then
-            echo "       => tools/${TDH_TOOLS}.sh"
-            echo "          tdh-tools:/$ tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f"
-            echo "          tdh-tools:/$ exit"
+          tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f > /tmp/error.log 2>&1; ret=$?
+          if [ $ret -ne 0 ]; then
+            logMessages /tmp/error.log
+            echo "ERROR: TMC failed to delete cluster"
+            if [ "$NATIVE" == "0" ]; then
+              echo "       => tools/${TDH_TOOLS}.sh"
+              echo "          tdh-tools:/$ tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f"
+              echo "          tdh-tools:/$ exit"
+            else
+              echo "       => tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f"
+            fi
+            exit 1
           else
-            echo "       => tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f"
+            if [ -d /tmp/k8s-attach-manifest.yaml ]; then
+              kubectl apply -f k8s-attach-manifest.yaml
+            fi
           fi
-          exit 1
+  
+          # --- WAIT FOR THE CLUSTER TO BE DELETED ---
+          cnt=1
+          while [ $cnt -ne 0 ]; do
+            cnt=$(tmc cluster list --name $TDH_TKGWC_NAME 2>/dev/null | grep -c $TDH_TKGWC_NAME)
+            sleep 20
+          done
         else
-          if [ -d /tmp/k8s-attach-manifest.yaml ]; then
-            kubectl apply -f k8s-attach-manifest.yaml
-          fi
+          # --- WAIT FOR THE CLUSTER TO BE DELETED ---
+          cnt=1
+          while [ $cnt -ne 0 ]; do
+            cnt=$(tmc cluster list --name $TDH_TKGWC_NAME 2>/dev/null | grep -c $TDH_TKGWC_NAME)
+            sleep 20
+          done
         fi
-
-        # --- WAIT FOR THE CLUSTER TO BE DELETED ---
-        cnt=1
-        while [ $cnt -ne 0 ]; do
-          cnt=$(tmc cluster list --name $TDH_TKGWC_NAME 2>/dev/null | grep -c $TDH_TKGWC_NAME)
-          sleep 20
-        done
-      else
-        # --- WAIT FOR THE CLUSTER TO BE DELETED ---
-        cnt=1
-        while [ $cnt -ne 0 ]; do
-          cnt=$(tmc cluster list --name $TDH_TKGWC_NAME 2>/dev/null | grep -c $TDH_TKGWC_NAME)
-          sleep 20
-        done
+  
+        kubectl delete ns vmware-system-tmc --wait=true > /dev/null 2>&1
       fi
-
-      kubectl delete ns vmware-system-tmc --wait=true > /dev/null 2>&1
+    fi
+  
+    cmdLoop tmc cluster list -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -o json > /tmp/output.json
+    nam=$(jq -r --arg key "$TDH_TKGWC_NAME" '.clusters[] | select(.fullName.name == $key).fullName.name' /tmp/output.json)
+    if [ "$nam" != "$TDH_TKGWC_NAME" ]; then
+      ret=1; cnt=0
+      while [ $ret -ne 0 -a $cnt -lt 5 ]; do
+        (cd /tmp && tmc cluster attach --name $TDH_TKGWC_NAME --kubeconfig=$KUBECONFIG -p $TMC_PROVISIONER_NAME \
+              -m $TMC_MANAGEMENT_CLUSTER -g tanzu-demo-hub --force > /tmp/error.log 2>&1); ret=$?
+  
+        [ $ret -eq 0 ] && break
+        cmdLoop tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f > /tmp/error.log 2>&1
+  
+        let cnt=cnt+1
+        sleep 30
+      done
+  
+      if [ $ret -ne 0 ]; then
+        logMessages /tmp/error.log
+        echo "ERROR: TMC failed to attach cluster"
+        if [ "$NATIVE" == "0" ]; then
+          echo "       => tools/${TDH_TOOLS}.sh"
+          echo "          tdh-tools:/$ tmc cluster attach --name $TDH_TKGWC_NAME --kubeconfig=$KUBECONFIG -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -g tanzu-demo-hub"
+          echo "          tdh-tools:/$ tmc cluster logs -k $KUBECONFIG"
+          echo "          tdh-tools:/$ exit"
+        else
+          echo "       => tanzu cluster delete $TDH_TKGWC_NAME -y"
+          echo "       => tmc cluster logs -k $KUBECONFIG"
+        fi
+        exit 1
+      else
+        if [ -f /tmp/k8s-attach-manifest.yaml ]; then 
+          cmdLoop kubectl apply -f /tmp/k8s-attach-manifest.yaml > /dev/null 2>&1
+          deleteFailedPods  vmware-system-tmc
+          runningPods       vmware-system-tmc
+        fi
+      fi
     fi
   fi
 
-echo gaga3
-tmc cluster list -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER | grep tdh
-echo gaga4
-  cmdLoop tmc cluster list -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -o json > /tmp/output.json
-  nam=$(jq -r --arg key "$TDH_TKGWC_NAME" '.clusters[] | select(.fullName.name == $key).fullName.name' /tmp/output.json)
-echo "NAM-2:$nam"
-  if [ "$nam" != "$TDH_TKGWC_NAME" ]; then
-    ret=1; cnt=0
-    while [ $ret -ne 0 -a $cnt -lt 5 ]; do
-      (cd /tmp && tmc cluster attach --name $TDH_TKGWC_NAME --kubeconfig=$KUBECONFIG -p $TMC_PROVISIONER_NAME \
-            -m $TMC_MANAGEMENT_CLUSTER -g tanzu-demo-hub --force > /tmp/error.log 2>&1); ret=$?
-
-      [ $ret -eq 0 ] && break
-      cmdLoop tmc cluster delete $TDH_TKGWC_NAME -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -f > /tmp/error.log 2>&1
-
-      let cnt=cnt+1
-      sleep 30
-    done
-
-    if [ $ret -ne 0 ]; then
-      logMessages /tmp/error.log
-      echo "ERROR: TMC failed to attach cluster"
-      if [ "$NATIVE" == "0" ]; then
-        echo "       => tools/${TDH_TOOLS}.sh"
-        echo "          tdh-tools:/$ tmc cluster attach --name $TDH_TKGWC_NAME --kubeconfig=$KUBECONFIG -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER -g tanzu-demo-hub"
-        echo "          tdh-tools:/$ tmc cluster logs -k $KUBECONFIG"
-        echo "          tdh-tools:/$ exit"
-      else
-        echo "       => tanzu cluster delete $TDH_TKGWC_NAME -y"
-        echo "       => tmc cluster logs -k $KUBECONFIG"
-      fi
-      exit 1
-    else
-      if [ -f /tmp/k8s-attach-manifest.yaml ]; then 
-        cmdLoop kubectl apply -f /tmp/k8s-attach-manifest.yaml > /dev/null 2>&1
-        deleteFailedPods  vmware-system-tmc
-        runningPods       vmware-system-tmc
-      fi
-    fi
-  fi
-fi
-
-echo gaga5
-tmc cluster list -p $TMC_PROVISIONER_NAME -m $TMC_MANAGEMENT_CLUSTER | grep tdh
-echo gaga6
-exit
-# --- NO CONNECTION FROM A PEZ-INTERNAL CLUSTER ---
-if [ "${TDH_TKGMC_INFRASTRUCTURE}" != "vSphere1" ]; then
-  checkTMCintegration      TO    ## Tanzu Observability (Wavefront)
-  checkTMCintegration      TDP   ## Tanzu Data Protection
-  checkTMCintegration      TCI   ## Tanzu Cluster Inspection
+  # --- NO CONNECTION FROM A PEZ-INTERNAL CLUSTER ---
+  #if [ "${TDH_TKGMC_INFRASTRUCTURE}" != "vSphere1" ]; then
+  #  checkTMCintegration      TO    ## Tanzu Observability (Wavefront)
+  #  checkTMCintegration      TDP   ## Tanzu Data Protection
+  #  checkTMCintegration      TCI   ## Tanzu Cluster Inspection
+  #fi
 fi
 
 echo "-----------------------------------------------------------------------------------------------------------"
@@ -457,11 +462,11 @@ echo "Tanzu Kubernetes Grid Cluster ($TDH_TKGWC_NAME) build completed"
 echo "-----------------------------------------------------------------------------------------------------------"
 if [ "$NATIVE" == "0" ]; then
   printf "\e[1m1.) Set KUBECONFIG and set the cluster context\e[0m\n"
-  echo "    => tools/tdh-tools.sh"
+  echo "    => tools/${TDH_TOOLS}.sh"
   echo "       tdh-tools:/$ kubectl config set-cluster ${TDH_TKGWC_NAME}"
   echo "       tdh-tools:/$ kubectl config use-context ${TDH_TKGWC_CONTEXT}"
   printf "\e[1m2.) Delete Cluster if not used anymore\e[0m\n"
-  echo "    => tools/tdh-tools.sh"
+  echo "    => tools/${TDH_TOOLS}.sh"
   echo "       tdh-tools:/$ tanzu cluster delete $TDH_TKGWC_NAME"
 else
   echo "1.) Set KUBECONFIG and set the cluster context"
diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -406,6 +406,7 @@ vSphereKubeconfig() {
   # --- SET LOGIN PASSWORD AS ENVIRONMENT VARIABLE ---
   export KUBECTL_VSPHERE_PASSWORD=$VSPHERE_TKGS_VCENTER_PASSWORD
 
+#hallo
   mv $HOME/.kube/config $HOME/.kube/config.bak
 
   ret=1; cnt=0
@@ -2841,7 +2842,6 @@ createTKGMCcluster() {
 
       messagePrint " ▪ Management Cluster Creating Completed"    "/tmp/$TDH_TKGMC_NAME.log"
 
-#hallo
       tanzu management-cluster kubeconfig get --admin > /dev/null 2>&1
       kubectl config set-cluster $TDH_TKGMC_NAME > /dev/null 2>&1
       kubectl config use-context ${TDH_TKGMC_NAME}-admin@$TDH_TKGMC_NAME > /dev/null 2>&1
@@ -4701,7 +4701,12 @@ tkgCreateCluster() {
 
     # --- GET CREDENTIALS AND SET ENVIRONMENT ---
     tanzu cluster kubeconfig get $TDH_TKGWC_NAME --admin > /dev/null 2>&1
-    tanzu cluster kubeconfig get $TDH_TKGWC_NAME --admin > $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.kubeconfig 2>/dev/null
+
+    # --- CREATE GLOBAL KUBECONFIG FILE ---
+    mv $HOME/.kube/config $HOME/.kube/config.bak
+    tanzu cluster kubeconfig get $TDH_TKGWC_NAME --admin > /dev/null 2>&1
+    mv $HOME/.kube/config $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.kubeconfig
+    mv $HOME/.kube/config.bak $HOME/.kube/config
   fi
 
   #########################################################################################################################
@@ -4798,7 +4803,12 @@ tkgCreateCluster() {
 
     # --- GET CREDENTIALS AND SET ENVIRONMENT ---
     tanzu cluster kubeconfig get $TDH_TKGWC_NAME --admin > /dev/null 2>&1
-    tanzu cluster kubeconfig get $TDH_TKGWC_NAME --admin > $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.kubeconfig 2>/dev/null
+
+    # --- CREATE GLOBAL KUBECONFIG FILE ---
+    mv $HOME/.kube/config $HOME/.kube/config.bak
+    tanzu cluster kubeconfig get $TDH_TKGWC_NAME --admin > /dev/null 2>&1
+    mv $HOME/.kube/config $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.kubeconfig
+    mv $HOME/.kube/config.bak $HOME/.kube/config
   fi
 
   #########################################################################################################################
@@ -4820,6 +4830,7 @@ tkgCreateCluster() {
         if [ "$TDH_TKGWC_NAME_TAG" == "TKG_CLUSTER_02" ]; then
           TDH_TKGWC_CPIP_ADDRESS=$VSPHERE_TKGM_WKLD_CLUSTER02_CONTROL_PLANE
           TDH_TKGWC_LB_ADDRESS=$VSPHERE_TKGM_WKLD_CLUSTER03_LOADBALANCER_POOL
+
         fi
   
         if [ "$TDH_TKGWC_NAME_TAG" == "TKG_CLUSTER_04" ]; then
@@ -4914,7 +4925,6 @@ tkgCreateCluster() {
       messagePrint " ▪ Workload Cluster Name"                 "$TDH_TKGWC_NAME"
       messagePrint " ▪ Workload Cluster Configuration"        "$HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml"
       messagePrint " ▪ Workload Cluster Kubeconfig"           "$HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.kubeconfig"
-echo hallo
 
       messagePrint " ▪ TKG Cluster Kubernetes Release"        "$TDH_TKGWC_K8S_VERSION"
       messagePrint " ▪ TKG Cluster Worker Nodes"              "$TDH_TKGWC_WORKERNODES"
@@ -5673,10 +5683,7 @@ exit
     fi
   fi
 
-
-return
-
-  messageTitle "Spring Cloud Gateway"
+  messageTitle "Tanzu Application Platform (TAP)"
   cnt=0
   if [ $cnt -eq 0 ]; then
     TDH_SERVICE_TAP_VERSION=$(getConfigMap tanzu-demo-hub TDH_SERVICE_TAP_VERSION)
@@ -5830,14 +5837,30 @@ installSpringCloudGateway() {
   messageTitle "Spring Cloud Gateway"
   cnt=$(kubectl get pods -A | egrep -c "^$NAMESPACE")
   if [ $cnt -eq 0 ]; then
+    TBS_FILE="/tmp/spring-cloud-gateway-k8s-$TDH_SERVICE_SPRING_CLOUD_GATEWAY_VERSION.tgz"
+    [ -f $TBS_FILE ] && rm -f $TBS_FILE
+
     # --- DOWNLOAD BUILD_SERVICE BINARIES ---
     downloadFromPivnet spring-cloud-gateway-for-kubernetes $TDH_SERVICE_SPRING_CLOUD_GATEWAY_VERSION \
         "$TDH_SERVICE_SPRING_CLOUD_GATEWAY_VERSION" "Spring Cloud Gateway for Kubernetes Installer"
 
-    TBS_FILE="/tmp/spring-cloud-gateway-k8s-$TDH_SERVICE_SPRING_CLOUD_GATEWAY_VERSION.tgz"
     [ -d /tmp/spring-cloud-gateway ] && rm -rf /tmp/spring-cloud-gateway
     mkdir -p /tmp/spring-cloud-gateway
-    tar xfz $TBS_FILE -C /tmp/spring-cloud-gateway
+
+    tar xfz $TBS_FILE -C /tmp/spring-cloud-gateway; ret=$? 
+    if [ $ret -ne 0 ]; then
+      logMessages /tmp/error.log
+      echo "ERROR: Failed to unpack $TBS_FILE"
+      if [ "$NATIVE" == "0" ]; then
+        echo "       => tools/${TDH_TOOLS}.sh"
+        echo "          tdh-tools:/$ tar xfz $TBS_FILE -C /tmp/spring-cloud-gateway"
+        echo "          tdh-tools:/$ exit"
+      else
+        echo "       => tar xfz $TBS_FILE -C /tmp/spring-cloud-gateway"
+      fi
+
+      exit 1
+    fi
 
     messagePrint " ▪ Verify VMware Registry Access" "$TDH_REGISTRY_VMWARE_NAME"
     cnt=0; ret=1
@@ -6289,7 +6312,6 @@ installGitea() {
   else
     ver=""; crt=""; stt=""; dat=""
   fi
-echo figu11
   
   cmdLoop kubectl -n $HELMCHART exec -it gitea-0 -- $HELMCHART admin user change-password -u gitea_admin -p $TDH_HARBOR_ADMIN_PASSWORD > /tmp/error.log 2>&1; ret=$?
   if [ $ret -ne 0 ]; then
