testing

diff --git a/deployTCE b/deployTCE
--- a/deployTCE
+++ b/deployTCE
@@ -56,20 +56,16 @@ listDeployments() {
   printf "%-31s %-7s %-28s %s\n" "CONFIURATION" "CLOUD" "MANAGEMENT-CLUSTER" "STATUS"
   echo "-----------------------------------------------------------------------------------------------------------"
 
-echo gaga1
   cnt=$(ls -1 ${HOME}/.tanzu-demo-hub/config/tcemc-*.cfg 2>/dev/null | wc -l | sed 's/  *//g')
   if [ $cnt -eq 0 ]; then
     echo "No TKG Management Cluster has been deployed, Please use ./deployTKGmc"
   else
-echo gaga2
     for deployment in $(ls -1 ${HOME}/.tanzu-demo-hub/config/tcemc-*.cfg 2>/dev/null); do
-echo gaga21
       TDH_TKGMC_NAME=$(egrep "^TDH_TKGMC_NAME=" $deployment | awk -F'=' '{ print $2 }')
       TDH_TKGMC_CONFIG=$(egrep "^TDH_TKGMC_CONFIG=" $deployment | awk -F'=' '{ print $2 }')
       TDH_TKGMC_INFRASTRUCTURE=$(egrep "^TDH_TKGMC_INFRASTRUCTURE=" $deployment | awk -F'=' '{ print $2 }')
       TDH_TKGMC_KUBECONFIG=$(egrep "^TDH_TKGMC_KUBECONFIG=" $deployment | awk -F'=' '{ print $2 }')
 
-echo gaga22
       if [ "$TDH_TKGMC_INFRASTRUCTURE" == "Azure" ]; then
         TDH_REGION=$(egrep "^AZURE_LOCATION:" ${HOME}/.tanzu-demo-hub/config/$TDH_TKGMC_CONFIG | awk '{ print $2 }')
       fi
@@ -77,22 +73,16 @@ echo gaga22
       if [ "$TDH_TKGMC_INFRASTRUCTURE" == "AWS" ]; then
         TDH_REGION=$(egrep "^AWS_REGION:" ${HOME}/.tanzu-demo-hub/config/$TDH_TKGMC_CONFIG | awk '{ print $2 }')
       fi
-echo gaga23
 
       # --- VERIFY MANAGEMENT CLUSTER ---
       if [ "$TDH_TKGMC_INFRASTRUCTURE" == "AWS" -o "$TDH_TKGMC_INFRASTRUCTURE" == "Azure" -o "$TDH_TKGMC_INFRASTRUCTURE" == "docker1" ]; then
-echo gaga31
         kubectl get cluster --kubeconfig ${HOME}/.tanzu-demo-hub/config/${TDH_TKGMC_KUBECONFIG} -A --request-timeout 1 > /dev/null 2>&1
         if [ $? -ne 0 ]; then smc="unavailable"; else smc="active"; fi
-echo gaga32
 
         cnt=$(kubectl config get-clusters | egrep -c "^$TDH_TKGMC_NAME")
         if [ $cnt -eq 0 ]; then stt="not-deployed"; else stt="deployed/$smc"; fi
-echo gaga34
       else
-echo "tanzu config server list |  egrep -c \" $TDH_TKGMC_NAME \""
         cnt=$(tanzu config server list |  egrep -c " $TDH_TKGMC_NAME ")
-echo "CNT:$cnt"
         if [ $cnt -gt 0 ]; then
           smc="active"
           ctx=$(tanzu config server list |  egrep " $TDH_TKGMC_NAME " | awk '{ print $NF }')
@@ -239,7 +229,73 @@ if [ ! -f /tdh_tools_docker_container  ]; then
 
     # --- FINISH CURRENT SESSION AS WE RUN AS CONTAINER ---
     exit $ret
-  else
+  fi
+fi
+
+while [ "$1" != "" ]; do
+  case $1 in
+    -d)   TKG_DEPLOYMENT=$2;;
+    -m)   TDH_TKGMC_NAME=$2;;
+    -n)   TDH_TKGWC_NAME=$2;;
+    -k)   TDH_TKGWC_K8S_VERSION=$2;;
+    -tag) TDH_TKGWC_NAME_TAG=$2;;
+    --debug)       DEBUG=1;;
+    --native)      NATIVE=1;;
+  esac
+  shift
+done
+
+
+if [ "${TKG_DEPLOYMENT}" == "" -o "${TDH_TKGMC_NAME}" == "" -o "${TDH_TKGWC_NAME}" == "" ]; then
+  if [ "${TKG_DEPLOYMENT}" == "" ]; then
+    listDeployments
+  fi
+
+  if [ "${TKG_WC_CLUSTER}" == "" ]; then
+    listClusterConfig
+  fi
+  usage; exit 0
+fi
+
+# --- VERIFY DEPLOYMENT ---
+TKG_DEPLOYMENT_CONFIG=$(echo $TKG_DEPLOYMENT | sed 's/cfg/yaml/g')
+if [ ! -f ${TDHPATH}/deployments/${TKG_DEPLOYMENT} ]; then
+  echo "ERROR: Deployment file $TKG_DEPLOYMENT can not be found in ${TDHPATH}/deployments"
+  exit 1
+else
+  . ${TDHPATH}/deployments/${TKG_DEPLOYMENT}
+fi
+
+if [ ! -f ${TDHPATH}/deployments/${TKG_DEPLOYMENT} ]; then
+  echo "ERROR: The Deployment deployments/$TKG_DEPLOYMENT does not have a releated $TKG_DEPLOYMENT file"
+  echo "       Please take deployments/tkg-tanzu-demo-hub.yaml as a template."
+  exit 1
+fi
+
+# --- CHECK ENVIRONMENT VARIABLES ---
+if [ -f ~/.tanzu-demo-hub.cfg ]; then
+  . ~/.tanzu-demo-hub.cfg
+fi
+
+# --- SOURCE MANAGEMENT CLUSTER VARIABLES ---
+if [ -f $HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.cfg ]; then
+  . $HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.cfg
+fi
+
+if [ "$TDH_DEPLOYMENT_CLUSTER_PLAN" == "dev" ]; then
+  TDH_TKGMC_CONFIG=$TDH_TKGMC_WC_CONFIG_DEV
+else
+  TDH_TKGMC_CONFIG=$TDH_TKGMC_WC_CONFIG_PROD
+fi
+
+# --- DIRTY FIX ---
+export TDH_INFRASTRUCTURE=$TDH_TKGMC_INFRASTRUCTURE
+export TDH_DEPLOYMENT_ENV_NAME=$TDH_INFRASTRUCTURE
+export TDH_TLS_CERT=tanzu-demo-hub
+export TDH_TLS_SECRET=${TDH_TLS_CERT}-tls
+export TDH_TLS_ISSUER_NAME=letsencrypt-staging
+export TDH_TLS_ISSUER_CONFIG=/tmp/issuer-dns-manager1.yaml
+
     # --- VERYFY ACCESS TO CLOUD ---
     chownDirectories
     checkTDHenvironment
@@ -251,8 +307,7 @@ if [ ! -f /tdh_tools_docker_container  ]; then
     checkCLIcommands TKG
     checkCLIcommands TANZU
     checkCLIcommands TMC
-  fi
-fi
+
 
 if [ "$TDH_TKGWC_K8S_VERSION" != "" ]; then 
   tanzu kubernetes-release get 2323 | sed '1d'
