fixed credentials

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1693,9 +1693,9 @@ createCluster() {
 >> $TKG_TEMPLATE
 
 
-    echo "AWS_ACCESS_KEY_ID: <encoded:QUtJQVdSWDZLS1NHSEdaUUJBSEQ=>"                  >  $TKG_TEMPLATE
+    echo "AWS_ACCESS_KEY_ID:"                  >  $TKG_TEMPLATE
     echo "AWS_AMI_ID: ami-066dad3403314512a"                                          >> $TKG_TEMPLATE
-    echo "AWS_B64ENCODED_CREDENTIALS: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVdSWDZLS1NHSEdaUUJBSEQKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0geUgvZjBKaFB3RVY0dDhRYWRKZUdVTFJJSFJ4c25LYlVQMEc5Y0VCZApyZWdpb24gPSBldS1jZW50cmFsLTEKCg=="                                          >> $TKG_TEMPLATE
+    echo "AWS_B64ENCODED_CREDENTIALS: "                                          >> $TKG_TEMPLATE
     echo "AWS_NODE_AZ: eu-central-1a"                                          >> $TKG_TEMPLATE
     echo "AWS_NODE_AZ_1: \"\""                                          >> $TKG_TEMPLATE
     echo "AWS_NODE_AZ_2: \"\""                                          >> $TKG_TEMPLATE
@@ -1712,7 +1712,7 @@ createCluster() {
     echo "AWS_PUBLIC_SUBNET_ID_1: \"\""                                          >> $TKG_TEMPLATE
     echo "AWS_PUBLIC_SUBNET_ID_2: \"\""                                          >> $TKG_TEMPLATE
     echo "AWS_REGION: eu-central-1"                                          >> $TKG_TEMPLATE
-    echo "AWS_SECRET_ACCESS_KEY: <encoded:eUgvZjBKaFB3RVY0dDhRYWRKZUdVTFJJSFJ4c25LYlVQMEc5Y0VCZA==>"                                          >> $TKG_TEMPLATE
+    echo "AWS_SECRET_ACCESS_KEY: "                                          >> $TKG_TEMPLATE
     echo "AWS_SSH_KEY_NAME: tanzu-demo-hub"                                          >> $TKG_TEMPLATE
     echo "AWS_VPC_CIDR: 10.0.0.0/16"                                          >> $TKG_TEMPLATE
     echo "AWS_VPC_ID: \"\""                                          >> $TKG_TEMPLATE
@@ -1739,8 +1739,8 @@ createCluster() {
     echo "LDAP_USER_SEARCH_NAME_ATTRIBUTE: \"\""                                          >> $TKG_TEMPLATE
     echo "LDAP_USER_SEARCH_USERNAME: userPrincipalName"                                          >> $TKG_TEMPLATE
     echo "NODE_MACHINE_TYPE: c4.2xlarge"                                          >> $TKG_TEMPLATE
-    echo "OIDC_IDENTITY_PROVIDER_CLIENT_ID: \"=0oalw23ymlHT9IDAf5d6\""              >> $TKG_TEMPLATE
-    echo "OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: \"<encoded:UmNTYTFmUnA2eU5OZTZCbGM3cHlrV2UtYlNjcUc0cVB2RGtsYmVfQQ==>\""              >> $TKG_TEMPLATE
+    echo "OIDC_IDENTITY_PROVIDER_CLIENT_ID: \"\""              >> $TKG_TEMPLATE
+    echo "OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: \"\""              >> $TKG_TEMPLATE
     echo "OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: groups"                             >> $TKG_TEMPLATE
     echo "OIDC_IDENTITY_PROVIDER_ISSUER_URL: \"https://vmware-tdh.okta.com\""                             >> $TKG_TEMPLATE
     echo "OIDC_IDENTITY_PROVIDER_NAME: \"\""                             >> $TKG_TEMPLATE
@@ -4912,6 +4912,98 @@ installPackage() {
   fi
 }
 
+# ------------------------------------------------------------------------------------------
+# Function Name ......: selfTestInit   
+# Function Category ..: selfTest - Tanzu Demo Hub automated testing facility for Demos
+# Function Purpose ...: Initialize SelfTest Counting and print the test Name
+# ------------------------------------------------------------------------------------------
+# Argument ($1) ......: Test Message Text (ie. "Deploy a Database") ............... (string)
+# Argument ($2) ......: Total count of Tests (ie. 20) ................................ (int)
+# Return Value .......: return 0 ..................................................... (int)
+# ------------------------------------------------------------------------------------------
+selfTestInit() {
+  _stp=1
+  _tot=$2
+  _msg="$1"
+  _cnt=$(echo "${_msg}" | wc -c | sed 's/ //g')
+  _dat=$(date "+%Y%m%d-%H:%M:%S")
+  _num="       "
+
+  if [ $first -eq 0 ]; then
+    printf "\b\b\b\b\b\b\bcompleted\n"
+  else
+    first=0
+  fi
+
+  _str=""
+  while [ $_cnt -lt 78 ]; do
+    _str="${_str}."
+    let _cnt=_cnt+1
+  done
+
+  printf " - ${_msg} ${_str}: $_num"
+}
+
+# ------------------------------------------------------------------------------------------
+# Function Name ......: selfTestStep
+# Function Category ..: selfTest - Tanzu Demo Hub automated testing facility for Demos
+# Function Purpose ...: Execute test and print result (sucessed / failed)
+# ------------------------------------------------------------------------------------------
+# Argument ($1) ......: Command to execute (ie. kubectl apply -f /tmp/<file>") .... (string)
+# Return Value .......: abort if ABORT_ON_FAILURE=1 otherwise only report the failed test
+# ------------------------------------------------------------------------------------------
+selfTestStep() {
+  CMD="$1"
+  _msg="$SELF_TEST_NAME"
+  _cnt=$(echo "${_msg}" | wc -c | sed 's/ //g')
+  _dat=$(date "+%Y%m%d-%H:%M:%S")
+
+  _str=""
+  while [ $_cnt -lt 78 ]; do
+    _str="${_str}."
+    let _cnt=_cnt+1
+  done
+
+  #[ $(uname) == "Linux" ] &&
+
+  eval $CMD > /tmp/selffTest.log 2>&1; ret=$?
+
+  _num=$(printf "[%02d/%02d]\n" $_stp $_tot)
+
+  if [ $ret -eq 0 ]; then
+    if [ "${PCF_DEPLOYMENT_DEBUG}" == "true" -o "${DEBUG}" == "1" ]; then
+      if [ $(uname) == "Linux" ]; then
+        printf "1 \e[1m[${_dat}-$HST] ${_msg}\e[0m [%d/%d]", $SELF_TEST_STEP, $SELF_TEST_TOTAL
+      else
+        printf "2 \e[1m[${_dat}-$HST] ${_msg}\e[0m [%d/%d]", $SELF_TEST_STEP, $SELF_TEST_TOTAL
+      fi
+    else
+     #printf "\e[37m${_msg} ${_str}: ${_stt} [%d/%d]\e[0m" $SELF_TEST_STEP $SELF_TEST_TOTAL
+      printf "\b\b\b\b\b\b\b$_num"
+      #printf "$_num"
+
+      #echo "$_num step"
+    fi
+
+    let _stp=_stp+1
+  else
+    if [ "$TDHDEMO_ABORT_ON_FAILURE" -eq 0 ]; then
+      printf "\b\b\b\b\b\b\bcompleted\n"
+    else
+      printf "\n\n"
+      echo "=> $CMD"
+      echo "------------------------------------------------------------------------------"
+      cat /tmp/selffTest.log
+      echo "------------------------------------------------------------------------------"
+      exit
+    fi
+  fi
+
+}
+
+selfTestFine() {
+  printf "\b\b\b\b\b\b\bcompleted\n"
+}
 
 
 
