test

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1061,13 +1061,23 @@ createCluster() {
       export GOVC_NETWORK="$VSPHERE_MANAGEMENT_NETWORK"
       export GOVC_RESOURCE_POOL=/${VSPHERE_DATACENTER}/host/${VSPHERE_CLUSTER}/Resources
 
-      for n in $(govc find -name "$TDH_TKGMC_NAME*"); do
-        messagePrint " - Cleanup local kind Clusters:"  "$n"
-        govc vm.destroy $n
+      nodes=$(govc find -name "$TDH_TKGMC_NAME*" >/dev/null 2>&1)
+      if [ $? != 0 ], then 
+        echo "ERROR: failed to login to vSphere"
+        echo "       => govc find -name \"$TDH_TKGMC_NAME*\""; exit
+      fi
+
+      for n in $nodes; do
+        messagePrint " - Cleanup Old Cluster Nodes"  "$n"
+        govc vm.destroy $n > /dev/null 2>&1
+        if [ $? != 0 ], then 
+          echo "ERROR: failed to login to vSphere"
+          echo "       => govc vm.destroy $n"; exit 
+        fi
       done
 
       for n in $(kind get clusters); do
-        messagePrint " - Cleanup Old Cluster NOdes"  "$n"
+        messagePrint " - Cleanup local kind Clusters:"  "$n"
         kind delete clusters $n > /dev/null 2>&1
       done
 
