testing

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -78,7 +78,6 @@ execCmd() {
   if [ $? -ne 0 ]; then exit 1; fi
 }
 
-#gaga
 tmcCheckLogin() {
   [ "${TDH_TANZU_MISSION_CONTROL_REGISTRATION}" == "false" ] && return
   missing_variables=0
@@ -987,7 +986,6 @@ checkCloudAccess() {
   fi
 }
 
-#gaga
 checkTDHenvironment() {
   missing_variables=0
 
@@ -1754,7 +1752,6 @@ route53createHostedZone() {
 
 route53setNSrecord () {
   hnm=$1; dom=$2; dns="$3"
-echo "gaga HNM:$hnm"
 
   ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name ${dom} | jq -r ".HostedZones[] | select(.Name | \
             scan(\"^$dom.\")).Id")
@@ -1974,7 +1971,52 @@ echo "VSPHERE_TKGM_SSH_PUBLIC_KEY_FILE:$VSPHERE_TKGM_SSH_PUBLIC_KEY_FILE"
 
 echo "TKG_TEMPLATE:$TKG_TEMPLATE"
 
-exit
+    cnt=$(tanzu management-cluster get 2>/dev/null | egrep -c " $TDH_TKGMC_NAME ")
+    if [ ${cnt} -eq 0 ]; then
+      # --- CLEAN OLD MANAGEMENT CLUSTER CONFIG ---
+      rm -f ~/.tanzu/config.yaml /tmp/$TDH_TKGMC_NAME.log
+
+      messagePrint " ▪ Management Cluster Creating"        "This may take up to 15min ..."
+
+      if [ $DEBUG -gt 0 ]; then
+        echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
+        tanzu management-cluster create --file $TKG_TEMPLATE -v 0 --log-file=/tmp/$TDH_TKGMC_NAME.log; ret=$?
+        echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
+      else
+        #tanzu management-cluster create --file $TKG_TEMPLATE -v 0 --log-file=/tmp/$TDH_TKGMC_NAME.log > /dev/null 2>&1; ret=$?
+echo "tanzu management-cluster create --file $TKG_TEMPLATE -v 0 --log-file=/tmp/$TDH_TKGMC_NAME.log"
+        tanzu management-cluster create --file $TKG_TEMPLATE -v 0 --log-file=/tmp/$TDH_TKGMC_NAME.log
+      fi
+
+      if [ ${ret} -ne 0 ]; then
+        echo "ERROR: failed to create TKG Management Cluster"
+        echo "       => tanzu management-cluster create --file $TKG_TEMPLATE -v 0 --log-file=/tmp/$TDH_TKGMC_NAME.log"
+        echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
+        cat /tmp/$TDH_TKGMC_NAME.log
+        echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
+
+        exit 1
+      fi
+
+      messagePrint " ▪ Management Cluster Creating Completed"    "/tmp/$TDH_TKGMC_NAME.log"
+
+      tanzu management-cluster kubeconfig get --admin > /dev/null 2>&1
+      kubectl config set-cluster $TDH_TKGMC_NAME > /dev/null 2>&1
+      kubectl config use-context ${TDH_TKGMC_NAME}-admin@$TDH_TKGMC_NAME > /dev/null 2>&1
+      context=$(kubectl config view -o json | jq -r '.contexts[].name' 2>/dev/null)
+      tanzu management-cluster kubeconfig get --admin --export-file=${TKG_KUBECONFIG} > /dev/null 2>&1; ret=$?
+      if [ $ret -ne 0 ]; then
+        echo "ERROR: failed to generate kubeconfig:"
+        echo "       => tanzu management-cluster kubeconfig get --admin --export-file=${TKG_KUBECONFIG}"
+        messageLine
+        tanzu management-cluster kubeconfig get --admin --export-file=${TKG_KUBECONFIG}
+        messageLine
+        exit
+      fi
+    fi
+#gaga
+
+exit 1
   fi
 
   if [ "${TDH_TKGMC_INFRASTRUCTURE}" == "AWS" ]; then
@@ -4397,8 +4439,6 @@ InstallContour() {
       exit
     fi
 
-echo "gaga3 IPA:$ipa"
-echo "setDNSalias \"$ipa\" \"${TDH_ENVNAME}\" \"${AWS_HOSTED_DNS_DOMAIN}\" \"*.apps-contour\" \"A\""
     setDNSalias "$ipa" "${TDH_ENVNAME}" "${AWS_HOSTED_DNS_DOMAIN}" "*.apps-contour" "A"
   fi
 
