changed messages on installing

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1308,15 +1308,8 @@ configureLDAP() {
     messageTitle "Configure LDAP Server"        
     messagePrint " - Install LDAP Server"       "jump.${TDH_TKGMC_ENVNAME}.${AWS_HOSTED_DNS_DOMAIN}"
     messagePrint " - Install LDAP Management"   "phpLDAPadmin"
-    if [ $DEBUG -gt 0 ]; then
-      echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
-      $SSH_COMMAND -n "[ -d $SSH_HOME/tanzu-demo-hub ] && chmod a+x ${TDHHOME}/scripts/InstallOpenLDAP.sh && \
-          sudo ${TDHHOME}/scripts/InstallOpenLDAP.sh \"${TDH_TKGMC_ENVNAME}.${AWS_HOSTED_DNS_DOMAIN}\""; ret=$?
-      echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
-    else
-      $SSH_COMMAND -n "[ -d $SSH_HOME/tanzu-demo-hub ] && chmod a+x ${TDHHOME}/scripts/InstallOpenLDAP.sh && \
-        sudo ${TDHHOME}/scripts/InstallOpenLDAP.sh \"${TDH_TKGMC_ENVNAME}.${AWS_HOSTED_DNS_DOMAIN}\" > /dev/null 2>&1"; ret=$?
-    fi
+    $SSH_COMMAND -n "[ -d $SSH_HOME/tanzu-demo-hub ] && chmod a+x ${TDHHOME}/scripts/InstallOpenLDAP.sh && \
+        sudo ${TDHHOME}/scripts/InstallOpenLDAP.sh \"${TDH_TKGMC_ENVNAME}.${AWS_HOSTED_DNS_DOMAIN}\" $DEBUG"; ret=$?
 
     if [ ${ret} -ne 0 ]; then
       echo "ERROR: Failed to install CLI Utilities (InstallUtilities.sh)"
@@ -1366,15 +1359,8 @@ configureJumpHost() {
   stt=$($SSH_COMMAND -n "[ -f /jump_software_installed ] && echo true")
   if [ "${stt}" == "" ]; then
     messagePrint " - Install CLI Utilities"   "aws,az,gcp,bosh,pivnet,cf,om,jq"
-    if [ $DEBUG -gt 0 ]; then
-      echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
-      $SSH_COMMAND -n "[ -d $SSH_HOME/tanzu-demo-hub ] && chmod a+x ${TDHHOME}/scripts/InstallUtilities.sh && \
-          sudo ${TDHHOME}/scripts/InstallUtilities.sh $PCF_PIVNET_TOKEN"; ret=$?
-      echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
-    else
-      $SSH_COMMAND -n "[ -d $SSH_HOME/tanzu-demo-hub ] && chmod a+x ${TDHHOME}/scripts/InstallUtilities.sh && \
-          sudo ${TDHHOME}/scripts/InstallUtilities.sh $PCF_PIVNET_TOKEN > /dev/null 2>&1"; ret=$?
-    fi
+    $SSH_COMMAND -n "[ -d $SSH_HOME/tanzu-demo-hub ] && chmod a+x ${TDHHOME}/scripts/InstallUtilities.sh && \
+        sudo ${TDHHOME}/scripts/InstallUtilities.sh $PCF_PIVNET_TOKEN $DEBUG"; ret=$?
 
     if [ ${ret} -ne 0 ]; then
       echo "ERROR: Failed to install CLI Utilities (InstallUtilities.sh)"
@@ -1409,15 +1395,8 @@ configureJumpHost() {
   stt=$($SSH_COMMAND -n "[ -f /tkg_software_installed ] && echo true")
   if [ "${stt}" == "" ]; then
     messagePrint " - Install TKG Utilities"   "tkg, ytt, kapp, kbld, kubectl, kind"
-    if [ $DEBUG -gt 0 ]; then
-      echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
-      $SSH_COMMAND -n "[ -d $SSH_HOME/tanzu-demo-hub ] && chmod a+x ${TDHHOME}/scripts/InstallTKGutilities.sh && \
-          sudo ${TDHHOME}/scripts/InstallTKGutilities.sh \"$SSH_HOME/tanzu-demo-hub\""; ret=$?
-      echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
-    else
-      $SSH_COMMAND -n "[ -d $SSH_HOME/tanzu-demo-hub ] && chmod a+x ${TDHHOME}/scripts/InstallTKGutilities.sh && \
-          sudo ${TDHHOME}/scripts/InstallTKGutilities.sh \"$SSH_HOME/tanzu-demo-hub\" > /dev/null 2>&1"; ret=$?
-    fi
+    $SSH_COMMAND -n "[ -d $SSH_HOME/tanzu-demo-hub ] && chmod a+x ${TDHHOME}/scripts/InstallTKGutilities.sh && \
+        sudo ${TDHHOME}/scripts/InstallTKGutilities.sh \"$SSH_HOME/tanzu-demo-hub\" \"$TDH_TKGMC_INFRASTRUCTURE\" $DEBUG"; ret=$?
 
     if [ ${ret} -ne 0 ]; then
       echo "ERROR: Failed to install TKG Utilities (InstallTKGutilities.sh)"
@@ -4729,6 +4708,49 @@ cleanManagementCluster() {
   done
 }
 
+installSnap() {
+  PKG=$1
+  OPT=$2
+
+  snap list $PKG > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    messagePrint " - Install Package ($PKG)" "installing"
+    cnt=0
+    snap install $PKG $OPT > /dev/null 2>&1; ret=$?
+    while [ $ret -ne 0 -a $cnt -lt 3 ]; do
+      snap install $PKG $OPT> /dev/null 2>&1; ret=$?
+      sleep 30
+      let cnt=cnt+1
+    done
+
+    if [ $ret -ne 0 ]; then
+      echo "ERROR: failed to install package $PKG"
+      echo "       => snap install $PKG $PKG"
+      exit 1
+    fi
+  else
+    ver=$(snap info $PKG | grep "installed:" | awk '{ print $2 }')
+    messagePrint " - Install Package ($PKG)" "$ver"
+  fi
+}
+
+installPackage() {
+  PKG=$1
+
+  messagePrint " - Install Package ($PKG)" "installing"
+  dpkg -s $PKG > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    apt install $PKG -y > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+      echo "ERROR: failed to install package $PKG"
+      echo "       => apt install $PKG -y"
+      exit 1
+    fi
+  else
+    ver=$(dpkg -s $PKG | grep "Version" | sed 's/^Version: //g') 
+    messagePrint " - Verify Package ($PKG)" "$ver"
+  fi
+}
 
 
 
