testing

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1017,6 +1017,20 @@ setTKGclusterDNS() {
   fi
 }
 
+verifyTLScertificate() {
+  TLS_CERTIFICATE=$1
+  TLS_PRIVATE_KEY=$2
+
+  dif=$((openssl x509 -in $TLS_CERTIFICATE -noout -modulus; openssl rsa -in $TLS_PRIVATE_KEY -noout -modulus) | \
+      uniq -c | awk '{ print $1 }')
+  if [ "$dif" == "" ]; then dif=0; fi
+  if [ $dif -ne 2 ]; then
+    echo "ERROR: Certificate modulus of $TLS_CERTIFICATE does not match with the private_key $TLS_PRIVATE_KEY"
+    echo "       => openssl x509 -in $TLS_CERTIFICATE -noout -modulus"
+    echo "       => openssl rsa -in $TLS_PRIVATE_KEY -noout -modulus"
+    exit 1
+  fi
+}
 
 
 
