testing

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -53,6 +53,29 @@ messageTitle() {
   fi
 }
 
+pivnetAPIdownload() {
+  REFRESH_TOKEN="$1"
+  PRODUCT_SLUG="$2"
+  PRODUCT_ID=$3
+  PRODUCT_FILE=$4
+  FILE_NAME="$5"
+
+  token=$(curl -X POST https://network.pivotal.io/api/v2/authentication/access_tokens \
+               -d "{\"refresh_token\":\"$REFRESH_TOKEN\"}" 2>/dev/null | jq -r '.access_token')
+  if [ "${token}" == "" -o "${token}" == "null" ]; then return 1; fi
+
+  # --- LOGIN INTO PIVNET ---
+  wget -O /tmp/$FILE_NAME --header="Authorization: Bearer $token" \
+  https://network.pivotal.io/api/v2/products/$PRODUCT_SLUG/releases/$PRODUCT_ID/product_files/$PRODUCT_FILE/download > /dev/null 2>&1
+
+  if [ ! -f /tmp/$FILE_NAME ]; then
+    echo "ERROR: Error downloading file from PIVNET /tmp/$FILE_NAME"
+  fi
+
+  return 0
+}
+
+
 messagePrint() {
   _msg="$1"
   _stt="$2"
@@ -2013,16 +2036,17 @@ installBuildService() {
     return
   fi
 
-  messageTitle "Installing Tanzu Build Service"
-
-  cnt=$(ls -1 $TDHPATH/software/build-service-*.tar 2>/dev/null | wc -l | sed 's/  //g') 
-  if [ $cnt -eq 0 ]; then 
-    echo "ERROR: Download build-service-*.tar from https://network.pivotal.io/products/build-service and store it under"
-    echo "       => $TDHPATH/software"
+  if [ "$TDH_SERVICE_BUILD_SERVICE_VERSION" == "" ]; then
+    echo "ERROR: Envuronment Variable (TDH_SERVICE_BUILD_SERVICE_VERSION) not found in"
+    echo "       in the deployment file: ${TDHPATH}/deployments/${K8S_DEPLOYMENT}"
     exit
   fi
 
-  TBS_FILE=$(ls -1tr $TDHPATH/software/build-service-*.tar | tail -1)
+  # --- DOWNLOAD BUILD_SERVICE BINARIES ---
+  downloadFromPivnet build-service $TDH_SERVICE_BUILD_SERVICE_VERSION
+
+  messageTitle "Installing Tanzu Build Service"
+  TBS_FILE="/tmp/build-service-$TDH_SERVICE_BUILD_SERVICE_VERSION.tar"
   [ -d /tmp/build-service ] && rm -rf /tmp/build-service
   mkdir /tmp/build-service
   tar xf $TBS_FILE -C /tmp/build-service
@@ -2098,18 +2122,60 @@ installBuildService() {
     echo "-----------------------------------------------------------------------------------------------------------"
   fi
 
-  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_VMWARE_NAME       $TDH_REGISTRY_VMWARE_NAME
-  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_VMWARE_USER       $TDH_REGISTRY_VMWARE_USER
-  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_VMWARE_PASS       $TDH_REGISTRY_VMWARE_PASS
-  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_NAME       $TDH_REGISTRY_DOCKER_NAME
-  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_USER       $TDH_REGISTRY_DOCKER_USER
-  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_PASS       $TDH_REGISTRY_DOCKER_PASS
-  uodateConfigMap tanzu-demo-hub TDH_GITHUB_USER                $TDH_GITHUB_USER
-  uodateConfigMap tanzu-demo-hub TDH_GITHUB_PASS                $TDH_GITHUB_PASS
-
-
+  uodateConfigMap tanzu-demo-hub TDH_SERVICE_BUILD_SERVICE_VERSION  $TDH_SERVICE_BUILD_SERVICE_VERSION
+  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_VMWARE_NAME           $TDH_REGISTRY_VMWARE_NAME
+  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_VMWARE_USER           $TDH_REGISTRY_VMWARE_USER
+  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_VMWARE_PASS           $TDH_REGISTRY_VMWARE_PASS
+  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_NAME           $TDH_REGISTRY_DOCKER_NAME
+  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_USER           $TDH_REGISTRY_DOCKER_USER
+  uodateConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_PASS           $TDH_REGISTRY_DOCKER_PASS
+  uodateConfigMap tanzu-demo-hub TDH_GITHUB_USER                    $TDH_GITHUB_USER
+  uodateConfigMap tanzu-demo-hub TDH_GITHUB_PASS                    $TDH_GITHUB_PASS
 }
 
+downloadFromPivnet() {
+  PRODUCT_SLUG=$1
+  SLUG_VER=$2
+
+  for pid in $(pivnetAPI $PCF_PIVNET_TOKEN GET products/$PRODUCT_SLUG/releases 2> /dev/null | \
+             jq -r ".releases[] | select(.version | scan(\"^$SLUG_VER\")).id"); do
+    fid=$(pivnetAPI $PCF_PIVNET_TOKEN GET products/$PRODUCT_SLUG/releases/$pid 2>/dev/null | \
+          jq -r ".product_files[] | select(.name | scan(\"^$SLUG_STR\")) | select(.file_version | scan(\"$SLUG_VER\")).id")
+
+    if [ "${fid}" != "" ]; then
+      # --- ACCEPT EULA ---
+      pivnetAPI $PCF_PIVNET_TOKEN POST products/$PRODUCT_SLUG/releases/$pid/eula_acceptance > /dev/null 2>&1
+      break
+    else
+      echo "ERROR: Unable to find $PRODUCT_SLUG $2 on Pivnet"
+      exit 1
+    fi
+  done
+
+  if [ "$fid" == "" ]; then 
+    echo "ERROR: Can not find version: $SLUG_VER from ($PRODUCT_SLUG) on PIVNET"
+    exit
+  fi
+
+  file=$(pivnetAPI $PCF_PIVNET_TOKEN GET products/$PRODUCT_SLUG/releases/$pid 2>/dev/null | \
+       jq -r ".product_files[] | select(.id | tostring | scan(\"^$fid$\")).aws_object_key" | \
+       awk -F'/' '{ print $NF }')
+
+  if [ ! -f /tmp/$file ]; then
+    messageTitle "Download (äPRODUCT_SLUG) from PIVNET"
+    messagePrint " - Product Name:" "$PRODUCT_SLUG"
+    messagePrint " - Product Slug:" "$SLUG_VER"
+    messagePrint " - Product FileID:" "$fid"
+    messagePrint " - Download Location:" "/tmp/$file"
+    pivnetAPIdownload $PCF_PIVNET_TOKEN $PRODUCT_SLUG $pid $fid $file
+  else
+    messageTitle "Verify PIVNET Download (äPRODUCT_SLUG)"
+    messagePrint " - Product Name:" "$PRODUCT_SLUG"
+    messagePrint " - Product Slug:" "$SLUG_VER"
+    messagePrint " - Product FileID:" "$fid"
+    messagePrint " - Download Location:" "/tmp/$file"
+  fi
+}
 
 
 
