copy /Users/sdu/.tanzu-demo-hub/cache directory to jump server

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -4706,23 +4706,26 @@ tkgCreateCluster() {
     [ "$TDH_DEPLOYMENT_CLUSTER_PLAN" == "dev" ] && DEP_SOURCE=$HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.yaml
     [ "$TDH_DEPLOYMENT_CLUSTER_PLAN" == "prod" ] && DEP_SOURCE=$HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.yaml
 
+    # --- GET NODE TYPES ---
+    TDH_TKGWC_WORKERNODES_MACHINE=$(nodeType $TDH_TKGWC_WORKERNODES_TYPE)
+    TDH_TKGWC_CONTROPLANE_MACHINE=$(nodeType $TDH_TKGWC_CONTROPLANE_NODETYPE)
+
+    # --- GENERATE WORKLOAD CLUSTER CONFIG FILE ---
+    CLUSTER_CONFIG_FILE=$HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml
+
+    # --- SET DEFAULT VALUES ---
+    [ "$TDH_TKGWC_CONTROPLANE_MACHINE" == "" ] && TDH_TKGWC_CONTROPLANE_MACHINE=Standard_D4s_v3
+    [ "$TDH_TKGWC_WORKERNODES_MACHINE" == "" ] && TDH_TKGWC_WORKERNODES_MACHINE=Standard_D4s_v3
+
+    # --- GET KUBERNETES VERSION ---
+    TDH_TKGWC_K8S_VERSION=$(tanzu kubernetes-release get | egrep "$TDH_TKGWC_KUBERNETES" | tail -1 | awk '{ print $1 }')
+
     messagePrint " ▪ Kubernetes Version"               "$TDH_TKGWC_KUBERNETES"
     messagePrint " ▪ Kubernetes Image"                 "$TDH_TKGWC_K8S_VERSION"
     messagePrint " ▪ TKG Cluster Worker Nodes"         "$TDH_TKGWC_WORKERNODES"
     messagePrint " ▪ TKG Cluster Worker Node Type"     "$TDH_TKGWC_WORKERNODES_TYPE ($TDH_TKGWC_WORKERNODES_MACHINE)"
     messagePrint " ▪ TKG Control Plane Nodes"          "$TDH_TKGWC_CONTROPLANE"
     messagePrint " ▪ TKG Control Plane Nodes Type"     "$TDH_TKGWC_CONTROPLANE_NODETYPE ($TDH_TKGWC_CONTROPLANE_MACHINE)"
-
-    # --- GENERATE WORKLOAD CLUSTER CONFIG FILE ---
-    CLUSTER_CONFIG_FILE=$HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml
-
-   # --- GET NODE TYPES ---
-    TDH_TKGWC_WORKERNODES_MACHINE=$(nodeType $TDH_TKGWC_WORKERNODES_TYPE)
-    TDH_TKGWC_CONTROPLANE_MACHINE=$(nodeType $TDH_TKGWC_CONTROPLANE_NODETYPE)
-
-    # --- SET DEFAULT VALUES ---
-    [ "$TDH_TKGWC_CONTROPLANE_MACHINE" == "" ] && TDH_TKGWC_CONTROPLANE_MACHINE=Standard_D4s_v3
-    [ "$TDH_TKGWC_WORKERNODES_MACHINE" == "" ] && TDH_TKGWC_WORKERNODES_MACHINE=Standard_D4s_v3
 
     str="AZURE_SUBSCRIPTION_ID|AZURE_TENANT_ID|AZURE_CLIENT_ID|AZURE_CLIENT_SECRET|AZURE_LOCATION|AZURE_SSH_PUBLIC_KEY_B64|CLUSTER_PLAN"
     egrep "$str" $DEP_SOURCE                                                        >  $CLUSTER_CONFIG_FILE
@@ -4760,8 +4763,20 @@ tkgCreateCluster() {
     if [ $ret -ne 0 ]; then
       echo "-----------------------------------------------------------------------------------------------------------"
       echo "=> tanzu cluster create $TDH_TKGWC_NAME -f $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml --tkr $TDH_TKGWC_K8S_VERSION"
-      tanzu cluster create $TDH_TKGWC_NAME -f $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml --tkr $TDH_TKGWC_K8S_VERSION
+      tanzu cluster create $TDH_TKGWC_NAME -f $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml --tkr $TDH_TKGWC_K8S_VERSION; ret=$?
       echo "-----------------------------------------------------------------------------------------------------------"
+
+      if [ $ret -ne 0 ]; then
+        echo "ERROR: failed to create TKG Workload Cluster"
+        if [ "$NATIVE" == "0" ]; then
+          echo "       => tools/${TDH_TOOLS}.sh"
+          echo "          tdh-tools:/$ tanzu cluster create $TDH_TKGWC_NAME -f $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml --tkr $TDH_TKGWC_K8S_VERSION"
+          echo "          tdh-tools:/$ exit"
+        else
+          echo "       => tanzu cluster create $TDH_TKGWC_NAME -f $HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.yaml --tkr $TDH_TKGWC_K8S_VERSION"
+        fi
+        exit 1
+      fi
     
       #dockerPullImages="projects.registry.vmware.com/tkg/antrea/antrea-debian:v0.13.3_vmware.1 \
       #                  projects.registry.vmware.com/tkg/tanzu_core/capabilities/capabilities-controller-manager:v1.4.1"
@@ -5084,7 +5099,6 @@ echo hallo
     export KUBECONFIG=$HOME/.tanzu-demo-hub/config/${TDH_TKGWC_NAME}.kubeconfig
     kubectl apply -f $TDHPATH/files/psp/vmware-system-privileged.yaml > /dev/null 2>&1
   fi
-
 }
 
 vsphereSupervisorClusterLogin() {
@@ -6746,22 +6760,18 @@ installGitLab() {
       exit 1
     fi
 
-echo gaga1
     # PATCH DOCKER PULL SECRET
     dockerPullSecret gitlab gitlab-certmanager-issuer 
     dockerPullSecret gitlab gitlab-gitlab-runner 
     dockerPullSecret gitlab gitlab-nginx-ingress
     dockerPullSecret gitlab gitlab-nginx-ingress-backend
     dockerPullSecret gitlab gitlab-prometheus-server
-echo gaga2
 
     cmdLoop kubectl -n gitlab rollout restart deployment gitlab-gitlab-runner > /dev/null 2>&1
     cmdLoop kubectl -n gitlab rollout restart deployment gitlab-prometheus-server > /dev/null 2>&1
-echo gaga3
 
     # --- WAIT FOR PODS TO GET STARTED ---
     runningPods $NAMESPACE
-echo gaga4
   fi
 
   cmdLoop helm ls -n $NAMESPACE -o json > /tmp/output.json
