improoving tdh-tools

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -7814,6 +7814,7 @@ cleanKindCluster() {
   fi
 }
 
+#hallo
 runTDHtoolsDemos() {
   if [ ! -f /tdh_tools_docker_container  ]; then
     if [ $NATIVE -eq 0 ]; then
@@ -8577,6 +8578,7 @@ secInSec() {
   date "+%S" | sed 's/^0//g'
 }
 
+#hallo
 dockerRunPreparation() {
   TDH_TOOLS=$1
   TDH_TOOLS_PATH=".${TDH_TOOLS}"
@@ -8622,4 +8624,100 @@ dockerRunPreparation() {
     [ -d $localdir -a -d $localdir ] && mkdir -p $localdir
   done
 } 
+
+# ------------------------------------------------------------------------------------------
+# Function Name ......: runTDHtools
+# Function Purpose ...: Install Contour Ingress Controller
+# ------------------------------------------------------------------------------------------
+# Argument ($1) ......: TDH Tools Flag (TCE/TCE)
+#          ($2) ......: Header Text to be shown on start
+#          ($3) ......: Commandline PATH and Command to be executed by docker
+#          ($4) ......: Commandline Arguments
+# ------------------------------------------------------------------------------------------
+# Return Value .......: 0 on Success, 1 on failure
+# ------------------------------------------------------------------------------------------
+runTDHtools() {
+  TOOLS_TLAG="$1"
+  HEADER_TEXT="$2"
+  DOCKER_EXEC="$3"
+  DOCKER_ARGS="$4"
+
+  [ "$TOOLS_TLAG" == "tce" -o "$TOOLS_TLAG" == "TCE" ] && TDH_TOOLS=tdh-tools-tce || TDH_TOOLS=tdh-tools
+  TDH_TOOLS_PATH=".${TDH_TOOLS}"
+
+  if [ ! -f /tdh_tools_docker_container  ]; then
+    tdhHeader "$HEADER_TEXT"
+
+    # --- VERIFY TOOLS AND ACCESS ---
+    verify_docker
+    checkCLIcommands        BASIC
+    checkKubernetesServices registry_docker
+
+    if [ $NATIVE -eq 0 ]; then
+      tdh_tools_build tce
+      messagePrint " ▪ Running TDH Tools Docker Container" "tdh-tools-tce:latest $TDHPATH/$CMD_EXEC $CMD_ARGS"
+
+      cid=$(docker ps -a | grep tdh-tools:latest | awk '{ print $1 }')
+      [ "$cid" != "" ] && for n in $cid; do docker rm $n -f > /dev/null 2>&1; done
+
+      # --- DUMP ENVIRONMENT VARIABLES ---
+      env | grep TDH > /tmp/tdh.env
+
+      export CORE_OPTIONS="-it --init --rm --hostname tdh-tools --name $TDH_TOOLS --network=host"
+      export USER_OPTIONS="$CORE_OPTIONS -u $(id -u):$(id -g) --env-file /tmp/tdh.env -e \"KUBECONFIG=$HOME/.kube/config\""
+      export ROOT_OPTIONS="$CORE_OPTIONS --env-file /tmp/tdh.env -e \"KUBECONFIG=$HOME/.kube/config\""
+
+      export CORE_MOUNTS=(
+               "-v /var/run/docker.sock:/var/run/docker.sock"                           ## REQIORED FOR DOCKER
+               "-v $HOME/.tanzu-demo-hub:$HOME/.tanzu-demo-hub:rw"
+               "-v $HOME/.tanzu-demo-hub.cfg:$HOME/.tanzu-demo-hub.cfg:ro"
+               "-v $HOME/$TDH_TOOLS_PATH/.cache:$HOME/.cache:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.config:$HOME/.config:rw"                      ## CONFIG FOR HELM AND TANZU
+               "-v $HOME/$TDH_TOOLS_PATH/.kube:$HOME/.kube:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.kube-tkg:$HOME/.kube-tkg:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.local:$HOME/.local:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.tanzu:$HOME/.tanzu:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.terraform:$HOME/.terraform:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.terraform.d:$HOME/.terraform.d:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.s3cfg:$HOME/.s3cfg:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.govmomi:$HOME/.govmomi:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.gradle:$HOME/.gradle:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.docker:$HOME/.docker:rw"                      ## DOCKER LOGIN CREDENTIALS
+               "-v $HOME/$TDH_TOOLS_PATH/.mvn:$HOME/.mvn:rw"
+               "-v $HOME/$TDH_TOOLS_PATH/.aws:$HOME/.aws:rw"                            ## PERSISTANT AWS CREDENTIALS
+               "-v $HOME/$TDH_TOOLS_PATH/.vmware-cna-saas:$HOME/.vmware-cna-saas:rw"    ## TANZU MISSION CONTROL (TMC) LOGIN CREDENTIALS
+               "-v $HOME/$TDH_TOOLS_PATH/tmp:/tmp:rw"                                   ## KEEP TEMP PERSISTENT
+               "-v $TDHPATH/:$TDHPATH:ro"                                               ## TANZU-DEMO-HUB DIRECTORY
+             )
+
+      # --- MAKE SURE DIRECTORIES ARE CREATED ---
+      for n in $(echo ${CORE_MOUNTS[*]} | sed 's/\-. //g'); do
+        [ $n == "/var/run/docker.sock" ] && continue
+        localdir=$(echo $n | awk -F: '{ print $1 }')
+        [ -d $localdir -a -d $localdir ] && mkdir -p $localdir
+      done
+
+      docker run $ROOT_OPTIONS ${CORE_MOUNTS[*]} tdh-tools:latest chmod 666 /var/run/docker.sock > /dev/null 2>&1
+      docker run $USER_OPTIONS ${CORE_MOUNTS[*]} tdh-tools:latest /usr/local/bin/tdh-postinstall-user-tce.sh > /dev/null 2>&1
+      docker run $USER_OPTIONS ${CORE_MOUNTS[*]} tdh-tools:latest $DOCKER_EXEC $DOCKER_ARGS; ret=$?
+
+      # --- FINISH CURRENT SESSION AS WE RUN AS CONTAINER ---
+      exit $ret
+    fi
+  else
+    # trap ctrl-c and call ctrl_c()
+    #trap ctrl_c INT
+
+    cd $TDHDEMO
+  fi
+}
+
+tdhHeader() {
+  TEXT=$1
+  echo ""
+  echo "Tanzu Demo Hub - $TEXT"
+  echo "by Sacha Dubois, VMware Inc,"
+  messageLine
+}
+
 
