testing

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -4899,7 +4899,7 @@ installMinio() {
 
     cnt=0; ret=1
     while [ $ret -ne 0 -a $cnt -lt 5 ]; do
-      helm install kubeapps --namespace $NAMESPACE bitnami/kubeapps -f $HELM_VALUES --version $HELM_KUBEAPPS_VERSION > /tmp/error.log 2>&1; ret=$?
+      helm install tdh-minio bitnami/minio -f ${HELM_VALUES} > /tmp/error.log 2>&1; ret=$?
       [ $ret -eq 0 ] && break
       let cnt=cnt+1
       sleep 30
@@ -5284,20 +5284,58 @@ installBuildService() {
         echo "       => docker login $TDH_REGISTRY_DOCKER_NAME -u $TDH_REGISTRY_DOCKER_USER -p $TDH_REGISTRY_DOCKER_PASS"; exit 1
       fi
   
+      echo gaga1
       messagePrint " ▪ Relocate images to" "$TDH_REGISTRY_DOCKER_NAME/$TDH_REGISTRY_DOCKER_USER/build-service"
-      imgpkg copy -b "registry.pivotal.io/build-service/bundle:$TDH_SERVICE_BUILD_SERVICE_VERSION" --to-repo $TDH_REGISTRY_DOCKER_USER/build-service > /dev/null 2>&1
-      if [ $? -ne 0 ]; then
+      cnt=0; ret=1
+      while [ $ret -ne 0 -a $cnt -lt 5 ]; do
+	imgpkg copy -b "registry.pivotal.io/build-service/bundle:$TDH_SERVICE_BUILD_SERVICE_VERSION" \
+		    --to-repo $TDH_REGISTRY_DOCKER_USER/build-service > /tmp/error.log 2>&1; ret=$?
+        [ $ret -eq 0 ] && break
+        let cnt=cnt+1
+        sleep 30
+      done
+      echo "gaga2 ret:$ret"
+
+      if [ $ret -ne 0 ]; then
+        logMessages /tmp/error.log
         echo "ERROR: Image Relocation failed"
-        echo "       => imgpkg copy -b registry.pivotal.io/build-service/bundle:$TDH_SERVICE_BUILD_SERVICE_VERSION \\"
-        echo "          --to-repo $TDH_REGISTRY_DOCKER_USER/build-service"; exit 1
+        if [ "$NATIVE" == "0" ]; then
+          echo "       => tools/${TDH_TOOLS}.sh"
+          echo "          tdh-tools:/$ imgpkg copy -b registry.pivotal.io/build-service/bundle:$TDH_SERVICE_BUILD_SERVICE_VERSION \\"
+	  echo "                                   --to-repo $TDH_REGISTRY_DOCKER_USER/build-service"; exit 1
+          echo "          tdh-tools:/$ exit"
+        else
+          echo "       => imgpkg copy -b registry.pivotal.io/build-service/bundle:$TDH_SERVICE_BUILD_SERVICE_VERSION \\"
+          echo "          --to-repo $TDH_REGISTRY_DOCKER_USER/build-service"; exit 1
+        fi
+
+        exit 1
       fi
 
+      echo gaga3
       messagePrint " ▪ Pull the Tanzu Build Service bundle image locally" "$TDH_REGISTRY_VMWARE_NAME/library/build-service"
       rm -rf /tmp/bundle
-      imgpkg pull -b "$TDH_REGISTRY_DOCKER_USER/build-service:$TDH_SERVICE_BUILD_SERVICE_VERSION" -o /tmp/bundle > /dev/null 2>&1; ret=$?
+      cnt=0; ret=1
+      while [ $ret -ne 0 -a $cnt -lt 5 ]; do
+	imgpkg pull -b "$TDH_REGISTRY_DOCKER_USER/build-service:$TDH_SERVICE_BUILD_SERVICE_VERSION" -o /tmp/bundle > /tmp/error.log 2>&1; ret=$?
+        [ $ret -eq 0 ] && break
+        let cnt=cnt+1
+        sleep 30
+      done
+
+      echo "gaga4 ret:$ret"
       if [ $ret -ne 0 ]; then
+        logMessages /tmp/error.log
         echo "ERROR: Image Relocation failed"
-        echo "       => imgpkg pull -b \"$TDH_REGISTRY_DOCKER_USER/build-service\" -o /tmp/bundle"
+        if [ "$NATIVE" == "0" ]; then
+          echo "       => tools/${TDH_TOOLS}.sh"
+          echo "          tdh-tools:/$ imgpkg pull -b \"$TDH_REGISTRY_DOCKER_USER/build-service\" -o /tmp/bundle"
+          echo "          tdh-tools:/$ exit"
+        else
+          echo "       => imgpkg pull -b \"$TDH_REGISTRY_DOCKER_USER/build-service\" -o /tmp/bundle"
+        fi
+
+        exit 1
       fi
 
       # --- DEPLOY KAPP ---
@@ -7395,7 +7433,7 @@ tdh_tools_build() {
 
   if [ ! -x $TDH_DOCKER_FILES/kbld ]; then
     # --- DOWNLOAD BUILD_SERVICE BINARIES ---
-    downloadFromPivnet kbld $TDH_CARVEL_KBLD "$TDH_CARVEL_KBLD" "kbld-linux-arm64"
+    downloadFromPivnet kbld $TDH_CARVEL_KBLD "$TDH_CARVEL_KBLD" "kbld - Linux"
     [ -f /tmp/kbld-linux-arm64-$TDH_CARVEL_KBLD ] && mv /tmp/kbld-linux-arm64-$TDH_CARVEL_KBLD $TDH_DOCKER_FILES/kbld && chmod a+x $TDH_DOCKER_FILES/kbld
 
     REBUILD_REQUIRED_SOFTWARE=1       ## REBUILD REQUIRED BECAUSE OF SOFTWARE CHANGE
@@ -7411,7 +7449,7 @@ tdh_tools_build() {
 
   if [ ! -x $TDH_DOCKER_FILES/kapp ]; then
     # --- DOWNLOAD BUILD_SERVICE BINARIES ---
-    downloadFromPivnet kapp $TDH_CARVEL_KAPP "$TDH_CARVEL_KAPP" "kapp-linux-arm64"
+    downloadFromPivnet kapp $TDH_CARVEL_KAPP "$TDH_CARVEL_KAPP" "kapp - Linux"
     [ -f /tmp/kapp-linux-arm64-$TDH_CARVEL_KAPP ] && mv /tmp/kapp-linux-arm64-$TDH_CARVEL_KAPP $TDH_DOCKER_FILES/kapp && chmod a+x $TDH_DOCKER_FILES/kapp
 
     REBUILD_REQUIRED_SOFTWARE=1       ## REBUILD REQUIRED BECAUSE OF SOFTWARE CHANGE
@@ -7419,7 +7457,7 @@ tdh_tools_build() {
 
   if [ ! -x $TDH_DOCKER_FILES/ytt ]; then
     # --- DOWNLOAD BUILD_SERVICE BINARIES ---
-    downloadFromPivnet ytt $TDH_CARVEL_YTT "$TDH_CARVEL_YTT" "ytt-linux-arm64"
+    downloadFromPivnet ytt $TDH_CARVEL_YTT "$TDH_CARVEL_YTT" "ytt - Linux"
     [ -f /tmp/ytt-linux-arm64-$TDH_CARVEL_YTT ] && mv /tmp/ytt-linux-arm64-$TDH_CARVEL_YTT $TDH_DOCKER_FILES/ytt && chmod a+x $TDH_DOCKER_FILES/ytt
 
     REBUILD_REQUIRED_SOFTWARE=1       ## REBUILD REQUIRED BECAUSE OF SOFTWARE CHANGE
@@ -7447,9 +7485,9 @@ tdh_tools_build() {
   if [ ! -s $TDH_DOCKER_FILES/terraform-bin ]; then
     #wget https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip 2>/dev/null 1>&2
     unzip terraform_0.12.31_linux_amd64.zip 2>/dev/null 1>&2
-    wget https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_arm64.zip 2>/dev/null 1>&2
-    mv terraform_0.14.3_linux_arm64.zip /tmp
-    unzip -o -d /tmp /tmp/terraform_0.14.3_linux_arm64.zip 2>/dev/null 1>&2
+    wget https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip 2>/dev/null 1>&2
+    mv terraform_0.14.3_linux_amd64.zip /tmp
+    unzip -o -d /tmp /tmp/terraform_0.14.3_linux_amd64.zip 2>/dev/null 1>&2
     mv /tmp/terraform $TDH_DOCKER_FILES/terraform-bin
     chmod +x $TDH_DOCKER_FILES/terraform-bin
   fi
@@ -8783,9 +8821,11 @@ TanzuPackage_Harbor () {
     messageTitle "Installing $PACKAGE_DES"
     messagePrint " ▪ Tanzu Package ($PACKAGE_NAME)"   "$PACKAGE_ID ($package_ver/$package_rel)"
     tanzu package install $PACKAGE_NAME --package-name $PACKAGE_ID --namespace $PACKAGE_NAMESPACE \
-           --version $package_ver --create-namespace --poll-timeout 10m --log-file /tmp/harbor.log \
+           --version $package_ver --create-namespace --poll-timeout 20m --poll-interval 10s --log-file /tmp/harbor.log \
            --values-file $HARBOR_VALUES --wait=true --verbose 9 > /tmp/error.log 2>&1; ret=$?
 
+    # Ignore any install error because installation hits a timeout, but mostly succeeding, sdubois 14.01.2022
+    ret=0
     if [ $ret -ne 0 ]; then
       logMessages /tmp/error.log
       echo "ERROR: failed to install Tanzu Package $PACKAGE_NAME)"
@@ -8840,44 +8880,44 @@ TanzuPackage_Harbor () {
   messagePrint " ▪ Tanzu Package ($PACKAGE_NAME) USer:    "     "admin"
   messagePrint " ▪ Tanzu Package ($PACKAGE_NAME) Password:"     "$TDH_HARBOR_ADMIN_PASSWORD"
 
-  # --- VERIFY DNS DOMAIN ---
-  verifyHostedZone ${TDH_ENVNAME}.$AWS_HOSTED_DNS_DOMAIN
-
-  [ "$TDH_TOOLS" == "tdh-tools" ] && CONTOUR_NS=tanzu-system-ingress || CONTOUR_NS=projectcontour
-  [ "$TDH_TOOLS" == "tdh-tools" ] && CONTOUR_NS=$NAMESPACE || CONTOUR_NS=projectcontour
-
-  ipa=""; cnt=0
-  while [ "$ipa" == "" -a $cnt -lt 15 ]; do
-    #ipa=$(kubectl describe svc envoy --namespace $CONTOUR_NS | egrep "^LoadBalancer Ingress:" | awk '{ print $NF }')
-    ipa=$(kubectl get httpproxy harbor-httpproxy -n $NAMESPACE -o json | jq -r '.status.loadBalancer.ingress[].hostname') 
-    [ "$ipa" != "" ] && break
-    let cnt=cnt+1
-    sleep 30
-  done
-
-  if [ "$ipa" == "" ]; then
-    echo "ERROR: Failed to gather IP Adress of the ingress-contour-envoy service in namespace ingress-contour"
-    echo "       Please check manually:"
-    echo "       => kubectl get svc --namespace $NAMESPACE"
-    exit 1
-  fi
-
-  # --- SET DNS RECORD ---
-  if [ "$TDH_INFRASTRUCTURE" == "minikube" -o "$TDH_INFRASTRUCTURE" == "vSphere" -o "$TDH_INFRASTRUCTURE" == "Azure" -o "$TDH_INFRASTRUCTURE" == "docker" ]; then
-    setDNSrecord "$ipa" "${TDH_ENVNAME}" "${AWS_HOSTED_DNS_DOMAIN}" "*.apps-contour" "A"
-  else
-    setDNSalias "$ipa" "${TDH_ENVNAME}" "${AWS_HOSTED_DNS_DOMAIN}" "*.apps-contour" "A"
-  fi
+#  # --- VERIFY DNS DOMAIN ---
+#  verifyHostedZone ${TDH_ENVNAME}.$AWS_HOSTED_DNS_DOMAIN
+#
+#  [ "$TDH_TOOLS" == "tdh-tools" ] && CONTOUR_NS=tanzu-system-ingress || CONTOUR_NS=projectcontour
+#  [ "$TDH_TOOLS" == "tdh-tools" ] && CONTOUR_NS=$NAMESPACE || CONTOUR_NS=projectcontour
+#
+#  ipa=""; cnt=0
+#  while [ "$ipa" == "" -a $cnt -lt 15 ]; do
+#    #ipa=$(kubectl describe svc envoy --namespace $CONTOUR_NS | egrep "^LoadBalancer Ingress:" | awk '{ print $NF }')
+#    ipa=$(kubectl get httpproxy harbor-httpproxy -n $NAMESPACE -o json | jq -r '.status.loadBalancer.ingress[].hostname') 
+#    [ "$ipa" != "" ] && break
+#    let cnt=cnt+1
+#    sleep 30
+#  done
+#
+#  if [ "$ipa" == "" ]; then
+#    echo "ERROR: Failed to gather IP Adress of the ingress-contour-envoy service in namespace ingress-contour"
+#    echo "       Please check manually:"
+#    echo "       => kubectl get svc --namespace $NAMESPACE"
+#    exit 1
+#  fi
+#
+#  # --- SET DNS RECORD ---
+#  if [ "$TDH_INFRASTRUCTURE" == "minikube" -o "$TDH_INFRASTRUCTURE" == "vSphere" -o "$TDH_INFRASTRUCTURE" == "Azure" -o "$TDH_INFRASTRUCTURE" == "docker" ]; then
+#    setDNSrecord "$ipa" "${TDH_ENVNAME}" "${AWS_HOSTED_DNS_DOMAIN}" "*.apps-contour" "A"
+#  else
+#    setDNSalias "$ipa" "${TDH_ENVNAME}" "${AWS_HOSTED_DNS_DOMAIN}" "*.apps-contour" "A"
+#  fi
 
   # --- STORE SETTINGS IN CONFIGMAP ---
-  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_ENABLED        "true"
-  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_ADMIN_PASSWORD "$TDH_HARBOR_ADMIN_PASSWORD"
-  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_DNS_HARBOR     "$HARBOR_HOSTNAME"
-  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_DNS_NOTARY     "$NOTARY_HOSTNAME"
-  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_CHART_NAME     "$crt"
-  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_CHART_VERSION  "$ver"
-  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_CHART_STATUS   "$stt"
-  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_CHART_UPDATE   "$dat"
+  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_ENABLED          "true"
+  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_ADMIN_PASSWORD   "$TDH_HARBOR_ADMIN_PASSWORD"
+  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_DNS_HARBOR       "$HARBOR_HOSTNAME"
+  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_DNS_NOTARY       "$NOTARY_HOSTNAME"
+  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_PACKAGE__NAME    "$pkg_nam"
+  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_PACKAGE_VERSION  "$pkg_ver"
+  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_PACKAGE_STATUS   "$pkg_stt"
+  uodateConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_PACKAGE_UPDATE   "$dat"
 }
 
 # ------------------------------------------------------------------------------------------
