testing

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -4576,7 +4576,9 @@ tkgCreateCluster() {
   #########################################################################################################################
   ################################################ INSTALL TKG ON AZURE ###################################################
   #########################################################################################################################
+echo hallo1
   if [ "$TDH_DEPLOYMENT_CLOUD" == "docker" ]; then
+echo hallo2
     messageTitle "Tanzu Kubernetes Grid Deployment"
     messagePrint " ▪ Management Cluster Name"               "$TDH_TKGMC_NAME"
     messagePrint " ▪ Management Cluster Configuration"      "$HOME/.tanzu-demo-hub/config/${TDH_TKGMC_NAME}.cfg"
@@ -12699,6 +12701,22 @@ dockerPullImages() {
 }
 
 # ------------------------------------------------------------------------------------------
+# Function Name ......: deleteRunningPods
+# Function Purpose ...: Waiting for system Services to have completed starting
+# ------------------------------------------------------------------------------------------
+# Argument ($1) ......: Namespace
+# ------------------------------------------------------------------------------------------
+# Return Value .......: 0 - SUCCEED, 1 - FAILED
+# ------------------------------------------------------------------------------------------
+deleteRunningPods() {
+  NAMESPACE=$1
+
+  for n in $(cmdLoop kubectl -n $NAMESPACE get pods | grep Evicted | awk '{ print $1 }'); do
+    cmdLoop kubectl -n $NAMESPACE delete pod $n > /dev/null 2>&1
+  done
+}
+
+# ------------------------------------------------------------------------------------------
 # Function Name ......: runningPods
 # Function Purpose ...: Waiting for system Services to have completed starting
 # ------------------------------------------------------------------------------------------
@@ -12711,9 +12729,12 @@ runningPods() {
 
   cmdLoop kubectl get pods -A -o json > /tmp/output.yaml
   tot=$(jq -r --arg key "$NAMESPACE" '.items[] | select(.metadata.namespace == $key).status.phase' /tmp/output.yaml | \
-        egrep -v Evicted | wc -l | awk '{ print $1 }')
+        egrep -v "Evicted|Failed" | wc -l | awk '{ print $1 }')
   cnt=$(jq -r --arg key "$NAMESPACE" '.items[] | select(.metadata.namespace == $key).status.phase' /tmp/output.yaml | \
-        egrep -vc "Running|Completed|Succeeded|Evicted")
+        egrep -vc "Running|Completed|Succeeded|Evicted|Failed")
+
+echo "runningPods:tot:$tot" 1>&2
+echo "runningPods:cnt:$cnt" 1>&2
 
   let bsy=tot-cnt
 
@@ -12727,6 +12748,7 @@ runningPods() {
 
     let bsy=tot-cnt
     messageCount $bsy
+echo " - runningPods:$cnt:$cnt bsy:$bsy" 1>&2
 
     [ $cnt -eq 0 ] && break
 
