fasten up buildservice verify

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -3856,7 +3856,7 @@ installSpringCloudGateway() {
       # --- INSTALL CONTOUR INGRESS ---
       messageTitle "Installing Spring Cloud Gateway"
 
-      messagePrint " ▪ Relocate the images" "$TDH_REGISTRY_VMWARE_NAME/library/build-service"
+      messagePrint " ▪ Relocate the images" "$DNS_HARBOR/library/spring-cloud-gateway"
       cd /tmp/spring-cloud-gateway/spring-cloud-gateway-k8s-$TDH_SERVICE_SPRING_CLOUD_GATEWAY_VERSION
       scripts/relocate-images.sh $DNS_HARBOR/library/spring-cloud-gateway > /dev/null 2>&1
       if [ $? -ne 0 ]; then
@@ -4129,183 +4129,190 @@ installBuildService() {
     exit 1
   fi
 
-  # --- DOWNLOAD BUILD_SERVICE BINARIES ---
-  downloadFromPivnet build-service $TDH_SERVICE_BUILD_SERVICE_VERSION "$TDH_SERVICE_BUILD_SERVICE_VERSION" "build-service-$TDH_SERVICE_BUILD_SERVICE_VERSION.tar"
+echo "XXXXX START-BUILD-SERVICE"
+  # --- VERIFY IF BUILDSERVICE IS INSTALLED ---
+  kubectl get ns build-service > /dev/null 2>&1; ret=$?
+  kp clusterbuilder list > /dev/null 2>&1; stt=$?
 
-  TBS_FILE="/tmp/build-service-$TDH_SERVICE_BUILD_SERVICE_VERSION.tar"
-  [ -d /tmp/build-service ] && rm -rf /tmp/build-service
-  mkdir /tmp/build-service
-  tar xf $TBS_FILE -C /tmp/build-service
-
-  # --- VERIFY SERVICE CONFIGURATION ---
-  checkKubernetesServices registry_vmware
-  checkKubernetesServices registry_docker
-  checkKubernetesServices github
-
-  messageTitle "Verify VMware Registry Access" 
-  messagePrint " ▪ Registry URL"                "$TDH_REGISTRY_VMWARE_NAME"
-  messagePrint " ▪ Registry User"               "$TDH_REGISTRY_VMWARE_USER"
-  messagePrint " ▪ Registry Password"           "$(maskPassword \"$TDH_REGISTRY_VMWARE_PASS\")"
-
-  cnt=0; ret=1
-  while [ $ret -ne 0 -a $cnt -lt 5 ]; do
-    docker login $TDH_REGISTRY_VMWARE_NAME -u $TDH_REGISTRY_VMWARE_USER -p $TDH_REGISTRY_VMWARE_PASS > /dev/null 2>&1; ret=$?
-    sleep 10
-    let cnt=cnt+1
-  done
-
-  if [ $ret -ne 0 ]; then
-    echo "ERROR: Docker login does not work"
-    echo "       => docker login $TDH_REGISTRY_VMWARE_NAME -u $TDH_REGISTRY_VMWARE_USER -p $TDH_REGISTRY_VMWARE_PASS"; exit 1
-  fi
-
-  #########################################################################################################################
-  ################################# TANZU BUILD SERVICE (TBS) - ON DOCKER REGISTRY ########################################
-  #########################################################################################################################
-
-  if [ "$TDH_SERVICE_REGISTRY_DOCKER" == "true1" ]; then
-    DNS_DOCKER=$(getConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_NAME)
-    TDH_REGISTRY_DOCKER_NAME=$(getConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_NAME)
-    TDH_REGISTRY_DOCKER_PASS=$(getConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_PASS)
-
-    # --- TESTING REGISTRY ---
-    messagePrint "Verify Docker Registry Access" "$TDH_REGISTRY_DOCKER_NAME"
-
+  if [ $stt -ne 0 -o $ret -ne 0 ]; then
+    # --- DOWNLOAD BUILD_SERVICE BINARIES ---
+    downloadFromPivnet build-service $TDH_SERVICE_BUILD_SERVICE_VERSION "$TDH_SERVICE_BUILD_SERVICE_VERSION" "build-service-$TDH_SERVICE_BUILD_SERVICE_VERSION.tar"
+  
+    TBS_FILE="/tmp/build-service-$TDH_SERVICE_BUILD_SERVICE_VERSION.tar"
+    [ -d /tmp/build-service ] && rm -rf /tmp/build-service
+    mkdir /tmp/build-service
+    tar xf $TBS_FILE -C /tmp/build-service
+  
+    # --- VERIFY SERVICE CONFIGURATION ---
+    checkKubernetesServices registry_vmware
+    checkKubernetesServices registry_docker
+    checkKubernetesServices github
+  
+    messageTitle "Verify VMware Registry Access" 
+    messagePrint " ▪ Registry URL"                "$TDH_REGISTRY_VMWARE_NAME"
+    messagePrint " ▪ Registry User"               "$TDH_REGISTRY_VMWARE_USER"
+    messagePrint " ▪ Registry Password"           "$(maskPassword \"$TDH_REGISTRY_VMWARE_PASS\")"
+  
     cnt=0; ret=1
     while [ $ret -ne 0 -a $cnt -lt 5 ]; do
-      docker login -u $TDH_REGISTRY_DOCKER_USER -p $TDH_REGISTRY_DOCKER_PASS > /dev/null 2>&1; ret=$?
+      docker login $TDH_REGISTRY_VMWARE_NAME -u $TDH_REGISTRY_VMWARE_USER -p $TDH_REGISTRY_VMWARE_PASS > /dev/null 2>&1; ret=$?
       sleep 10
       let cnt=cnt+1
     done
-
+  
     if [ $ret -ne 0 ]; then
       echo "ERROR: Docker login does not work"
-      echo "       => docker login $TDH_REGISTRY_DOCKER_NAME -u $TDH_REGISTRY_DOCKER_USER -p $TDH_REGISTRY_DOCKER_PASS"; exit 1
+      echo "       => docker login $TDH_REGISTRY_VMWARE_NAME -u $TDH_REGISTRY_VMWARE_USER -p $TDH_REGISTRY_VMWARE_PASS"; exit 1
     fi
-
-    messagePrint " ▪ Relocate images to" "$TDH_REGISTRY_DOCKER_NAME/$TDH_REGISTRY_DOCKER_USER/build-service"
-    kbld relocate -f /tmp/build-service/images.lock --lock-output /tmp/build-service/images-relocated.lock \
-         --repository $TDH_REGISTRY_DOCKER_NAME/$TDH_REGISTRY_DOCKER_USER/build-service > /dev/null 2>&1
-    if [ $? -ne 0 ]; then
-      echo "ERROR: Image Relocation faied"
-      echo "       => kbld relocate -f /tmp/build-service/images.lock --lock-output /tmp/build-service/images-relocated.lock \\"
-      echo "          --repository $TDH_REGISTRY_DOCKER_NAME/$TDH_REGISTRY_DOCKER_USER/build-service"; exit 1
-    fi
-  fi
-
-  #########################################################################################################################
-  ################################# TANZU BUILD SERVICE (TBS) - ON HARBOR REGISTRY ########################################
-  #########################################################################################################################
-
-  if [ "$TDH_SERVICE_REGISTRY_HARBOR" == "true" ]; then 
-    DNS_HARBOR=$(getConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_DNS_HARBOR)
-    TDH_HARBOR_REGISTRY_DNS_HARBOR=$(getConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_DNS_HARBOR)
-    TDH_HARBOR_REGISTRY_ADMIN_PASSWORD=$(getConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_ADMIN_PASSWORD)
-
-    messageTitle "Verify Harbor Registry Access"
-    messagePrint " ▪ Registry URL"                "$TDH_HARBOR_REGISTRY_DNS_HARBOR"
-    messagePrint " ▪ Registry User"               "admin"
-    messagePrint " ▪ Registry Password"           "$(maskPassword \"$TDH_HARBOR_REGISTRY_ADMIN_PASSWORD\")"
-
-    cnt=0; ret=1
-    while [ $ret -ne 0 -a $cnt -lt 5 ]; do
-      docker login $TDH_HARBOR_REGISTRY_DNS_HARBOR -u admin -p $TDH_HARBOR_REGISTRY_ADMIN_PASSWORD > /dev/null 2>&1; ret=$?
-      sleep 10
-      let cnt=cnt+1
-    done
-
-    if [ $ret -ne 0 ]; then
-      echo "ERROR: Docker login does not work 1'"
-      echo "       => docker login $TDH_HARBOR_REGISTRY_DNS_HARBOR -u admin -p $TDH_HARBOR_REGISTRY_ADMIN_PASSWORD"; exit 1
-    fi
-
-    messagePrint " ▪ Relocate the images" "$TDH_REGISTRY_VMWARE_NAME/library/build-service"
-    kbld relocate -f /tmp/build-service/images.lock --lock-output /tmp/build-service/images-relocated.lock \
-         --repository $DNS_HARBOR/library/build-service > /dev/null 2>&1
-    if [ $? -ne 0 ]; then
-      echo "ERROR: Image Relocation faied"
-      echo "       => kbld relocate -f /tmp/build-service/images.lock --lock-output /tmp/build-service/images-relocated.lock \\"
-      echo "          --repository $DNS_HARBOR/library/build-service"; exit 1
-    fi
-
-    # --- DEPLOY KAPP ---
-    stt=$(kapp inspect -a tanzu-build-service 2>/dev/null | tail -1)
-    if [ "$stt" != "Succeeded" ]; then
-      kapp delete -a tanzu-build-service -y >/dev/null 2>&1
-
-      messageTitle "Installing Tanzu Build Service"
-      messagePrint " ▪ Install Build Service (kapp)" "`date`"
-      echo "-----------------------------------------------------------------------------------------------------------"
-      echo " WARNING: This process may take up to 2h for the deployment, Please run kapp manually to get more info"
-      echo "          => kapp inspect -a tanzu-build-service --column Namespace,name,reconcile_state | grep -v ok"
-      echo "-----------------------------------------------------------------------------------------------------------"
-        ytt -f /tmp/build-service/values.yaml \
-            -f /tmp/build-service/manifests/ \
-            -f $TDHPATH/certificates/ca.pem \
-            -v docker_repository="$DNS_HARBOR/library/build-service" \
-            -v docker_username="admin" \
-            -v docker_password="$TDH_HARBOR_REGISTRY_ADMIN_PASSWORD" 2>/dev/null \
-            | kbld -f /tmp/build-service/images-relocated.lock -f- 2>/dev/null \
-            | kapp deploy -a tanzu-build-service -f- -y > /dev/null 2>&1; ret=$?
   
-      cnt=$(kapp inspect -a tanzu-build-service --json | jq -r '.Tables[].Rows[].reconcile_state' | grep -vc "ok")
-      while [ $cnt -ne 0 ]; do
-        cnt=$(kapp inspect -a tanzu-build-service --json | jq -r '.Tables[].Rows[].reconcile_state' | grep -vc "ok")
-        sleep 360
+    #########################################################################################################################
+    ################################# TANZU BUILD SERVICE (TBS) - ON DOCKER REGISTRY ########################################
+    #########################################################################################################################
+  
+    if [ "$TDH_SERVICE_REGISTRY_DOCKER" == "true1" ]; then
+      DNS_DOCKER=$(getConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_NAME)
+      TDH_REGISTRY_DOCKER_NAME=$(getConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_NAME)
+      TDH_REGISTRY_DOCKER_PASS=$(getConfigMap tanzu-demo-hub TDH_REGISTRY_DOCKER_PASS)
+  
+      # --- TESTING REGISTRY ---
+      messagePrint "Verify Docker Registry Access" "$TDH_REGISTRY_DOCKER_NAME"
+  
+      cnt=0; ret=1
+      while [ $ret -ne 0 -a $cnt -lt 5 ]; do
+        docker login -u $TDH_REGISTRY_DOCKER_USER -p $TDH_REGISTRY_DOCKER_PASS > /dev/null 2>&1; ret=$?
+        sleep 10
+        let cnt=cnt+1
       done
-      messagePrint " ▪ Install Build Service completed" "`date`"
-    else
-      messageTitle "Verify Tanzu Build Service"
-      messagePrint " ▪ Veriify Build Service (kapp)" "tanzu-build-service"
+  
+      if [ $ret -ne 0 ]; then
+        echo "ERROR: Docker login does not work"
+        echo "       => docker login $TDH_REGISTRY_DOCKER_NAME -u $TDH_REGISTRY_DOCKER_USER -p $TDH_REGISTRY_DOCKER_PASS"; exit 1
+      fi
+  
+      messagePrint " ▪ Relocate images to" "$TDH_REGISTRY_DOCKER_NAME/$TDH_REGISTRY_DOCKER_USER/build-service"
+      kbld relocate -f /tmp/build-service/images.lock --lock-output /tmp/build-service/images-relocated.lock \
+           --repository $TDH_REGISTRY_DOCKER_NAME/$TDH_REGISTRY_DOCKER_USER/build-service > /dev/null 2>&1
+      if [ $? -ne 0 ]; then
+        echo "ERROR: Image Relocation faied"
+        echo "       => kbld relocate -f /tmp/build-service/images.lock --lock-output /tmp/build-service/images-relocated.lock \\"
+        echo "          --repository $TDH_REGISTRY_DOCKER_NAME/$TDH_REGISTRY_DOCKER_USER/build-service"; exit 1
+      fi
     fi
-  fi
+  
+    #########################################################################################################################
+    ################################# TANZU BUILD SERVICE (TBS) - ON HARBOR REGISTRY ########################################
+    #########################################################################################################################
+  
+    if [ "$TDH_SERVICE_REGISTRY_HARBOR" == "true" ]; then 
+      DNS_HARBOR=$(getConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_DNS_HARBOR)
+      TDH_HARBOR_REGISTRY_DNS_HARBOR=$(getConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_DNS_HARBOR)
+      TDH_HARBOR_REGISTRY_ADMIN_PASSWORD=$(getConfigMap tanzu-demo-hub TDH_HARBOR_REGISTRY_ADMIN_PASSWORD)
+  
+      messageTitle "Verify Harbor Registry Access"
+      messagePrint " ▪ Registry URL"                "$TDH_HARBOR_REGISTRY_DNS_HARBOR"
+      messagePrint " ▪ Registry User"               "admin"
+      messagePrint " ▪ Registry Password"           "$(maskPassword \"$TDH_HARBOR_REGISTRY_ADMIN_PASSWORD\")"
+  
+      cnt=0; ret=1
+      while [ $ret -ne 0 -a $cnt -lt 5 ]; do
+        docker login $TDH_HARBOR_REGISTRY_DNS_HARBOR -u admin -p $TDH_HARBOR_REGISTRY_ADMIN_PASSWORD > /dev/null 2>&1; ret=$?
+        sleep 10
+        let cnt=cnt+1
+      done
 
-  # --- DOWNLOAD KP UTILITY ---
-  if [ ! -f /usr/local/bin/kp ]; then 
-    downloadFromPivnet build-service $TDH_SERVICE_BUILD_SERVICE_VERSION $TDH_SERVICE_BUILD_SERVICE_KP "kp-darwin"
-
-    echo "INFO: Please copy the file /tmp/kp-darwin-$TDH_SERVICE_BUILD_SERVICE_KP /usr/local/bin"
-    echo "      => sudo mv /tmp/kp-darwin-$TDH_SERVICE_BUILD_SERVICE_KP /usr/local/bin"
-    echo "      => sudo chmod a+x /usr/local/bin/kp"
-  fi
-
-  kp clusterbuilder list > /dev/null 2>&1
-  if [ $? -ne 0 ]; then 
-    # --- DOWNLOAD BUILD_SERVICE DEPENDANCIES ---
-    downloadFromPivnet tbs-dependencies $TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES $TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES "descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml"
-
-    messagePrint " ▪ Import Dependency Descriptors" "/tmp/descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml"
-    cnt=0; ret=1
-    while [ $ret -ne 0 -a $cnt -lt 5 ]; do
-      if [ $DEBUG -eq 1 ]; then
-        messageLine
-        kp import -f /tmp/descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml; ret=$?
-        messageLine
-      else
-        kp import -f /tmp/descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml > /dev/null 2>&1; ret=$?
+      if [ $ret -ne 0 ]; then
+        echo "ERROR: Docker login does not work 1'"
+        echo "       => docker login $TDH_HARBOR_REGISTRY_DNS_HARBOR -u admin -p $TDH_HARBOR_REGISTRY_ADMIN_PASSWORD"; exit 1
+      fi
+  
+      messagePrint " ▪ Relocate the images" "$TDH_REGISTRY_VMWARE_NAME/library/build-service"
+      kbld relocate -f /tmp/build-service/images.lock --lock-output /tmp/build-service/images-relocated.lock \
+           --repository $DNS_HARBOR/library/build-service > /dev/null 2>&1
+      if [ $? -ne 0 ]; then
+        echo "ERROR: Image Relocation faied"
+        echo "       => kbld relocate -f /tmp/build-service/images.lock --lock-output /tmp/build-service/images-relocated.lock \\"
+        echo "          --repository $DNS_HARBOR/library/build-service"; exit 1
       fi
 
-      [ $ret -eq 0 ] && break
-      sleep 30
-      let cnt=cnt+1
-    done
+      # --- DEPLOY KAPP ---
+      stt=$(kapp inspect -a tanzu-build-service 2>/dev/null | tail -1)
+      if [ "$stt" != "Succeeded" ]; then
+        kapp delete -a tanzu-build-service -y >/dev/null 2>&1
 
-    if [ $ret -ne 0 ]; then
-      echo "ERROR: failed to import descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml"
-      echo "       => kp import -f /tmp/descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml"
-      exit 1
+        messageTitle "Installing Tanzu Build Service"
+        messagePrint " ▪ Install Build Service (kapp)" "`date`"
+        echo "-----------------------------------------------------------------------------------------------------------"
+        echo " WARNING: This process may take up to 2h for the deployment, Please run kapp manually to get more info"
+        echo "          => kapp inspect -a tanzu-build-service --column Namespace,name,reconcile_state | grep -v ok"
+        echo "-----------------------------------------------------------------------------------------------------------"
+          ytt -f /tmp/build-service/values.yaml \
+              -f /tmp/build-service/manifests/ \
+              -f $TDHPATH/certificates/ca.pem \
+              -v docker_repository="$DNS_HARBOR/library/build-service" \
+              -v docker_username="admin" \
+              -v docker_password="$TDH_HARBOR_REGISTRY_ADMIN_PASSWORD" 2>/dev/null \
+              | kbld -f /tmp/build-service/images-relocated.lock -f- 2>/dev/null \
+              | kapp deploy -a tanzu-build-service -f- -y > /dev/null 2>&1; ret=$?
+    
+        cnt=$(kapp inspect -a tanzu-build-service --json | jq -r '.Tables[].Rows[].reconcile_state' | grep -vc "ok")
+        while [ $cnt -ne 0 ]; do
+          cnt=$(kapp inspect -a tanzu-build-service --json | jq -r '.Tables[].Rows[].reconcile_state' | grep -vc "ok")
+          sleep 360
+        done
+        messagePrint " ▪ Install Build Service completed" "`date`"
+      else
+        messageTitle "Verify Tanzu Build Service"
+        messagePrint " ▪ Veriify Build Service (kapp)" "tanzu-build-service"
+      fi
+    fi
+
+    # --- DOWNLOAD KP UTILITY ---
+    if [ ! -f /usr/local/bin/kp ]; then 
+      downloadFromPivnet build-service $TDH_SERVICE_BUILD_SERVICE_VERSION $TDH_SERVICE_BUILD_SERVICE_KP "kp-darwin"
+  
+      echo "INFO: Please copy the file /tmp/kp-darwin-$TDH_SERVICE_BUILD_SERVICE_KP /usr/local/bin"
+      echo "      => sudo mv /tmp/kp-darwin-$TDH_SERVICE_BUILD_SERVICE_KP /usr/local/bin"
+      echo "      => sudo chmod a+x /usr/local/bin/kp"
+    fi
+  
+    kp clusterbuilder list > /dev/null 2>&1
+    if [ $? -ne 0 ]; then 
+      # --- DOWNLOAD BUILD_SERVICE DEPENDANCIES ---
+      downloadFromPivnet tbs-dependencies $TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES $TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES "descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml"
+  
+      messagePrint " ▪ Import Dependency Descriptors" "/tmp/descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml"
+      cnt=0; ret=1
+      while [ $ret -ne 0 -a $cnt -lt 5 ]; do
+        if [ $DEBUG -eq 1 ]; then
+          messageLine
+          kp import -f /tmp/descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml; ret=$?
+          messageLine
+        else
+          kp import -f /tmp/descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml > /dev/null 2>&1; ret=$?
+        fi
+  
+        [ $ret -eq 0 ] && break
+        sleep 30
+        let cnt=cnt+1
+      done
+  
+      if [ $ret -ne 0 ]; then
+        echo "ERROR: failed to import descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml"
+        echo "       => kp import -f /tmp/descriptor-$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES.yaml"
+        exit 1
+      fi
     fi
   fi
 
   kp clusterbuilder list > /dev/null 2>&1
   [ $? -eq 0 ] && stt="successfuly installed" || stt="installed failed"
   if [ $DEBUG -eq 1 ]; then
-    messagePrint " - Verify Dependency Descriptors" "$stt"
+    messagePrint " ▪ Verify Dependency Descriptors" "$stt"
     messageLine
     kp clusterbuilder list | sed '$d'
     messageLine
   else
-    messagePrint " - Verify Dependency Descriptors" "$stt"
+    messagePrint " ▪ Verify Dependency Descriptors" "$stt"
   fi
 
   uodateConfigMap tanzu-demo-hub TDH_SERVICE_BUILD_SERVICE          "true"
