add kubernetes-dashboard

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -6590,6 +6590,129 @@ installGitea() {
 }
 
 # ------------------------------------------------------------------------------------------
+# Function Name ......: installKubeernetesDashboard
+# Function Purpose ...: Install Kubernetes Dashboard 
+# ------------------------------------------------------------------------------------------
+# Argument ($1) ......: None
+# ------------------------------------------------------------------------------------------
+# Return Value .......: 0 - SUCCEED, 1 - FAILED
+# ------------------------------------------------------------------------------------------
+installKubeernetesDashboard() {
+  NAMESPACE=kubernetes-dashboard
+  HELMCHART=kubernetes-dashboard
+  HELMREPO=kubernetes-dashboard
+
+#helm repo add kubernetes-dashboard https: //kubernetes.github.io/dashboard/
+#helm install kubernetes-dashboardkubernetes-dashboard/kubernetes-dashboard
+
+  if [ "$TDH_SERVICE_KUBEAPPS" != "true" ]; then
+    uodateConfigMap tanzu-demo-hub TDH_SERVICE_KUBERNETES_DASHBOARD        "false"
+    deleteHelmChart $NAMESPACE $HELMCHART
+    return
+  fi
+
+  TDH_DOMAIN=$(getConfigMap tanzu-demo-hub TDH_DOMAIN)
+  TDH_ENVNAME=$(getConfigMap tanzu-demo-hub TDH_ENVNAME)
+  DOMAIN=$(getConfigMap tanzu-demo-hub TDH_INGRESS_CONTOUR_LB_DOMAIN)
+
+  messageTitle "Kubernetes Dashboard"
+  cnt=$(helm list -q -n $NAMESPACE | egrep -c "^$HELMCHART")
+  if [ $cnt -eq 0 ]; then
+    # --- CREATE NAMESPACE ---
+    messagePrint " ▪ Create Namespace" "$HELMCHART"
+    deleteNamespace $NAMESPACE > /dev/null 2>&1
+    createNamespace $NAMESPACE > /dev/null 2>&1
+
+    # --- DOCKER PULL SECRET ---
+    dockerPullSecret $NAMESPACE
+
+    # --- COPY SECRET TO NAMESPACE ---
+    messagePrint " ▪ Copy TLS Secret" "tanzu-demo-hub-tls"
+    copySecretObject default $NAMESPACE tanzu-demo-hub-tls
+
+    kubectl get secret tanzu-demo-hub-tls --namespace=default -oyaml | grep -v '^\s*namespace:\s' | \
+    sed 's/name: tanzu-demo-hub-tls/name: kubernetes-dashboard-certs/g' | 
+    kubectl apply --namespace=$NAMESPACE -f - > /dev/null 2>&1
+
+    #kubectl get secret tanzu-demo-hub-tls --namespace=default -oyaml | grep -v '^\s*namespace:\s' | \
+    #kubectl apply --namespace=$NAMESPACE -f - > /dev/null 2>&1
+
+    # --- ADD GIT REPOSITORY ---
+    messagePrint " ▪ Add the Kubernetes Repository"   "https://kubernetes.github.io/dashboard/"
+    helmRepoAdd kubernetes-dashboard "https://kubernetes.github.io/dashboard/"
+
+    if [ "$TDH_SERVICE_KUBERNETES_DASHBOARD_VERSION" == "" -o "$TDH_SERVICE_KUBERNETES_DASHBOARD_VERSION" == "latest" ]; then
+      HELMCHART_VER=$(helm search repo $HELMREPO/$HELMCHART | egrep "^$HELMCHART" | tail -1 | awk '{ print $2 }')
+    else
+      HELMCHART_VER=$TDH_SERVICE_KUBERNETES_DASHBOARD
+    fi
+
+    HELM_VALUES=/tmp/helm_kubeapps_dashboard_values.yaml
+
+    echo "global:"                                                                                                              >  $HELM_VALUES
+    echo "  imageRegistry: docker.io"                                                                                           >> $HELM_VALUES
+    echo "  imagePullSecrets:"                                                                                                  >> $HELM_VALUES
+    echo "    - tdh-docker-repo"                                                                                                >> $HELM_VALUES
+    echo ""                                                                                                                     >> $HELM_VALUES
+    echo "#service:"                                                                                                             >> $HELM_VALUES
+    echo "#  type: ClusterIP"                                                                                                    >> $HELM_VALUES
+    echo "#  externalPort: 443"                                                                                                  >> $HELM_VALUES
+    echo ""                                                                                                                     >> $HELM_VALUES
+    echo "ingress:"                                                                                                             >> $HELM_VALUES
+    echo "  enabled: true"                                                                                                      >> $HELM_VALUES
+    echo "  annotations:"                                                                                                       >> $HELM_VALUES
+    echo "    kubernetes.io/ingress.class: contour"                                                                             >> $HELM_VALUES
+    echo "    ingress.kubernetes.io/force-ssl-redirect: \"true\""                                                               >> $HELM_VALUES
+    echo "    ingress.kubernetes.io/ssl-passthrough: \"true\""                                                                  >> $HELM_VALUES
+    echo "  paths:"                                                                                                             >> $HELM_VALUES
+    echo "    - /"                                                                                                              >> $HELM_VALUES
+    echo "    - /*"                                                                                                             >> $HELM_VALUES
+    echo "  hosts:"                                                                                                             >> $HELM_VALUES
+    echo "    - dashboard.$DOMAIN"                                                                                              >> $HELM_VALUES
+    echo "  tls:"                                                                                                               >> $HELM_VALUES
+    echo "  - secretName: tanzu-demo-hub-tls"                                                                                   >> $HELM_VALUES
+    echo "    hosts:"                                                                                                           >> $HELM_VALUES
+    echo "      - dashboard.$DOMAIN"                                                                                            >> $HELM_VALUES
+
+echo "HELM_VALUES:$HELM_VALUES"
+cat $HELM_VALUES
+
+echo "helm install $HELMCHART --namespace $NAMESPACE $HELMREPO/$HELMCHART -f $HELM_VALUES --version $HELMCHART_VER"
+
+exit
+    messagePrint " ▪ Deploy the Kubeapps Helm Chart" "kubeapps"
+helm install kubernetes-dashboardkubernetes-dashboard/kubernetes-dashboard
+    messagePrint " ▪ Deploy the Kubeapps Helm Chart" "kubeapps"
+#gaga kubernetes-dashboard
+    cnt=0; ret=1; stt="notdeployed"
+    while [ $ret -ne 0 -a $cnt -lt 5 -a "$stt" != "deployed" ]; do
+      #helm install $HELMCHART --namespace $NAMESPACE $HELMREPO/$HELMCHART -f $HELM_VALUES --version $HELMCHART_VER --create-namespace --wait --wait-for-jobs --timeout 10m > /tmp/error.log 2>&1; ret=$?
+echo "helm install $HELMCHART --namespace $NAMESPACE $HELMREPO/$HELMCHART -f $HELM_VALUES --version $HELMCHART_VER"
+      helm install $HELMCHART --namespace $NAMESPACE $HELMREPO/$HELMCHART -f $HELM_VALUES --version $HELMCHART_VER --create-namespace --wait --wait-for-jobs --timeout 10m; ret=$?
+
+      # --- WAIT FOR PODS TO GET STARTED ---
+      runningPods $NAMESPACE
+
+      cmdLoop helm ls -n $NAMESPACE -o json > /tmp/output.json
+      stt=$(jq -r --arg chart "$HELMCHART" '.[] | select(.name == $chart).status' /tmp/output.json)
+
+      [ $ret -eq 0 -a "$stt" == "deployed" ] && break
+
+      # --- DELTE FAILED HELM CHART ---
+      deleteHelmChart $NAMESPACE $HELMCHART > /dev/null 2>&1
+      deleteNamespace $NAMESPACE > /dev/null 2>&1
+
+      let cnt=cnt+1
+      sleep 30
+    done
+  fi
+
+exit
+  # --- STORE SETTINGS IN CONFIGMAP ---
+  uodateConfigMap tanzu-demo-hub TDH_SERVICE_KUBERNETES_DASHBOARD             "true"
+}
+
+# ------------------------------------------------------------------------------------------
 # Function Name ......: installKubeapps
 # Function Purpose ...: Install Kubeapps Helm Chargt
 # ------------------------------------------------------------------------------------------
