tap-e2e-app demos

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -50,14 +50,14 @@ fakeCmd() {
   normal=$(tput sgr0)
 
   echo -e "     => ${bold}$1${normal}\c"; read x
-  echo "     ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
+  echo "     -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
   cat /tmp/log | sed -e 's/^/     /g'
-  echo "     ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
+  echo "     -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
   echo ""
 }
 
 fileCat() {
-  echo "     ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
+  echo "     -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
 
   if [ -f /usr/local/bin/bat -o /usr/bin/bat ]; then
     bat -p --color always $1 | sed -e 's/^/     /g' -e '/^$/N;/^\n$/D'
@@ -65,13 +65,13 @@ fileCat() {
     cat $1 | sed '/^$/N;/^\n$/D'
   fi
 
-  echo "     ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
+  echo "     -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
   echo ""
 }
 
 execCat() {
   echo -e "     => cat $1\c"; read x
-  echo "     ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
+  echo "     -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
 
   if [ -f /usr/local/bin/bat -o /usr/bin/bat ]; then
     #bat -p --color always $1 | sed 's/^/     /g'
@@ -80,7 +80,7 @@ execCat() {
     cat $1 | sed '/^$/N;/^\n$/D'
   fi
 
-  echo "     ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
+  echo "     -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
   echo ""
 }
 
@@ -91,7 +91,7 @@ execCmd() {
   if [ "$(uname)" == "Darwin" ]; then SED=gsed; else SED=sed; fi
 
   echo -e "     => ${bold}$1${normal}\c"; read x
-  echo "     ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
+  echo "     -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
   ret=1; cnt=0
   while [ $ret -ne 0 -a $cnt -lt 5 ]; do
     eval "$1" > /tmp/execCmd.log 2>&1; ret=$?
@@ -105,7 +105,7 @@ execCmd() {
 
   #DELETEME
   #eval "$1" 2>&1 | $SED '${/^$/d;}' | $SED 's/^/     /g' 
-  echo "     ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
+  echo "     -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
   echo ""
 }
 
@@ -11831,6 +11831,46 @@ giteaForkRepo() {
 }
 
 # ------------------------------------------------------------------------------------------
+# Function Name ......: deleteGiteaRepo
+# Function Purpose ...: Delete Gitea Repo
+# ------------------------------------------------------------------------------------------
+# Argument ($1) ......: n/a
+# ------------------------------------------------------------------------------------------
+# Return Value .......: n/a
+# ------------------------------------------------------------------------------------------
+# Reference Documentation:
+# https://crib.utwente.nl/git/api/swagger#/repository
+# ------------------------------------------------------------------------------------------
+deleteGiteaRepo() {
+  GITEA_ORG=$1
+  GITEA_REPO=$2
+
+  TDH_SERVICE_GITEA_ADMIN_USER=$(getConfigMap tanzu-demo-hub TDH_SERVICE_GITEA_ADMIN_USER)
+  TDH_SERVICE_GITEA_ADMIN_PASS=$(getConfigMap tanzu-demo-hub TDH_SERVICE_GITEA_ADMIN_PASS)
+  TDH_SERVICE_GITEA_SERVER=$(getConfigMap tanzu-demo-hub TDH_SERVICE_GITEA_SERVER)
+  TDH_SERVICE_GITEA_SERVER_URL=$(getConfigMap tanzu-demo-hub TDH_SERVICE_GITEA_SERVER_URL)
+  TDH_SERVICE_GITEA_ADMIN_TOKEN_ID=$(getConfigMap tanzu-demo-hub TDH_SERVICE_GITEA_ADMIN_TOKEN_ID)
+
+  curl -X GET ${TDH_SERVICE_GITEA_SERVER_URL}/api/v1/repos/$GITEA_ORG/$GITEA_REPO \
+       -H 'accept: application/json' 2>/dev/null > /tmp/output.json
+  nam=$(jq -r '.name' /tmp/output.json)
+
+  if [ "$nam" == "$GITEA_REPO" ]; then
+    cnt=0; ret=1
+    while [ $ret -ne 0 -a $cnt -lt 5 ]; do
+      curl -X DELETE ${TDH_SERVICE_GITEA_SERVER_URL}/api/v1/repos/$GITEA_ORG/$GITEA_REPO \
+           -H 'accept: application/json' \
+           -H 'Content-Type: application/json' \
+           -u "$TDH_SERVICE_GITEA_ADMIN_USER:$TDH_SERVICE_GITEA_ADMIN_PASS" 2>/dev/null > /tmp/output.json 2>&1; ret=$?
+      [ $ret -eq 0 ] && break
+
+      let cnt=cnt+1
+      sleep 10
+    done
+  fi
+}
+
+# ------------------------------------------------------------------------------------------
 # Function Name ......: createGiteaRepo
 # Function Purpose ...: Get Gitea Repo
 # ------------------------------------------------------------------------------------------
@@ -11839,7 +11879,7 @@ giteaForkRepo() {
 # Return Value .......: n/a
 # ------------------------------------------------------------------------------------------
 # Reference Documentation:
-# https://developer.vmware.com/apis/897/tanzu-mission-control
+# https://crib.utwente.nl/git/api/swagger#/repository
 # ------------------------------------------------------------------------------------------
 createGiteaRepo() {
   GITEA_ORG=$1
@@ -11884,7 +11924,7 @@ createGiteaRepo() {
 # Return Value .......: n/a
 # ------------------------------------------------------------------------------------------
 # Reference Documentation:
-# https://developer.vmware.com/apis/897/tanzu-mission-control
+# https://crib.utwente.nl/git/api/swagger#/repository
 # ------------------------------------------------------------------------------------------
 createGiteaOrg() {
   GITEA_REPO=$1
@@ -11934,7 +11974,7 @@ createGiteaOrg() {
 # Return Value .......: n/a
 # ------------------------------------------------------------------------------------------
 # Reference Documentation:
-# https://developer.vmware.com/apis/897/tanzu-mission-control
+# https://crib.utwente.nl/git/api/swagger#/repository
 # ------------------------------------------------------------------------------------------
 createGiteaAPItoken() {
   TDH_SERVICE_GITEA_ADMIN_USER=$(getConfigMap tanzu-demo-hub TDH_SERVICE_GITEA_ADMIN_USER)
