patch rate limiting

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -6215,4 +6215,23 @@ installTanzuPlugins() {
   fi
 }
 
+patchServiceAccount() {
+  SERVICE_ACCOUNT=$1
+  NAMESPACE=$2
+
+  messagePrint " ▪ Patch Docker RateLimit in ServiceAccount"  "$NAMESPACE/$SERVICE_ACCOUNT"
+  kubectl -n $NAMESPACE create secret docker-registry tdh-docker-repo \
+          --docker-server $TDH_REGISTRY_DOCKER_NAME \
+          --docker-username $TDH_REGISTRY_DOCKER_USER \
+          --docker-password $TDH_REGISTRY_DOCKER_PASS
+
+  kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "tdh-docker-repo"}]}' -n $NAMESPACE > /dev/null 2>&1; ret=$?
+  if [ $ret -ne 0 ]; then
+    echo "ERROR: Failed to Patch Service account"
+    echo "       => kubectl patch serviceaccount default -p '{\"imagePullSecrets\": [{\"name\": \"tdh-docker-repo\"}]}' -n $NAMESPACE"
+    exit
+  fi
+} 
+
+
 
