tdh-tools-tce extenstions

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -6762,24 +6762,39 @@ verify_docker() {
 }
 
 tdh_tools_build() {
+#gaga
   REBUILD_REQUIRED=0
   REBUILD_REQUIRED_SOFTWARE=0
   verify_docker
   checkTDHenvironment
 
-  [ -f files/tdh-tools/tdh-tools.cfg ] && . files/tdh-tools/tdh-tools.cfg
+  if [ "$1" == "tce" ]; then 
+    BUILD_MODE=tce
+    TDH_TOOLS_DOCKERFILE=Dockerfile-tce
+    TDH_TOOLS_IMAGE=tdh-tools-tce
+    [ -f files/tdh-tools/tdh-tools-tce.cfg ] && . files/tdh-tools/tdh-tools-tce.cfg
+
+    TCE_DOWNLOAD_URL=https://github.com/vmware-tanzu/community-edition/releases/download/${TKG_COMNUNITY_EDITION_VERSION}
+    TCE_LINUX_PACKAGE=tce-linux-amd64-${TKG_COMNUNITY_EDITION_VERSION}
+    TCE_DARWIN_PACKAGE=tce-darwin-amd64-${TKG_COMNUNITY_EDITION_VERSION}
+  else 
+    TDH_TOOLS_DOCKERFILE=Dockerfile
+    TDH_TOOLS_IMAGE=tdh-tools
+    BUILD_MODE=tkg
+    [ -f files/tdh-tools/tdh-tools.cfg ] && . files/tdh-tools/tdh-tools.cfg
+  fi
 
   TDH_DOCKER_FILES=/tmp/tdh-tools
   mkdir -p $TDH_DOCKER_FILES
-  cp files/tdh-tools/Dockerfile           $TDH_DOCKER_FILES
+  cp files/tdh-tools/$TDH_TOOLS_DOCKERFILE           $TDH_DOCKER_FILES
   cp files/tdh-tools/wrapdocker           $TDH_DOCKER_FILES
   cp files/tdh-tools/tmc                  $TDH_DOCKER_FILES
   cp files/tdh-tools/jenkins-cli.jar      $TDH_DOCKER_FILES
   cp files/tdh-tools/vmware-ovftool.tar   $TDH_DOCKER_FILES
-  DOCKER_CHKSUM=$(sum $TDHPATH/files/tdh-tools/Dockerfile | awk '{ print $1 }')
-  DOCKER_IMAGE_LATEST_ID=$(docker images | egrep "^tdh-tools" | grep "latest" | awk '{ print $3 }')
-  DOCKER_IMAGE_ID=$(docker images | egrep "^tdh-tools" | grep "CHKSUM" | grep "$DOCKER_IMAGE_LATEST_ID" | awk '{ print $3 }')
-  DOCKER_IMAGE_CHKSUM=$(docker images | egrep "^tdh-tools" | grep "CHKSUM" | grep "$DOCKER_IMAGE_LATEST_ID" | awk '{ print $2 }' | sed 's/CHKSUM-//g')
+  DOCKER_CHKSUM=$(sum $TDHPATH/files/tdh-tools/$TDH_TOOLS_DOCKERFILE | awk '{ print $1 }')
+  DOCKER_IMAGE_LATEST_ID=$(docker images | egrep "^$TDH_TOOLS_IMAGE " | grep "latest" | awk '{ print $3 }')
+  DOCKER_IMAGE_ID=$(docker images | egrep "^$TDH_TOOLS_IMAGE " | grep "CHKSUM" | grep "$DOCKER_IMAGE_LATEST_ID" | awk '{ print $3 }')
+  DOCKER_IMAGE_CHKSUM=$(docker images | egrep "^$TDH_TOOLS_IMAGE" | grep "CHKSUM" | grep "$DOCKER_IMAGE_LATEST_ID" | awk '{ print $2 }' | sed 's/CHKSUM-//g')
 
   # --- SET CORRECT PERMISSONS ---
   [ -f $TDH_DOCKER_FILES/tmc ] && chmod a+x $TDH_DOCKER_FILES/tmc
@@ -6788,9 +6803,9 @@ tdh_tools_build() {
   [ "$TDH_SERVICE_BUILD_SERVICE_VERSION" == "" ] && TDH_SERVICE_BUILD_SERVICE_VERSION=1.2.1
   [ "$TDH_SERVICE_BUILD_SERVICE_KP" == "" ] && TDH_SERVICE_BUILD_SERVICE_KP=0.3.0
   [ "$TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES" == "" ] && TDH_SERVICE_BUILD_SERVICE_DEPENDANCIES=0.3.0
-  [ "$TKG_TANZU_KUBERNETES_GRID" == "" ] && TKG_TANZU_KUBERNETES_GRID=1.3.1
+  [ "$TKG_TANZU_KUBERNETES_GRID" == "" ] && TKG_TANZU_KUBERNETES_GRID=1.4.0
 
-  messageTitle "TDH Tools Docker Container (tdh-tools)"
+  messageTitle "TDH Tools Docker Container ($TDH_TOOLS_IMAGE)"
 
   # --- DOW3LOAD BUILD_SERVICE BINARIES ---
   if [ ! -f $TDH_DOCKER_FILES/kp-linux-${TDH_SERVICE_BUILD_SERVICE_KP} ]; then 
@@ -6849,22 +6864,22 @@ tdh_tools_build() {
      echo -e "\n\n\nyes" | nohup $TDHPATH/software/VMware-ovftool-4.4.1-16812187-lin.x86_64.bundle > /dev/null 2>&1
   fi
 
-  #messagePrint " ▪ Docker Image (tdh-tools) Name / ID"                  "tdh-tools:latest / $DOCKER_IMAGE_LATEST_ID"
+  #messagePrint " ▪ Docker Image ($TDH_TOOLS_IMAGE) Name / ID"                  "$TDH_TOOLS_IMAGE:latest / $DOCKER_IMAGE_LATEST_ID"
 
   cnt=$(docker images | egrep -c "^tdh-tools") 
   if [ $cnt -gt 0 ]; then 
     if [ "$DOCKER_IMAGE_CHKSUM" == "$DOCKER_CHKSUM" ]; then 
-      messagePrint " ▪ Dockerfile Checksum (files/tdh-tools/Dockerfile)"  "$DOCKER_CHKSUM"
-      messagePrint " ▪ Docker Image (tdh-tools) Checksum"                 "$DOCKER_IMAGE_CHKSUM => No Rebuild required"
+      messagePrint " ▪ Dockerfile Checksum (files/tdh-tools/$TDH_TOOLS_DOCKERFILE)"  "$DOCKER_CHKSUM"
+      messagePrint " ▪ Docker Image ($TDH_TOOLS_IMAGE) Checksum"                 "$DOCKER_IMAGE_CHKSUM => No Rebuild required"
     else
-      messagePrint " ▪ Dockerfile Checksum (files/tdh-tools/Dockerfile)"  "$DOCKER_CHKSUM"
-      messagePrint " ▪ Docker Image (tdh-tools) Checksum"                 "$DOCKER_IMAGE_CHKSUM => Rebuild required"
+      messagePrint " ▪ Dockerfile Checksum (files/tdh-tools/$TDH_TOOLS_DOCKERFILE)"  "$DOCKER_CHKSUM"
+      messagePrint " ▪ Docker Image ($TDH_TOOLS_IMAGE) Checksum"                 "$DOCKER_IMAGE_CHKSUM => Rebuild required"
       REBUILD_REQUIRED=1
 
       docker image rm $DOCKER_IMAGE_ID -f > /dev/null 2>&1
     fi
   else
-    messagePrint " ▪ Docker Image (tdh-tools:latest) Not available"       "Initial Build"
+    messagePrint " ▪ Docker Image ($TDH_TOOLS_IMAGE:latest) Not available"       "Initial Build"
     REBUILD_REQUIRED=1
   fi
 
@@ -6874,108 +6889,120 @@ tdh_tools_build() {
   fi
 
   # --- DOWNLOAD CARVEL TOOLS ---
-  if [ ! -d $TDH_DOCKER_FILES/cli-${TKG_TANZU_KUBERNETES_GRID} ]; then
-    TANZU_CLI_BUINDLE=$TDH_DOCKER_FILES/tanzu-cli-bundle-v${TKG_TANZU_KUBERNETES_GRID}-linux-amd64.tar
-    TANZU_CLI_BUINDLE=$TDH_DOCKER_FILES/tanzu-cli-bundle-linux-amd64.tar
-    if [ ! -f $TANZU_CLI_BUINDLE ]; then
-      . ~/.tanzu-demo-hub.cfg
+  if [ $BUILD_MODE == "tce" ]; then
+    TCE_DOWNLOAD_URL=https://github.com/vmware-tanzu/community-edition/releases/download/${TKG_COMNUNITY_EDITION_VERSION}
+    TCE_LINUX_PACKAGE=tce-linux-amd64-${TKG_COMNUNITY_EDITION_VERSION}
 
-      VMWCLI=/tmp/vmw-cli
+    if [ ! -d $TDH_DOCKER_FILES/$TCE_LINUX_PACKAGE ]; then
+      wget $TCE_DOWNLOAD_URL/${TCE_LINUX_PACKAGE}.tar.gz > /dev/null 2>&1
+      tar xvfz ${TCE_LINUX_PACKAGE}.tar.gz > /dev/null 2>&1
+      mv $TCE_LINUX_PACKAGE $TDH_DOCKER_FILES
+    fi
 
-      if [ ! -s $VMWCLI ]; then
-        messagePrint " ▪ Install Package (vmw-cli)" "installing"
-        docker run apnex/vmw-cli shell > $VMWCLI 2>/dev/null
-        if [ $? -ne 0 ]; then
-          echo "ERROR: faileed to run vmw-cli docker container"
-          echo "       => docker run apnex/vmw-cli shell > /tmp/vmw-cli"
+  else
+    if [ ! -d $TDH_DOCKER_FILES/cli-${TKG_TANZU_KUBERNETES_GRID} ]; then
+      TANZU_CLI_BUINDLE=$TDH_DOCKER_FILES/tanzu-cli-bundle-v${TKG_TANZU_KUBERNETES_GRID}-linux-amd64.tar
+      TANZU_CLI_BUINDLE=$TDH_DOCKER_FILES/tanzu-cli-bundle-linux-amd64.tar
+      if [ ! -f $TANZU_CLI_BUINDLE ]; then
+        . ~/.tanzu-demo-hub.cfg
+  
+        VMWCLI=/tmp/vmw-cli
+  
+        if [ ! -s $VMWCLI ]; then
+          messagePrint " ▪ Install Package (vmw-cli)" "installing"
+          docker run apnex/vmw-cli shell > $VMWCLI 2>/dev/null
+          if [ $? -ne 0 ]; then
+            echo "ERROR: faileed to run vmw-cli docker container"
+            echo "       => docker run apnex/vmw-cli shell > /tmp/vmw-cli"
+            exit 1
+          fi
+  
+          chmod 755 $VMWCLI
+        fi
+  
+        export VMWUSER="$TDH_MYVMWARE_USER"
+        export VMWPASS="$TDH_MYVMWARE_PASS"
+        $VMWCLI ls vmware_tanzu_kubernetes_grid > /dev/null 2>&1
+  
+        cnt=$($VMWCLI ls vmware_tanzu_kubernetes_grid 2>/dev/null | egrep "^tanzu-cli-bundle" | grep -c "$TKG_TANZU_KUBERNETES_GRID")
+        if [ $cnt -eq 0 ]; then 
+          echo "ERROR: failed to download tanzu-cli-bundle version: $TKG_TANZU_KUBERNETES_GRID from myVMware.com. This version does not" 
+          echo "       seam to be available anymore"
+          messageLine
+          $VMWCLI ls vmware_tanzu_kubernetes_grid | egrep "^tanzu-cli-bundle" 
+          messageLine
           exit 1
         fi
-
-        chmod 755 $VMWCLI
-      fi
-
-      export VMWUSER="$TDH_MYVMWARE_USER"
-      export VMWPASS="$TDH_MYVMWARE_PASS"
-      $VMWCLI ls vmware_tanzu_kubernetes_grid > /dev/null 2>&1
-
-      cnt=$($VMWCLI ls vmware_tanzu_kubernetes_grid 2>/dev/null | egrep "^tanzu-cli-bundle" | grep -c "$TKG_TANZU_KUBERNETES_GRID")
-      if [ $cnt -eq 0 ]; then 
-        echo "ERROR: failed to download tanzu-cli-bundle version: $TKG_TANZU_KUBERNETES_GRID from myVMware.com. This version does not" 
-        echo "       seam to be available anymore"
-        messageLine
-        $VMWCLI ls vmware_tanzu_kubernetes_grid | egrep "^tanzu-cli-bundle" 
-        messageLine
-        exit 1
-      fi
-
-      cnt=0
-      vmwfile=$($VMWCLI ls vmware_tanzu_kubernetes_grid 2>/dev/null | egrep "^tanzu-cli-bundle" | grep linux | tail -1 | awk '{ print $1 }')
-      while [ "$vmwfile" == "" -a $cnt -lt 5 ]; do
-        vmwfile=$($VMWCLI ls vmware_tanzu_kubernetes_grid 2>/dev/null | egrep "^tanzu-cli-bundle" | grep linux | tail -1 | awk '{ print $1 }')
-        let cnt=cnt+1
-        sleep 10
-      done
-
-#      if [ "tanzu-cli-bundle-v${TKG_TANZU_KUBERNETES_GRID}-linux-amd64.tar" != "$vmwfile" ]; then 
-#        echo "ERROR: $vmwfile from myVMware.com differs from the requested version $TKG_TANZU_KUBERNETES_GRID"
-#        echo "       You may want to change the version TKG_TANZU_KUBERNETES_GRID=$TKG_TANZU_KUBERNETES_GRID in"
-#        echo "       the files/tdh-tools/tdh-tools.cfg configuration file. Please see the available versions here:"
-#
-#        messageLine
-#        $VMWCLI ls vmware_tanzu_kubernetes_grid | egrep "^tanzu-cli-bundle"
-#        messageLine
-#        exit 1
-#      fi
-
-      messagePrint " ▪ Downloading Tanzu CLI Bundle" "$TDH_DOCKER_FILES/$vmwfile"
-
-      if [ "$vmwfile" == "" ]; then
-        echo "ERROR: failed to download $vmwfile"
-        echo "       => export VMWUSER=\"$TDH_MYVMWARE_USER\""
-        echo "       => export VMWPASS=\"$TDH_MYVMWARE_PASS\""
-        echo "       => $VMWCLI ls vmware_tanzu_kubernetes_grid"
-        echo ""
-        echo "INFO:  You may download tanzu-cli-bundle $TKG_TANZU_KUBERNETES_GRID manually from myVMware.com. an place it under:"
-        echo "       $TANZU_CLI_BUINDLE"
-        exit 1
-      else
+  
         cnt=0
-        while [ ! -f "$vmwfile" -a $cnt -lt 10 ]; do
-          $VMWCLI ls vmware_tanzu_kubernetes_grid > /dev/null 2>&1
-          $VMWCLI cp $vmwfile > /dev/null 2>&1
+        vmwfile=$($VMWCLI ls vmware_tanzu_kubernetes_grid 2>/dev/null | egrep "^tanzu-cli-bundle" | grep linux | tail -1 | awk '{ print $1 }')
+        while [ "$vmwfile" == "" -a $cnt -lt 5 ]; do
+          vmwfile=$($VMWCLI ls vmware_tanzu_kubernetes_grid 2>/dev/null | egrep "^tanzu-cli-bundle" | grep linux | tail -1 | awk '{ print $1 }')
           let cnt=cnt+1
-          sleep 30
+          sleep 10
         done
+  
+  #      if [ "tanzu-cli-bundle-v${TKG_TANZU_KUBERNETES_GRID}-linux-amd64.tar" != "$vmwfile" ]; then 
+  #        echo "ERROR: $vmwfile from myVMware.com differs from the requested version $TKG_TANZU_KUBERNETES_GRID"
+  #        echo "       You may want to change the version TKG_TANZU_KUBERNETES_GRID=$TKG_TANZU_KUBERNETES_GRID in"
+#        echo "       the files/tdh-tools/tdh-tools.cfg configuration file. Please see the available versions here:"
+    #
+#        messageLine
+    #        $VMWCLI ls vmware_tanzu_kubernetes_grid | egrep "^tanzu-cli-bundle"
+  #        messageLine
+  #        exit 1
+  #      fi
 
-        if [ ! -f $vmwfile ]; then
+        messagePrint " ▪ Downloading Tanzu CLI Bundle" "$TDH_DOCKER_FILES/$vmwfile"
+    
+        if [ "$vmwfile" == "" ]; then
           echo "ERROR: failed to download $vmwfile"
           echo "       => export VMWUSER=\"$TDH_MYVMWARE_USER\""
           echo "       => export VMWPASS=\"$TDH_MYVMWARE_PASS\""
           echo "       => $VMWCLI ls vmware_tanzu_kubernetes_grid"
-          echo "       => $VMWCLI cp $vmwfile"
           echo ""
           echo "INFO:  You may download tanzu-cli-bundle $TKG_TANZU_KUBERNETES_GRID manually from myVMware.com. an place it under:"
           echo "       $TANZU_CLI_BUINDLE"
           exit 1
         else
-          mv $vmwfile $TDH_DOCKER_FILES
+          cnt=0
+          while [ ! -f "$vmwfile" -a $cnt -lt 10 ]; do
+            $VMWCLI ls vmware_tanzu_kubernetes_grid > /dev/null 2>&1
+            $VMWCLI cp $vmwfile > /dev/null 2>&1
+            let cnt=cnt+1
+            sleep 30
+          done
+  
+          if [ ! -f $vmwfile ]; then
+            echo "ERROR: failed to download $vmwfile"
+            echo "       => export VMWUSER=\"$TDH_MYVMWARE_USER\""
+            echo "       => export VMWPASS=\"$TDH_MYVMWARE_PASS\""
+            echo "       => $VMWCLI ls vmware_tanzu_kubernetes_grid"
+            echo "       => $VMWCLI cp $vmwfile"
+            echo ""
+            echo "INFO:  You may download tanzu-cli-bundle $TKG_TANZU_KUBERNETES_GRID manually from myVMware.com. an place it under:"
+            echo "       $TANZU_CLI_BUINDLE"
+            exit 1
+          else
+            mv $vmwfile $TDH_DOCKER_FILES
+          fi
         fi
       fi
+  
+      if [ ! -d $TDH_DOCKER_FILES/cli-$TKG_TANZU_KUBERNETES_GRID  ]; then
+        rm -f ${TDH_DOCKER_FILES}/cli 
+        tar xf $TANZU_CLI_BUINDLE && mv cli ${TDH_DOCKER_FILES}/cli-$TKG_TANZU_KUBERNETES_GRID
+        cd $TDH_DOCKER_FILES && ln -s  cli-$TKG_TANZU_KUBERNETES_GRID cli
+      fi
+
+      REBUILD_REQUIRED_SOFTWARE=1       ## REBUILD REQUIRED BECAUSE OF SOFTWARE CHANGE
     fi
 
-    if [ ! -d $TDH_DOCKER_FILES/cli-$TKG_TANZU_KUBERNETES_GRID  ]; then
-      rm -f ${TDH_DOCKER_FILES}/cli 
-      tar xf $TANZU_CLI_BUINDLE && mv cli ${TDH_DOCKER_FILES}/cli-$TKG_TANZU_KUBERNETES_GRID
-      cd $TDH_DOCKER_FILES && ln -s  cli-$TKG_TANZU_KUBERNETES_GRID cli
+    if [ $REBUILD_REQUIRED_SOFTWARE -gt 0 ]; then 
+      messagePrint " ▪ Software Updates (files/tdh-tools/tdh-tools.cfg) )"  "=> Rebuild required"
+  
+      REBUILD_REQUIRED=1
     fi
-
-    REBUILD_REQUIRED_SOFTWARE=1       ## REBUILD REQUIRED BECAUSE OF SOFTWARE CHANGE
-  fi
-
-  if [ $REBUILD_REQUIRED_SOFTWARE -gt 0 ]; then 
-    messagePrint " ▪ Software Updates (files/tdh-tools/tdh-tools.cfg) )"  "=> Rebuild required"
-
-    REBUILD_REQUIRED=1
   fi
 
   if [ $REBUILD_REQUIRED -gt 0 ]; then 
