testing

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -90,8 +90,9 @@ sshEnvironment() {
     SSH_HOME=/home/ubuntu
     SSH_PRIVATE_KEY=~/.tanzu-demo-hub/KeyPair-Azure.pem
     SSH_HOST=$pip
-    SSH_OPTIONS="-o StrictHostKeyChecking=no -o RequestTTY=yes -o ServerAliveInterval=240 -o ClientAliveInterval=240"
     SSH_OPTIONS="-o StrictHostKeyChecking=no"
+    SSH_OPTIONS="-o StrictHostKeyChecking=no -o RequestTTY=yes -o ServerAliveInterval=240 -o ClientAliveInterval=240"
+    SSH_OPTIONS="-o StrictHostKeyChecking=no -o RequestTTY=yes -o ServerAliveInterval=240"
     SCP_OPTIONS="-o StrictHostKeyChecking=no"
     SSH_COMMAND="ssh -q $SSH_OPTIONS -i ${SSH_PRIVATE_KEY} ${SSH_USER}@${SSH_HOST}"
     SCP_COMMAND="scp -i ${SSH_PRIVATE_KEY} -r $SCP_OPTIONS"
@@ -1246,3 +1247,47 @@ exit
   fi
 }
 
+setDNSrecord() {
+  TKG_IPADRESS="$1"
+  DNS_PREFIX="$2"
+  DNS_SUFFIX="$3"
+  HOSTNAME="$4"
+  
+
+    DNS_NAME="*.${TKG_INGRESS}-${TKG_CLUSTER}"
+    messagePrint "- LoadBalancer PublicIP:" "$TKG_IPADRESS"
+    messagePrint "- Create DNS Entry for:" "*.${TKG_INGRESS}-${TKG_CLUSTER}.${DNS_PREFIX}.${DNS_SUFFIX}"
+
+    ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name ${DNS_PREFIX}.${DNS_SUFFIX} | jq -r '.HostedZones[0].Id')
+    ZONE_ID_STR=$(echo "${ZONE_ID}" | awk -F'/' '{ print $NF }')
+
+    if [ "${ZONE_ID}" != "" ]; then
+      ZONE="${HOSTNAME}.${DNS_PREFIX}.${DNS_SUFFIX}"
+
+      TMPROUTE53=/tmp/$$_tmp_route53.json
+      echo "{"                                                            >  $TMPROUTE53
+      echo "  \"Comment\": \"CREATE/DELETE/UPSERT a record \","           >> $TMPROUTE53
+      echo "  \"Changes\": [{"                                            >> $TMPROUTE53
+      echo "    \"Action\": \"UPSERT\","                                  >> $TMPROUTE53
+      echo "    \"ResourceRecordSet\": {"                                 >> $TMPROUTE53
+      echo "      \"Name\": \"${ZONE}\","                                 >> $TMPROUTE53
+      echo "      \"Type\": \"A\","                                       >> $TMPROUTE53
+      echo "      \"TTL\": 300,"                                          >> $TMPROUTE53
+      echo "      \"ResourceRecords\": [{ \"Value\": \"$TKG_IPADRESS\"}]" >> $TMPROUTE53
+      echo "    }"                                                        >> $TMPROUTE53
+      echo "  }]"                                                         >> $TMPROUTE53
+      echo "}"                                                            >> $TMPROUTE53
+
+      aws route53 change-resource-record-sets --hosted-zone-id $ZONE_ID \
+          --change-batch file://${TMPROUTE53} > /dev/null 2>&1
+      if [ $? -ne 0 ]; then
+        echo "ERROR: failed to set DNS for $hnm"
+        echo "       => aws route53 change-resource-record-sets --hosted-zone-id \"${ZONE_ID}\" \\"
+        echo "              --change-batch file://${TMPROUTE53}"
+        cat $TMPROUTE53
+        exit 1
+      fi
+
+      rm -f $TMPROUTE53
+    fi
+}
