TCE Tanzu Package for Harbor

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -6055,8 +6055,6 @@ InstallHarborRegistry() {
   HARBOR_HOSTNAME="harbor.apps-contour.$TDH_ENVNAME.$AWS_HOSTED_DNS_DOMAIN"
   NOTARY_HOSTNAME="notary.apps-contour.$TDH_ENVNAME.$AWS_HOSTED_DNS_DOMAIN"
 
-echo gaga
-kubectl get pods -A | egrep -c "^registry-harbor"
   messageTitle "Harbor Registry"
   cnt=$(kubectl get pods -A | egrep -c "^$NAMESPACE") 
   if [ $cnt -eq 0 ]; then
@@ -6189,7 +6187,7 @@ kubectl get pods -A | egrep -c "^registry-harbor"
     echo "apiVersion: projectcontour.io/v1"                                       >  $HARBOR_VALUES
     echo "kind: HTTPProxy"                                                        >> $HARBOR_VALUES
     echo "metadata:"                                                              >> $HARBOR_VALUES
-    echo "  name: harbor-proxy"                                                   >> $HARBOR_VALUES
+    echo "  name: harbor-httpproxy"                                               >> $HARBOR_VALUES
     echo "  namespace: $NAMESPACE"                                                >> $HARBOR_VALUES
     echo "  annotations:"                                                         >> $HARBOR_VALUES
     echo "    kubernetes.io/ingress.class: contour"                               >> $HARBOR_VALUES
@@ -8523,6 +8521,7 @@ TanzuPackage_Harbor () {
   PACKAGE_NAME=$1
   NAMESPACE=registry-harbor
   NAMESPACE=tanzu-system-registry
+  NAMESPACE=harbor
   PACKAGE_ID=$2
   PACKAGE_DES="Harbor OCI Registry"
 
@@ -8621,6 +8620,81 @@ TanzuPackage_Harbor () {
       rm -f /tmp/error.log
     fi
   fi
+
+    # --- ADD HTTPProxy ---
+    HARBOR_VALUES=/tmp/harbor_httpproxy.yaml
+    echo "apiVersion: projectcontour.io/v1"                                       >  $HARBOR_VALUES
+    echo "kind: HTTPProxy"                                                        >> $HARBOR_VALUES
+    echo "metadata:"                                                              >> $HARBOR_VALUES
+    echo "  name: harbor-httpproxy"                                               >> $HARBOR_VALUES
+    echo "  namespace: $NAMESPACE"                                                >> $HARBOR_VALUES
+    echo "  annotations:"                                                         >> $HARBOR_VALUES
+    echo "    kubernetes.io/ingress.class: contour"                               >> $HARBOR_VALUES
+    echo "spec:"                                                                  >> $HARBOR_VALUES
+    echo "  virtualhost:"                                                         >> $HARBOR_VALUES
+    echo "    fqdn: harbor.apps-contour.$TDH_ENVNAME.$AWS_HOSTED_DNS_DOMAIN"      >> $HARBOR_VALUES
+    echo "    tls:"                                                               >> $HARBOR_VALUES
+    echo "      secretName: $HARBOR_TLS_SECRET"                                   >> $HARBOR_VALUES
+    echo "  routes:"                                                              >> $HARBOR_VALUES
+    echo "    - conditions: "                                                     >> $HARBOR_VALUES
+    echo "      - prefix: /"                                                      >> $HARBOR_VALUES
+    echo "      services:"                                                        >> $HARBOR_VALUES
+    echo "        - name: harbor-portal"                                          >> $HARBOR_VALUES
+    echo "          port: 80"                                                     >> $HARBOR_VALUES
+    echo "      timeoutPolicy:"                                                   >> $HARBOR_VALUES
+    echo "        response: 600s"                                                 >> $HARBOR_VALUES
+    echo "    - conditions:"                                                      >> $HARBOR_VALUES
+    echo "      - prefix: /api/"                                                  >> $HARBOR_VALUES
+    echo "      services:"                                                        >> $HARBOR_VALUES
+    echo "        - name: harbor-core"                                            >> $HARBOR_VALUES
+    echo "          port: 80"                                                     >> $HARBOR_VALUES
+    echo "      timeoutPolicy:"                                                   >> $HARBOR_VALUES
+    echo "        response: 600s"                                                 >> $HARBOR_VALUES
+    echo "    - conditions:"                                                      >> $HARBOR_VALUES
+    echo "      - prefix: /service/"                                              >> $HARBOR_VALUES
+    echo "      services:"                                                        >> $HARBOR_VALUES
+    echo "        - name: harbor-core"                                            >> $HARBOR_VALUES
+    echo "          port: 80"                                                     >> $HARBOR_VALUES
+    echo "      timeoutPolicy:"                                                   >> $HARBOR_VALUES
+    echo "        response: 600s"                                                 >> $HARBOR_VALUES
+    echo "    - conditions:"                                                      >> $HARBOR_VALUES
+    echo "      - prefix: /v2/"                                                   >> $HARBOR_VALUES
+    echo "      services:"                                                        >> $HARBOR_VALUES
+    echo "        - name: harbor-core"                                            >> $HARBOR_VALUES
+    echo "          port: 80"                                                     >> $HARBOR_VALUES
+    echo "      timeoutPolicy:"                                                   >> $HARBOR_VALUES
+    echo "        response: 600s"                                                 >> $HARBOR_VALUES
+    echo "    - conditions:"                                                      >> $HARBOR_VALUES
+    echo "      - prefix: /chartrepo/"                                            >> $HARBOR_VALUES
+    echo "      services:"                                                        >> $HARBOR_VALUES
+    echo "        - name: harbor-core"                                            >> $HARBOR_VALUES
+    echo "          port: 80"                                                     >> $HARBOR_VALUES
+    echo "      timeoutPolicy:"                                                   >> $HARBOR_VALUES
+    echo "        response: 600s"                                                 >> $HARBOR_VALUES
+    echo "    - conditions:"                                                      >> $HARBOR_VALUES
+    echo "      - prefix: /c/"                                                    >> $HARBOR_VALUES
+    echo "      services:"                                                        >> $HARBOR_VALUES
+    echo "        - name: harbor-core"                                            >> $HARBOR_VALUES
+    echo "          port: 80"                                                     >> $HARBOR_VALUES
+    echo "      timeoutPolicy:"                                                   >> $HARBOR_VALUES
+    echo "        response: 600s"                                                 >> $HARBOR_VALUES
+
+    messagePrint " ▪ Deploy HTTPProxy for Harbor" "$HARBOR_VALUES"
+    kubectl apply -f $HARBOR_VALUES; ret=$?
+    if [ $ret -ne 0 ]; then
+      echo "ERROR: failed to deploy HTTPProxy"
+      if [ "$NATIVE" == "0" ]; then
+        echo "       => tools/${TDH_TOOLS}.sh"
+        echo "          tdh-tools:/$ kubectl apply -f $HARBOR_VALUES"
+        echo "          tdh-tools:/$ exit"
+      else
+        echo "       => kubectl apply -f $HARBOR_VALUES"
+      fi
+
+      exit 1
+    fi
+
+#gaga
 
   tanzu package installed get $PACKAGE_NAME -n $NAMESPACE -o json > /tmp/pkg.json
   pkg_stt=$(jq -r '.[]."status"' /tmp/pkg.json)
