verify kubectl generation

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -2119,6 +2119,14 @@ exit
       kubectl config use-context ${TDH_TKGMC_NAME}-admin@$TDH_TKGMC_NAME > /dev/null 2>&1
       context=$(kubectl config view -o json | jq -r '.contexts[].name' 2>/dev/null)
       tanzu management-cluster kubeconfig get --admin --export-file=${TKG_KUBECONFIG} > /dev/null 2>&1
+      if [ $? -ne 0 ]; then
+        echo "ERROR: failed to generate kubeconfig:"
+        echo "       => tanzu management-cluster kubeconfig get --admin --export-file=${TKG_KUBECONFIG}"
+        messageLine
+        tanzu management-cluster kubeconfig get --admin --export-file=${TKG_KUBECONFIG} 
+        messageLine
+        exit
+      fi
     fi
   fi
 
