copy /Users/sdu/.tanzu-demo-hub/cache directory to jump server

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -2233,17 +2233,27 @@ configureLDAP() {
 # Function Name ......: buildTDHToolsContainer
 # Function Purpose ...: Build the TDH Tools Container
 # ------------------------------------------------------------------------------------------
-# Argument ($1) ......: none
+# Argument ($1) ......: tkg / tce
 # ------------------------------------------------------------------------------------------
 # Return Value .......: 0 - SUCCEED, 1 - FAILED
 # ------------------------------------------------------------------------------------------
 buildTDHToolsContainer() {
   TKG_TYPE=$1
-  TKG_RELEASE=$2
 
   for rel in $(ls -1 $TDHPATH/files/tdh-tools/tdh-tools-tkg-*.cfg | sed -e 's/^.*tools-tkg-//g' -e 's/\.cfg//g'); do
-echo "$SSH_COMMAND -n \"[ -f $SSH_HOME/tanzu-demo-hub/scripts/uploadOVAimages.sh ] && tanzu-demo-hub/scripts/uploadOVAimages.sh tkg $rel\""
-    $SSH_COMMAND -n "[ -f $SSH_HOME/tanzu-demo-hub/scripts/buildTDHToolsContainer.sh ] && tanzu-demo-hub/scripts/buildTDHToolsContainer.sh tkg $rel"
+    $SSH_COMMAND -n "[ -f $SSH_HOME/tanzu-demo-hub/scripts/buildTDHToolsContainer.sh ] && tanzu-demo-hub/scripts/buildTDHToolsContainer.sh $TKG_TYPE $rel"; ret=$?
+    if [ $ret -eq 0 ]; then
+      echo "ERROR: failed to TDH Tools container on the Jumop Host"
+      if [ "$NATIVE" == "0" ]; then
+        echo "       => tools/${TDH_TOOLS}.sh"
+        echo "          tdh-tools:/$ $SSH_COMMAND -n \"[ -f $SSH_HOME/tanzu-demo-hub/scripts/buildTDHToolsContainer.sh ] && tanzu-demo-hub/scripts/buildTDHToolsContainer.sh $TKG_TYPE $rel\""
+        echo "          tdh-tools:/$ exit"
+      else
+        echo "       => $SSH_COMMAND -n \"[ -f $SSH_HOME/tanzu-demo-hub/scripts/buildTDHToolsContainer.sh ] && tanzu-demo-hub/scripts/buildTDHToolsContainer.sh $TKG_TYPE $rel\""
+      fi
+
+      exit 1
+    fi
 
   done
 }
@@ -10118,15 +10128,11 @@ tdh_tools_build() {
     REBUILD_REQUIRED=1
   fi
 
-echo gaga1
   if [ ! -s $TDH_DOCKER_FILES/mc ]; then
     #wget https://dl.min.io/client/mc/release/linux-amd64/mc > /dev/null 2>&1
     wget https://dl.min.io/client/mc/release/linux-amd64/mc 
-ls -la mc
-pwd
     mv mc $TDH_DOCKER_FILES && chmod a+x $TDH_DOCKER_FILES/mc
   fi
-echo gaga2
 
   # --- DOWNLOAD CARVEL TOOLS ---
   if [ $BUILD_MODE == "tce" ]; then
@@ -10188,7 +10194,6 @@ echo gaga2
 
   echo tdh-tools > $TDH_DOCKER_FILES/hostname
 
-echo gaga10
   if [ $BUILD_MODE == "tkg" ]; then
 echo gaga101
     # --- CLEANUP ---
